### ISSUE TITLE
QQ: change in behaviour? Unprocessed tagging for temp files?

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#858] opened 2017-03-14 14:41 UTC
Is the application now tagging folders indicating they are unprocessed? I kept getting "file cannot be found and I'm thinking this could be why. If its not, then i think Headphones is running rampant again, as it did this before to my completed downloads, but i've never seen it do this in the sab temp files.

Running SAB, SickRage, Couch, Headphones, LazyLib, Mylar, utorrent all on the same machine. Using SAB develop branch. First time i've seen this.
[KODI] - Guns N' Roses - Greatest Hits - Ain't It Fun (Unprocessed)

This is most disconcerting
 'Total.Recall.2012.EXTENDED.DirCut.BluRay.720p.H264-20-40.cp(tt1386703) (Unprocessed)'
drwxrwxrwx 3 root root  4096 Mar 14 04:06 'Total.Recall.2012.EXTENDED.DirCut.BluRay.720p.H264-20-40.cp(tt1386703) (Unprocessed[1])'
drwxrwxrwx 3 root root  4096 Mar  4 08:51 'Total.Recall.2012.EXTENDED.DirCut.BluRay.720p.H264-20-40.cp(tt1386703) (Unprocessed[1]) (Unprocessed)'

**Comment by Safihre** [comment] 2017-03-14 14:51
We didn't change anything. Why does it scan incomplete folders?

**Comment by mgaulton** [comment] 2017-03-14 14:57
Roger. Thanks for confirming.

That's the big question, it shouldn't even know those folders exist.

**Comment by mgaulton** [comment] 2017-03-14 15:09
it appears nzbToMedia sent a forceProcess on that path for some reason. Opened an issue over there.

**Comment by clinton-hall** [comment] 2017-03-15 10:38
is there a way to send "failed" downloads to another location (i.e. not "temp" not "complete") before post-processing?

**Comment by Safihre** [comment] 2017-03-15 12:15
@clinton-hall but why? They failed. Usually meaning no files at all.
What info do you need from the folder?

(PS: did you see my post about SABnzbd 2.0.0 https://github.com/clinton-hall/test/issues/4 ?)

**Comment by thezoggy** [comment] 2017-03-15 15:52
i think hes wanting it so that way his script doesnt mess with the downloads until sab is finished..

**Comment by Safihre** [comment] 2017-03-21 19:54
Anyone can tell me what the problem is that we, sabnzbd, should fix or change?

**Comment by clinton-hall** [comment] 2017-03-22 10:50
If it is not too problematic, then perhaps setting a "failed" path so that a failed download is moved from temp to failed before the pp script is called (when option `Post-Process Only Verified Jobs` is off and  `empty_postproc` is on).

**Comment by Safihre** [comment] 2017-03-22 14:40
But again: why? What use is the path to half or not at all downloaded files?

**Comment by thezoggy** [comment] 2017-03-22 20:37
@Safihre i do believe the ultimate problem is that sab reports back something is completed/failed slightly too early for 3rd party scripts that react upon the info. thus they end up stepping on sab's toes or cant do something to the file because sab is still messing with it. 

I've seen 'hacky' fixes like.. look at files timestamp and if its less than 30 secs old.. wait 30 secs and check again.. repeat until its 30secs old.. then proceed.

**Comment by Safihre** [comment] 2017-03-22 21:03
@thezoggy Just looking at the code, the only thing that happens after the script-call is cleanup of unwanted files from the cleanup list:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L482
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L526
Or did I miss something?

Although I don't think this is what @clinton-hall/@mgaulton are talking about.

**Comment by clinton-hall** [comment] 2017-03-23 12:03
@Safihre 
What has happened here is a unique set of circumstances, but is indeed repeatable.

1. sabnzbd completes download and fails due to either par repair or failure to extract.
2. nzbToMedia processes (in order to mark downlaod as failed in SR/CP/HP etc...
3. nzbToMedia does another attempt at extracting (requested by several users who also use torrent downlaoders, or sometimes have archives within archives)... in this case this extraction also failed.
4. additionally, even when failed nzbToMedia will attempt to see if any media can be recovered and checks for valid media files (on occasion it is possible that a sample file etc fails to extract but in-fact there is a playable video file) In this case it appears that nzbToMedia did find at least 1 playable media file (in fact it appears this was a 2 part downlaod and 1 part was ok, 1 part failed), and therefore marked this as successfull to try and process the valid media
5. nzbToMedia then sends this download to Headphones (it sends <path_to_temp>/<downloadName>)
6. Headphones did not process anything, so then nzbToMedia processes the next directory up (<path_to_temp>)
7. Headphones deletes all of the currently downloading material.


So, this scenario can only happen with a failed download that has valid media files being sent to HeadPhones. The main issue is point 6 above, that I recently changed.

Usually for a download the path would be <path_to_complete>/<category>/<downloadName> and this is sent to HeadPhones but it appears HeadPhones forceProcess api no longer takes the <downloadName> directory that contains the music, but must be passed the parent directory (basically it parses the parent directory and processes each "album" directory within it. To keep backwards compatibility I try <path_to_complete>/<category>/<downloadName> first, then if that doesn't work I send <path_to_complete>/<category>
In normal circumstances, since all other completed music downloads have been processed, this directory only contains the 1 album... but in the case where this "parent" directory is the temp downlaod directory, this obviously causes issues.

I am thinking I might just remove the valid media file check from HeadPhones category as (unlike movie/series downloads) music should be quicker/easier to snatch another and it probably isn't as important to try and save what data has been downloaded?

As I can tell, with CouchPotato, SickBeard/SickRage, Sonarr, Radarr this issues should not be repeatable as we only ever parse the download directory (never the parent).

**Comment by Safihre** [comment] 2017-03-28 14:59
Oke so closing this as a non-SABnzbd-related-issue. The API provides the path to the data SABnzbd and does nothing with the data except remove unwanted files after the script has run.
@thezoggy There might be a delay in when any file-operations are executed (we've seen this before), but this is not SAB's fault but between Python and the OS. Sometimes indeed when SAB sends a delete-command and python-function returns successful, the file stays on the disk for a few seconds more due to some (Linux!) weirdness.

**Closed by Safihre** 2017-03-28 14:59 UTC
