### ISSUE TITLE
QQ/FR: set job to failed from pre-queue script

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#546] opened 2016-04-14 14:34 UTC
Hey there, 

Reading the docs, i don't think this is possible but I use a prequeue python script and rather than reject, i'd like to queue it as failed so that nzbToMedia can still process it and notifiy the searcher (SB/CP) that that job isn't valid.

Thanks.

**Comment by shypike** [comment] 2016-04-14 14:47
You are right. Currently this is not possible. Let us think about a solution.

**Comment by mgaulton** [comment] 2016-04-14 14:51
Looks like this is a dupe of https://github.com/sabnzbd/sabnzbd/issues/504

**Comment by shypike** [comment] 2016-04-20 09:28
Duplicate of #504

**Closed by shypike** 2016-04-20 09:28 UTC
