### ISSUE TITLE
sabnzbd 1.0.2 does not open nzb files with © character in the filename

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#582] opened 2016-05-29 13:34 UTC
When sabnzbd is associated with .nzb files in windows (7) environment, and the nzb file contains a utf-8 © character, the nzb is not added to the download queue.
When clicked on an nzb, on intial startup however the nzb IS added to the download queue.
Subsequent clicks on such an nzb file does NOT add it to to download queue.

Added an example nzb.

[example nzb.zip](https://github.com/sabnzbd/sabnzbd/files/288349/example.nzb.zip)

**Comment by shypike** [comment] 2016-05-31 10:20
It's quite a problem.
The way SABnzbd passes the filename to the running instance of SABnzbd through a URL. It seems that the libraries we use for that, cannot properly handle UTF-8 or anything non-plain ASCII.
It should be a solvable problem, but it will take a while.

**Comment by mesa57** [comment] 2016-05-31 10:26
Thanks for the response. We will try to find a workaround for the time being.

**Comment by Safihre** [comment] 2016-05-31 10:30
Use the Watched folder maybe? This one should support any charters.

**Comment by mesa57** [comment] 2016-05-31 10:38
Correct, the watched folder works fine.

**Comment by Safihre** [comment] 2016-06-02 06:20
Weird! When I add this NZB using _Add NZB_ in the interface I hear 2 of Windows's error sounds through my speakers.. This happens in every browser on Windows. How is that possible?
The NZB is still added though.

**Comment by mesa57** [comment] 2016-06-02 07:15
At this moment we are reverting to sabnzbd 0.7.20
Users (spotnet) are not only reporting this problem, but also some weird performance issues.

**Comment by shypike** [comment] 2016-06-02 07:18
We know the cause, the next step is to solve the issue.
Which isn't easy, because it's in the third-party web-framework we 're using.

**Comment by shypike** [comment] 2016-06-14 19:31
Fixed in commit 29e45da431fcce4a32cb25227650e443ecc2ff0b, so in 1.0.3

**Closed by shypike** 2016-06-14 19:31 UTC
Labels: 1 - Confirmed, 3 - Fixed

**Comment by mesa57** [comment] 2016-06-14 19:43
Thanks, that is fast :smile:
