### ISSUE TITLE
Top menu on config doesn't render properly on Linux (Chrome)

### ISSUE THREAD

**Issue by KaoticEvil** [sabnzbd/sabnzbd#523] opened 2016-03-25 00:14 UTC
Topic says it all.. Running latest SABnzbd (installed from AUR).

System is as follows:
Chrome Version 50.0.2661.37 beta (64-bit)
Arch Linux (fully updated)
Firefox 45.0.1
Konqueror 4.14.17 (Using KDE Development Platform 4.14.18)

Scrolling down doesn't make a difference, the menu at the top doesn't move

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/12788790/14034781/742d8042-f1f4-11e5-9ae3-d0df28c808e3.png)

Firefox: 
![firefox](https://cloud.githubusercontent.com/assets/12788790/14034784/7e6f7ff6-f1f4-11e5-9a0d-9d8a98baf744.png)

Konqueror:
![konqi](https://cloud.githubusercontent.com/assets/12788790/14034786/846fd892-f1f4-11e5-80b6-985093148ee3.png)

**Comment by thezoggy** [comment] 2016-03-25 10:25
first off, not sure why your on `0.8.x` and not on `1.0.0` or 1.1.x... so may just be an issue thats already fixed in newer code.

at first glance it looks like your missing some css/fonts? check console for any errors..

**Comment by Safihre** [comment] 2016-03-25 11:11
Indeed it looks like Chrome substituted some other font in there? Any idea what it might be? That's why it doesn't fit.

**Comment by KaoticEvil** [comment] 2016-03-27 02:00
Yeah, for some reason the AUR version shows 0.8.0 when it's really 1.x series. I'm not at my computer at the moment, but I'll check the console a little later on.

**Comment by KaoticEvil** [comment] 2016-03-28 16:56
Followup: I just noticed that Chrome seems to render the logo image above the menu, but if I resize the window (or even the frame) it doesn't happen:

Normal: ![http://www.enlightenment.org/ss/e-56f961238b3cb1.34757462.jpg](http://www.enlightenment.org/ss/e-56f961238b3cb1.34757462.jpg)

Resized: ![http://www.enlightenment.org/ss/e-56f96174300c10.42325855.jpg](http://www.enlightenment.org/ss/e-56f96174300c10.42325855.jpg)

I tracked the window width, and anything above 1210px wide moves the logo above.

Even just opening the Developer Tools frame resizes it so that it renders correctly:
![http://www.enlightenment.org/ss/e-56f961f443c4e3.31134757.jpg](http://www.enlightenment.org/ss/e-56f961f443c4e3.31134757.jpg)

**Comment by Safihre** [comment] 2016-03-28 17:36
@KaoticEvil yes we programmed it to do that below 1200pixels on any browser or platform, it will show the icons.

The problem is the font Chrome on Arch, which for some reason is rendered differently:
![image](https://cloud.githubusercontent.com/assets/5703454/14084711/60622308-f51c-11e5-8519-b789eca4ce98.png)

**Comment by thezoggy** [comment] 2016-03-28 17:54
@KaoticEvil, did you set a default font in chrome? (if so, thats overriding what we specified to use/coded for)

**Comment by thezoggy** [comment] 2016-03-28 17:56
looks like to be a common arch linux problem with firefox/chrome:
https://wiki.archlinux.org/index.php/Infinality#Firefox.2FChrome_browsers_rendering_monospaced_with_proportional_font

run:
`fc-match "monospace"`

and report back what it shows

**Comment by sanderjo** [comment] 2016-03-29 21:03
I can NOT reproduce this with Chromium on Ubuntu Linux:

![chrome ubuntu sab glitter](https://cloud.githubusercontent.com/assets/1273502/14123738/585b902c-f602-11e5-8be8-70ac9b5a60d0.png)

**Comment by thezoggy** [comment] 2016-04-12 18:27
try doing:
`fc-cache -fr`

**Comment by KaoticEvil** [comment] 2016-04-13 14:15
No output, but no change either.

**Comment by Safihre** [comment] 2016-05-31 10:44
Can be closed, in 1.1.0 the new logo is smaller so even these weird fonts (which are not the fault of SABnzbd, but of the OS) will still not mess up the menu bar anymore.

**Closed** 2016-06-01 06:51 UTC
