### ISSUE TITLE
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:852)

### ISSUE THREAD

**Issue by wavecentral** [sabnzbd/sabnzbd#1829] opened 2021-03-16 01:59 UTC
On or around 3/11/2021 I started getting the following error below.  It appears in the logs anytime I visit my homepage of sabnzbd.  Everything seems to be working ok with my news servers, test connections works, and I'm successfully downloading.

Version: | 3.2.0 [7be9281]
Uptime: 49m
Config file: /var/lib/plexmediaserver/.sabnzbd/sabnzbd.ini
Parameters: "/usr/bin/sabnzbdplus" "--daemon" "--pidfile" "/var/run/sabnzbdplus/pid" "--server" "0.0.0.0:8095"
Python Version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] [UTF-8]
OpenSSL: OpenSSL 1.1.1 11 Sep 2018

```2021-03-11 00:28:51,808::INFO::[notifier:122] Sending notification: Error - [11/Mar/2021:00:28:51] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:852)
 (type=error, job_cat=None)```

**Comment by thezoggy** [comment] 2021-03-16 05:22
It's because you are using self signed certs or a cert that does not have a CA which  tgen does not validated with sslv3.

**Comment by thezoggy** [comment] 2021-03-16 05:22
Also your using old openssl/python which means your ca-bundle is probably pretty old as well

**Comment by Safihre** [comment] 2021-03-16 06:20
This is caused by the ancient CherryPy included with the `sabnzbdplus` package on Ubuntu.
@jcfp I am kind of done with this. I want to require CherryPy 18.6 (which is already 1 year old by now) starting with 3.3.0.

**Comment by Safihre** [comment] 2021-03-16 08:03
(sorry @jcfp if that sounded harsh, CherryPy just annoys me in general 😅)

**Comment by sanderjo** [comment] 2021-03-16 08:05
> I am kind of done with this. '

Yes, understandably. Probably some Ubuntu or Debian policy?

> I want to require CherryPy 18.6 (which is already 1 year old by now) starting with 3.3.0.

FWIW: It is only a problem if cherrypy is too low AND https enabled on SAB webgui AND rogue clients/scanners (99.99999% from Internet) thus AND SAB accessible from Internet (0.0.0.0 + port forwarding / no-NAT)

So ... first: a big fat warning with older cherrypy **AND** https enabled AND SAB listening to 0.0.0.0 ... ?

**Comment by thezoggy** [comment] 2021-03-16 15:00
the goal should be to stop the tracebacks/warnings generated. If increasing cherrypy can do that we dhould. But I get these myself using latest windows binary builds.. so I don't think it's that simple.

**Comment by Safihre** [comment] 2021-03-17 06:11
Yes, some are not caught by Cherrypy, but a whole lot more than the none that are caught by the super old Cherrypy.

**Comment by thezoggy** [comment] 2021-03-17 06:43
shame this cherrpy option doesnt suppress it (just tried):
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1374

looking through sab source we have a lot of cherrpy 'quirks/issues' that we have to deal with...  wonder how many of those we could drop in lieu of forcing newer version as well

**Comment by Safihre** [comment] 2021-03-17 07:46
Actually I have been experimenting with using `aiohttp` instead. But it introduces a whole new set of problems and requires a major refractor of all the interface code.

**Comment by jcfp** [comment] 2021-03-17 11:07
> (sorry @jcfp if that sounded harsh, CherryPy just annoys me in general sweat_smile)

I dislike the outdated cherrypy package as much as anyone, even had to add a patch recently so it wouldn't break sab with python 3.9. I'll be in a better position to work on that upgrade once I get full upload rights to Debian.

@sanderjo disabling https just to prevent (some) tracebacks seems disproportionate and likely to be removed by distros.

**Comment by thezoggy** [comment] 2021-03-17 14:19
Perhaps we should just document this issue on our wiki and add thing to our ghi about common problems and link to it

**Comment by jcfp** [comment] 2021-03-27 08:15
> I'll be in a better position to work on that upgrade once I get full upload rights to Debian.

This is now in progress on the Debian end: I packaged several new dependencies (jaraco stuff) and once they make it out of [new queue](https://ftp-master.debian.org/new.html), I'll upload cherrypy 18.x as well. Work on the latter is 99% complete and will soon appear in a branch on https://salsa.debian.org/python-team/packages/cherrypy3.

**Comment by Safihre** [comment] 2021-03-27 08:23
❤️

**Comment by Safihre** [comment] 2021-04-23 09:19
Closing this, @jcfp 's updates to CherryPy will fix things.

**Closed by Safihre** 2021-04-23 09:19 UTC
