### ISSUE TITLE
QQ: directunpack folder name

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1017] opened 2017-08-30 00:37 UTC
So i've noticed that jobs are left named _UNPACK_* after the job is done, while regular unpacking renames to remove the _UNPACK_. Is this the expected behaviour?

**Comment by thezoggy** [comment] 2017-08-30 01:23
dupe of https://github.com/sabnzbd/sabnzbd/issues/1015

**Comment by Safihre** [comment] 2017-08-30 06:01
No that's not expected behavior. Indeed what OS and sabnzbd version are you on? 

And you mean this happens for every download? Not just failed ones? 
If you set logging to Debug, you can check in the log what is going wrong with the renaming.

**Comment by mgaulton** [comment] 2017-08-30 14:51
Opensuse LEAP 42.3
latest git pull from master for sab

It seems like its happening for some and not all, i happened to be monitoring as like 40 downloads hit the queue and noticed that while it said it was successfully downloaded, the folders still had that in the name. looking through my download folders, it was across multiple categories. The files still got processed successfully by nzbToMedia though. I'll turn on debug and check a few.

**Comment by mgaulton** [comment] 2017-08-30 15:12
I'm running with debug but poked a big more in the logs


I found this 
/tmp/sabnzbd/sabnzbd.log.3:2017-08-30 10:16:36,303::ERROR::[__init__:897] Saving /home/@downloads/Miracles.from.Heaven.2016.720p.WEBRip.AAC.2.0.x264-SRG.cp(tt4257926)/__A                                           DMIN__/__renames__ failed
/tmp/sabnzbd/sabnzbd.log.3:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Miracles.from.Heaven.2016.720p.WEBRip.AAC.2.0.x264-SRG.cp(tt4257926)/__ADMIN__                                           /__renames__'

then this 
server6:~ # grep -i 'No such file or directory:' /tmp/sabnzbd/sabnzbd.log*
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E09.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E10.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E11.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E12.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E13.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E14.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E17.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E18.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E23.DVDRip.X264-REWARD.1/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Madam.Secretary.S02E23.DVDRip.X264-REWARD.2/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log.1:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Miracles.from.Heaven.2016.720p.WEBRip.AAC.2.0.x264-SRG.cp(tt4257926)/__ADMIN__/SABnzbd_nzo_t0_9ZJ'
/tmp/sabnzbd/sabnzbd.log.2:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Star.Trek.Voyager.S01E08.HDTV.x264.F1rebladerunner/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log.3:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Jungle.Book.2016.R5.Screener.XviD-Avi.cp(tt3040964)/__ADMIN__/__renames__'
/tmp/sabnzbd/sabnzbd.log.3:IOError: [Errno 2] No such file or directory: u'/home/@downloads/Miracles.from.Heaven.2016.720p.WEBRip.AAC.2.0.x264-SRG.cp(tt4257926)/__ADMIN__/__renames__'

**Comment by Safihre** [comment] 2017-08-30 15:15
That's alright and normal.

**Comment by Safihre** [comment] 2017-08-30 15:16
Just to be sure: you're Complete and Incomplete directory are not pointing to the same directory right? 

The errors would be about the Complete directory, not about Incomplete.

**Comment by mgaulton** [comment] 2017-08-30 15:40
correct, they are different I was thinking that the Admin/renames file was where it stored info for renaming the files later. I'll keep checking.
My incompletes is /home/@downloads
my completes is /home/@send/

**Comment by thezoggy** [comment] 2017-08-30 19:30
why do all your download folders have a dot at the start...  usually that would be hidden/private files..

**Comment by Safihre** [comment] 2017-09-06 20:15
@mgaulton Any more problems?
@thezoggy the dots in the folders were because the log output wasn't wrapped in `

**Comment by Safihre** [comment] 2017-09-16 08:15
Closing due to lack of response, feel free to reopen when more information is available 👍

**Closed by Safihre** 2017-09-16 08:15 UTC

**Comment by mgaulton** [comment] 2017-11-02 19:29
So i finally caught one in the logs.
Nothing changed. Jobs before and after were successful. Happens very sporadically, across all categories. Not sure if its just same to manually rename them and try and process them manually.


ERROR an hour agoError renaming "/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)" to "/home/@send/Books/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)"
--
ERROR an hour agoCannot change permissions of /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)

sabnzbd.log.2:2017-11-02 14:17:57,892::DEBUG::[misc:1542] Applying permissions 0666 (octal) to /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar
sabnzbd.log.2:2017-11-02 14:17:57,896::DEBUG::[misc:1136] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/SABnzbd_nzf_gbNfET
sabnzbd.log.2:2017-11-02 14:17:57,908::INFO::[misc:943] Creating directories: /home/@send/Books/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:57,909::DEBUG::[misc:1058] Renaming "/home/@send/Books/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)" to "/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)"
sabnzbd.log.2:2017-11-02 14:17:57,909::DEBUG::[directunpacker:359] Running unrar for DirectUnpack ['/usr/bin/unrar', 'x', '-vp', '-tsm-', '-idp', '-o+', '-p-', u'/home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar', u'/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/']
sabnzbd.log.2:2017-11-02 14:17:58,169::DEBUG::[misc:1136] [sabnzbd.remove_data] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/SABnzbd_nzo_BEgAvS
sabnzbd.log.2:2017-11-02 14:17:58,176::INFO::[nzbqueue:434] [sabnzbd.assembler.run] Removed job William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:58,265::INFO::[postproc:307] Starting Post-Processing on William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096) => Repair:True, Unpack:True, Delete:True, Script:None, Cat:books
sabnzbd.log.2:2017-11-02 14:17:58,266::INFO::[postproc:630] Starting verification and repair of William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:58,266::INFO::[__init__:909] [sabnzbd.postproc.parring] /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/__verified__ missing
sabnzbd.log.2:2017-11-02 14:17:58,266::INFO::[postproc:666] No par2 sets for William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:58,266::DEBUG::[newsunpack:2082] build_filelists(): rars: [u'/home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar']
sabnzbd.log.2:Extracting from /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar
sabnzbd.log.2:Extracting  /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/William Shakespeare - The Merry Wives of Windsor [RSC] (retail) (epub).epub  OK
sabnzbd.log.2:WARNING: Cannot change attributes of /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/William Shakespeare - The Merry Wives of Windsor [RSC] (retail) (epub).epub
sabnzbd.log.2:2017-11-02 14:17:59,382::DEBUG::[__init__:877] [sabnzbd.postproc.parring] Saving data for __verified__ in /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__
sabnzbd.log.2:2017-11-02 14:17:59,382::INFO::[postproc:686] Verification and repair finished for William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:59,383::INFO::[postproc:350] Running unpack_magic on William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:59,387::DEBUG::[newsunpack:2082] build_filelists(): rars: [u'/home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar']
sabnzbd.log.2:2017-11-02 14:17:59,387::INFO::[newsunpack:263] Unrar starting on /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)
sabnzbd.log.2:2017-11-02 14:17:59,387::DEBUG::[newsunpack:478] Rar_sets: {u'31928-15260-2839': [u'/home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar']}
sabnzbd.log.2:2017-11-02 14:17:59,387::DEBUG::[newsunpack:540] rar_unpack(): Rars: [u'/home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar']
sabnzbd.log.2:2017-11-02 14:17:59,387::DEBUG::[newsunpack:541] rar_unpack(): Newfiles: [u'/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/William Shakespeare - The Merry Wives of Windsor [RSC] (retail) (epub).epub']
sabnzbd.log.2:2017-11-02 14:17:59,388::DEBUG::[misc:1136] [sabnzbd.newsunpack.rar_unpack] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/31928-15260-2839.rar
sabnzbd.log.2:2017-11-02 14:17:59,388::INFO::[newsunpack:267] Unrar finished on /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)
sabnzbd.log.2:2017-11-02 14:17:59,391::INFO::[postproc:355] unpack_magic finished on William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:59,391::DEBUG::[misc:1542] Applying permissions 0666 (octal) to /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:2017-11-02 14:17:59,391::ERROR::[misc:1547] Cannot change permissions of /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)
sabnzbd.log.2:OSError: [Errno 2] No such file or directory: '/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)'
sabnzbd.log.2:2017-11-02 14:17:59,424::DEBUG::[misc:1058] Renaming "/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)" to "/home/@send/Books/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)"
sabnzbd.log.2:2017-11-02 14:17:59,428::ERROR::[postproc:411] Error renaming "/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)" to "/home/@send/Books/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)"
sabnzbd.log.2:IOError: [Errno 2] No such file or directory: u'/home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)'
sabnzbd.log.2:2017-11-02 14:17:59,440::INFO::[postproc:528] Cleaning up William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096) (keep_basic=False)
sabnzbd.log.2:2017-11-02 14:17:59,440::DEBUG::[misc:1136] [sabnzbd.misc.remove_all] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/William.Shakespeare-The.Merry.Wives.of.Windsor.[RSC].(retail).(epub).nzb.gz
sabnzbd.log.2:2017-11-02 14:17:59,440::DEBUG::[misc:1136] [sabnzbd.misc.remove_all] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/SABnzbd_attrib
sabnzbd.log.2:2017-11-02 14:17:59,441::DEBUG::[misc:1136] [sabnzbd.misc.remove_all] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096).nzb.gz
sabnzbd.log.2:2017-11-02 14:17:59,441::DEBUG::[misc:1136] [sabnzbd.misc.remove_all] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/SABnzbd_nzo_PxRO6_
sabnzbd.log.2:2017-11-02 14:17:59,441::DEBUG::[misc:1136] [sabnzbd.misc.remove_all] Deleting file /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__/__verified__
sabnzbd.log.2:2017-11-02 14:17:59,442::DEBUG::[misc:1142] [sabnzbd.misc.remove_all] Deleting dir /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)/__ADMIN__
sabnzbd.log.2:2017-11-02 14:17:59,443::DEBUG::[misc:1142] [sabnzbd.nzbstuff.purge_data] Deleting dir /home/@downloads/William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL.(32837096)
sabnzbd.log.2:2017-11-02 14:17:59,455::INFO::[database:272] Added job William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096) to history
grep: temp: Is a directory

**Comment by mgaulton** [comment] 2017-11-02 19:32
Grabbing the previous 300 lines.

**Comment by mgaulton** [comment] 2017-11-02 19:33
https://gist.github.com/mgaulton/aa5575627aa8b2baeacc56e3164fdd8f

**Comment by Safihre** [comment] 2017-11-03 13:03
Aah, do you have some ebook automation running? 
Because it seems something is deleting the files before SABnzbd is getting to them. 
Or sort of permissions problem, even unrar is having problems:
```
Extracting  /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/William Shakespeare - The Merry Wives of Windsor [RSC] (retail) (epub).epub  OK
WARNING: Cannot change attributes of /home/@send/Books/_UNPACK_William Shakespeare - The Personal Shakespeare Vol  7 of 15 LL (32837096)/William Shakespeare - The Merry Wives of Windsor [RSC] (retail) (epub).epub
```
So, not SABnzbd related I think.

**Comment by mgaulton** [comment] 2017-11-06 16:42
Its happened for TV, Movies, Books etc
The only automation is nzbToMedia, which doesn't do books.
