### ISSUE TITLE
SABnzbd shutting down directly when choosing this at 'On queue finish'

### ISSUE THREAD

**Issue by zaadstra** [sabnzbd/sabnzbd#1099] opened 2018-02-04 17:36 UTC
v2.3.2, windows / v2.3.1 linux + Firefox 58

I notice that when I select 'On queue finish' - Shutdown SABnzbd it closes down right away.
Also, after some testing and looking in that menu, there were more sudden shutdowns.
Also, when shutting down after downloading, manually, I get stuck on the lost connection screen while in the past there was a nice "... has shut down now" page. When looking at the menu option, the program suddenly shut down again.

On a Synology Nas, currently v2.3.1 I see when scanning watchfolder, it always shuts down. I believe this is since v2.3.1. In the log I see a shutdown request (not by me), then all nzb's in watchfolder are imported and the program shuts down. When restarting the service, the queue is processed. Note, the watchfolder contains 50-100+ files. And some text files (this never was an issue).
Today I looked on the nas and found the service in the stopped state.

Since the last update (or two), these strange things happen. Perhaps some code has been changed for these functions and this has awkward side effects.

-zaadstra

**Comment by Safihre** [comment] 2018-02-04 18:21
What browser do you use?

**Comment by Safihre** [comment] 2018-02-04 18:35
Could you also maybe switch logging to +Debug and then post these relevant sections that you describe where SAB is suddenly restarted?
I just tested Firefox and Chrome on Windows and cannot reproduce the sudden shutdowns so far.

**Comment by zaadstra** [comment] 2018-02-04 19:02
Firefox 58, plugin uBlcok-origin and some others.

Here is a log fragment.  After setting log to debug I just hoovered around a bit above the interface.

2018-02-04 19:56:40,311::INFO::[SABnzbd:1148] --------------------------------
2018-02-04 19:56:40,311::INFO::[SABnzbd:1149] SABnzbd.exe-2.3.2 (rev=<HASH>b7b244fb0366e9a)
2018-02-04 19:56:40,312::INFO::[SABnzbd:1150] Full executable path = C:\Program Files\SABnzbd\SABnzbd.exe
2018-02-04 19:56:40,312::INFO::[SABnzbd:1156] Platform = Windows-7-6.1.7601-SP1 (win64)
2018-02-04 19:56:40,313::INFO::[SABnzbd:1161] Python-version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
2018-02-04 19:56:40,313::INFO::[SABnzbd:1162] Arguments = "C:\Program Files\SABnzbd\SABnzbd.exe"
2018-02-04 19:56:40,313::INFO::[SABnzbd:1167] Preferred encoding = cp1252
2018-02-04 19:56:40,313::INFO::[SABnzbd:1177] SSL version = OpenSSL 1.0.2k  26 Jan 2017
2018-02-04 19:56:40,313::INFO::[SABnzbd:1184] Loaded additional certificates from C:\Program Files\SABnzbd\cacert.pem
2018-02-04 19:56:40,313::INFO::[SABnzbd:1225] Read INI file C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini
2018-02-04 19:56:40,316::INFO::[postproc:100] Loading postproc queue
2018-02-04 19:56:40,318::INFO::[__init__:974] [N/A] C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\Rating.sab missing
2018-02-04 19:56:40,319::INFO::[scheduler:207] Setting schedule for midnight BPS reset
2018-02-04 19:56:40,319::INFO::[__init__:345] All processes started
2018-02-04 19:56:40,319::INFO::[SABnzbd:280] Web dir is C:\Program Files\SABnzbd\interfaces\Glitter
2018-02-04 19:56:40,319::INFO::[SABnzbd:280] Web dir is C:\Program Files\SABnzbd\interfaces\Config
2018-02-04 19:56:40,325::INFO::[config:853] Writing settings to INI file C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini
2018-02-04 19:56:40,342::INFO::[SABnzbd:404] SABYenc module (v3.3.2)... found!
2018-02-04 19:56:40,342::INFO::[SABnzbd:421] Cryptography module (v2.1.4)... found!
2018-02-04 19:56:40,342::INFO::[SABnzbd:426] par2 binary... found (C:\Program Files\SABnzbd\win\par2\par2.exe)
2018-02-04 19:56:40,342::INFO::[SABnzbd:431] MultiPar binary... found (C:\Program Files\SABnzbd\win\par2\multipar\par2j64.exe)
2018-02-04 19:56:40,342::INFO::[SABnzbd:436] UNRAR binary... found (C:\Program Files\SABnzbd\win\unrar\x64\UnRAR.exe)
2018-02-04 19:56:40,342::INFO::[SABnzbd:451] unzip binary... NOT found!
2018-02-04 19:56:40,342::INFO::[SABnzbd:454] 7za binary... found (C:\Program Files\SABnzbd\win\7zip\7za.exe)
2018-02-04 19:56:40,348::INFO::[SABnzbd:1380] Starting web-interface on 127.0.0.1:8080
2018-02-04 19:56:40,348::INFO::[_cplogging:219] [04/Feb/2018:19:56:40] ENGINE Bus STARTING
2018-02-04 19:56:40,568::INFO::[_cplogging:219] [04/Feb/2018:19:56:40] ENGINE Serving on http://127.0.0.1:8080
2018-02-04 19:56:40,568::INFO::[_cplogging:219] [04/Feb/2018:19:56:40] ENGINE Bus STARTED
2018-02-04 19:56:40,569::INFO::[SABnzbd:1418] Starting SABnzbd.exe-2.3.2
2018-02-04 19:56:40,569::INFO::[postproc:187] Completed Download Folder D:\DownloadNews\Completed is not on FAT
2018-02-04 19:56:40,572::INFO::[dirscanner:330] Dirscanner starting up
2018-02-04 19:56:40,575::INFO::[urlgrabber:81] URLGrabber starting up
2018-02-04 19:56:40,575::INFO::[panic:209] Launching browser with http://127.0.0.1:8080/sabnzbd
2018-02-04 19:56:41,729::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2018-02-04 19:57:37,720::INFO::[config:853] Writing settings to INI file C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini
2018-02-04 19:58:14,964::INFO::[interface:404] Shutdown requested by interface
2018-02-04 19:58:14,964::INFO::[__init__:381] SABnzbd shutting down...
2018-02-04 19:58:14,966::INFO::[directunpacker:445] Aborting all DirectUnpackers
2018-02-04 19:58:14,966::DEBUG::[__init__:394] Stopping URLGrabber
2018-02-04 19:58:14,966::INFO::[urlgrabber:76] URLGrabber shutting down
2018-02-04 19:58:14,966::DEBUG::[__init__:401] Stopping rating
2018-02-04 19:58:15,861::DEBUG::[rating:157] Stopping ratings
2018-02-04 19:58:15,861::DEBUG::[__init__:408] Stopping dirscanner
2018-02-04 19:58:15,861::INFO::[dirscanner:321] Dirscanner shutting down
2018-02-04 19:58:15,861::DEBUG::[__init__:416] Stopping downloader
2018-02-04 19:58:15,861::INFO::[downloader:508] Shutting down
2018-02-04 19:58:15,864::DEBUG::[__init__:419] Stopping assembler
2018-02-04 19:58:15,864::INFO::[assembler:67] Shutting down
2018-02-04 19:58:15,865::DEBUG::[__init__:426] Stopping postprocessor
2018-02-04 19:58:15,867::INFO::[nzbqueue:277] Saving queue
2018-02-04 19:58:15,867::DEBUG::[__init__:948] [sabnzbd\nzbqueue.pyo.save] Saving data for queue10.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\queue10.sab
2018-02-04 19:58:15,868::DEBUG::[__init__:948] [sabnzbd\bpsmeter.pyo.save] Saving data for totals10.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\totals10.sab
2018-02-04 19:58:15,871::DEBUG::[__init__:948] [sabnzbd\rss.pyo.save] Saving data for rss_data.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\rss_data.sab
2018-02-04 19:58:15,871::DEBUG::[__init__:948] [sabnzbd\dirscanner.pyo.save] Saving data for watched_data2.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\watched_data2.sab
2018-02-04 19:58:15,872::INFO::[postproc:94] Saving postproc queue
2018-02-04 19:58:15,872::DEBUG::[__init__:948] [sabnzbd\postproc.pyo.save] Saving data for postproc2.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\postproc2.sab
2018-02-04 19:58:15,874::DEBUG::[scheduler:257] Terminating scheduler
2018-02-04 19:58:15,874::INFO::[__init__:445] All processes stopped
2018-02-04 19:58:15,874::INFO::[_cplogging:219] [04/Feb/2018:19:58:15] ENGINE Bus STOPPING
2018-02-04 19:58:16,686::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
2018-02-04 19:58:16,686::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus STOPPED
2018-02-04 19:58:16,686::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus EXITING
2018-02-04 19:58:16,686::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus EXITED
2018-02-04 19:58:16,770::INFO::[interface:404] Shutdown requested by interface
2018-02-04 19:58:16,770::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus STOPPING
2018-02-04 19:58:16,770::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) already shut down
2018-02-04 19:58:16,772::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus STOPPED
2018-02-04 19:58:16,772::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus EXITING
2018-02-04 19:58:16,772::INFO::[_cplogging:219] [04/Feb/2018:19:58:16] ENGINE Bus EXITED
2018-02-04 19:58:18,061::INFO::[SABnzbd:1554] Leaving SABnzbd

**Comment by Safihre** [comment] 2018-02-04 19:07
Does the same happen in a different browser? Say Edge/Internet Explorer?

**Comment by zaadstra** [comment] 2018-02-04 19:17
Do not know.  Will try.   

Here is a log fragment from the synology today,  importing 3 nzb's from watchfolder and shut down as described above.  The first time this happened I thought I accidentally clicked but next times it happened again.


2018-02-04 17:08:41,621::INFO::[SABnzbd:1148] --------------------------------
2018-02-04 17:08:41,621::INFO::[SABnzbd:1149] SABnzbd.py-2.3.1 (rev=<HASH>25eeb3ebe70b972)
2018-02-04 17:08:41,622::INFO::[SABnzbd:1150] Full executable path = /usr/local/<USERNAME>/share/SABnzbd/SABnzbd.py
2018-02-04 17:08:41,623::INFO::[SABnzbd:1160] Platform = posix
2018-02-04 17:08:41,624::INFO::[SABnzbd:1161] Python-version = 2.7.13 (default, Dec 19 2016, 02:14:38) 
[GCC 4.3.2]
2018-02-04 17:08:41,624::INFO::[SABnzbd:1162] Arguments = /usr/local/<USERNAME>/share/SABnzbd/SABnzbd.py -f /usr/local/<USERNAME>/var/config.ini --pidfile /usr/local/<USERNAME>/var/<USERNAME>.pid -d
2018-02-04 17:08:41,625::INFO::[SABnzbd:1167] Preferred encoding = UTF-8
2018-02-04 17:08:41,626::INFO::[SABnzbd:1177] SSL version = OpenSSL 1.0.2j  26 Sep 2016
2018-02-04 17:08:41,627::INFO::[SABnzbd:1225] Read INI file /usr/local/<USERNAME>/var/config.ini
2018-02-04 17:08:41,648::INFO::[postproc:87] Loading postproc queue
2018-02-04 17:08:41,652::INFO::[__init__:974] [N/A] /usr/local/<USERNAME>/var/admin/Rating.sab missing
2018-02-04 17:08:41,653::INFO::[scheduler:207] Setting schedule for midnight BPS reset
2018-02-04 17:08:41,655::INFO::[__init__:345] All processes started
2018-02-04 17:08:41,656::INFO::[SABnzbd:280] Web dir is /usr/local/<USERNAME>/share/SABnzbd/interfaces/Glitter
2018-02-04 17:08:41,657::INFO::[SABnzbd:280] Web dir is /usr/local/<USERNAME>/share/SABnzbd/interfaces/Config
2018-02-04 17:08:41,744::INFO::[config:853] Writing settings to INI file /usr/local/<USERNAME>/var/config.ini
2018-02-04 17:08:41,976::INFO::[SABnzbd:404] SABYenc module (v3.3.1)... found!
2018-02-04 17:08:41,977::INFO::[SABnzbd:421] Cryptography module (v1.6)... found!
2018-02-04 17:08:41,978::INFO::[SABnzbd:426] par2 binary... found (/usr/local/<USERNAME>/bin/par2)
2018-02-04 17:08:41,979::INFO::[SABnzbd:436] UNRAR binary... found (/usr/local/<USERNAME>/bin/unrar)
2018-02-04 17:08:41,979::INFO::[SABnzbd:444] UNRAR binary version 5.50
2018-02-04 17:08:41,981::INFO::[SABnzbd:449] unzip binary... found (/usr/local/<USERNAME>/bin/unzip)
2018-02-04 17:08:41,990::INFO::[SABnzbd:454] 7za binary... found (/usr/syno/bin/7z)
2018-02-04 17:08:41,990::INFO::[SABnzbd:460] nice binary... found (/usr/local/<USERNAME>/bin/nice)
2018-02-04 17:08:41,991::INFO::[SABnzbd:464] ionice binary... found (/usr/local/<USERNAME>/bin/ionice)
2018-02-04 17:08:42,006::INFO::[SABnzbd:1380] Starting web-interface on 0.0.0.0:9201
2018-02-04 17:08:42,007::INFO::[_cplogging:219] [04/Feb/2018:17:08:42] ENGINE Bus STARTING
2018-02-04 17:08:42,561::INFO::[_cplogging:219] [04/Feb/2018:17:08:42] ENGINE Serving on https://0.0.0.0:9201
2018-02-04 17:08:42,767::INFO::[_cplogging:219] [04/Feb/2018:17:08:42] ENGINE Serving on http://0.0.0.0:9200
2018-02-04 17:08:42,768::INFO::[_cplogging:219] [04/Feb/2018:17:08:42] ENGINE Bus STARTED
2018-02-04 17:08:42,770::INFO::[SABnzbd:1418] Starting SABnzbd.py-2.3.1
2018-02-04 17:08:42,803::INFO::[dirscanner:330] Dirscanner starting up
2018-02-04 17:08:42,823::INFO::[urlgrabber:72] URLGrabber starting up
2018-02-04 17:08:42,825::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2018-02-04 17:08:42,841::INFO::[postproc:168] Completed Download Folder /volume1/download/<USERNAME>/complete is not on FAT
2018-02-04 17:09:01,651::INFO::[interface:551] Successful login from 172.16.2.178
2018-02-04 17:09:08,938::INFO::[interface:404] Shutdown requested by interface
2018-02-04 17:09:08,940::INFO::[__init__:381] SABnzbd shutting down...
2018-02-04 17:09:08,941::INFO::[directunpacker:445] Aborting all DirectUnpackers
2018-02-04 17:09:08,942::INFO::[urlgrabber:67] URLGrabber shutting down
2018-02-04 17:09:09,866::INFO::[dirscanner:321] Dirscanner shutting down
2018-02-04 17:09:10,012::INFO::[downloader:510] Shutting down
2018-02-04 17:09:10,020::INFO::[assembler:67] Shutting down
2018-02-04 17:09:10,024::INFO::[nzbqueue:277] Saving queue
2018-02-04 17:09:10,033::INFO::[postproc:81] Saving postproc queue
2018-02-04 17:09:10,035::INFO::[__init__:445] All processes stopped
2018-02-04 17:09:10,036::INFO::[_cplogging:219] [04/Feb/2018:17:09:10] ENGINE Bus STOPPING
2018-02-04 17:09:10,042::INFO::[_cplogging:219] [04/Feb/2018:17:09:10] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9201)) shut down
2018-02-04 17:09:10,530::INFO::[dirscanner:448] Scheduled or manual watched folder scan
2018-02-04 17:09:10,535::INFO::[dirscanner:378] Trying to import /volume1/download/<USERNAME>/nzb_in/blablabla(2).nzb
2018-02-04 17:09:11,561::INFO::[misc:943] Creating directories: /volume1/download/<USERNAME>/incomplete/blablabla(2)
2018-02-04 17:09:11,584::INFO::[nzbstuff:515] File blaa - SABnzbd_nzf_Bz_L0s added to queue
2018-02-04 17:09:11,588::INFO::[nzbstuff:515] File blaaa - SABnzbd_nzf_Q8LNxL added to queue
2018-02-04 17:09:11,589::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/nzb_backup/blablabla(2).nzb.gz
2018-02-04 17:09:11,592::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/incomplete/blablabla(2)/__ADMIN__/blablabla(2).nzb.gz
2018-02-04 17:09:11,598::INFO::[nzbqueue:277] Saving queue
2018-02-04 17:09:11,604::INFO::[dirscanner:378] Trying to import /volume1/download/<USERNAME>/nzb_in/blablabla(1).nzb
2018-02-04 17:09:12,610::INFO::[misc:943] Creating directories: /volume1/download/<USERNAME>/incomplete/blablabla(1)
2018-02-04 17:09:12,693::INFO::[nzbstuff:515] blablablabla (2017).nzb - SABnzbd_nzf_7WJX6M added to queue
2018-02-04 17:09:13,188::INFO::[nzbstuff:515] blablablabla (2017).rar - SABnzbd_nzf_BjZkP1 added to queue
2018-02-04 17:09:13,504::INFO::[nzbstuff:515] blablablabla (2017).rar.par2 - SABnzbd_nzf_C5SI4b added to queue
2018-02-04 17:09:13,641::INFO::[nzbstuff:515] blablablabla (2017).rar.vol0+1.PAR2 - SABnzbd_nzf_BCcgbX added to queue
2018-02-04 17:09:13,749::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/nzb_backup/blablabla(1).nzb.gz
2018-02-04 17:09:13,941::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/incomplete/blablabla(1)/__ADMIN__/blablabla(1).nzb.gz
2018-02-04 17:09:14,045::INFO::[nzbqueue:277] Saving queue
2018-02-04 17:09:14,220::INFO::[dirscanner:378] Trying to import /volume1/download/<USERNAME>/nzb_in/blablabla.nzb
2018-02-04 17:09:15,730::INFO::[misc:943] Creating directories: /volume1/download/<USERNAME>/incomplete/blablabla
2018-02-04 17:09:15,735::INFO::[nzbstuff:515] File bla1 - SABnzbd_nzf_KJ4bjh added to queue
<snip>
2018-02-04 17:09:16,164::INFO::[nzbstuff:515] File bla12 - SABnzbd_nzf_5YXUPo added to queue
2018-02-04 17:09:16,165::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/nzb_backup/blablabla.nzb.gz
2018-02-04 17:09:16,378::INFO::[__init__:613] Backing up /volume1/download/<USERNAME>/incomplete/blablabla/__ADMIN__/blablabla.nzb.gz
2018-02-04 17:09:16,394::INFO::[nzbqueue:277] Saving queue
2018-02-04 17:09:16,662::INFO::[_cplogging:219] [04/Feb/2018:17:09:16] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9200)) shut down
2018-02-04 17:09:16,663::INFO::[_cplogging:219] [04/Feb/2018:17:09:16] ENGINE Bus STOPPED
2018-02-04 17:09:16,664::INFO::[_cplogging:219] [04/Feb/2018:17:09:16] ENGINE Bus EXITING
2018-02-04 17:09:16,665::INFO::[_cplogging:219] [04/Feb/2018:17:09:16] ENGINE Bus EXITED
2018-02-04 17:09:18,891::INFO::[SABnzbd:1554] Leaving SABnzbd

**Comment by zaadstra** [comment] 2018-02-04 19:29
Hmmm interesting,  the Internet Exploder shows, at manual shutdown, the screen I was used to:
"SABnzbd shutdown finished"  http://127.0.0.1:8080/sabnzbd/shutdown/?session=9e39b5b4a0b159f3ab8bac28591a19d6&pid=1224

Another good thing of IE,  when dragging an object above the SABnzbd webpage, and removing it out of browser focus, the page immediately returns to the web page. In firefox the big Plus symbol stays and can't be removed unless refreshing the page,

So Firefox is suspect.  I disabled ublock-origin but no change.  I need to close the browser now.

**Comment by zaadstra** [comment] 2018-02-04 19:39
Probably FOUND the little bastard.  Plugin hooverZoom (https://addons.mozilla.org/en-US/firefox/addon/hooverzoom/) which is very nice for photo sites and others showing thumbnails like wiki and work sites.
After forcing an update there was a new version with options (did not see them before), and excluded 127.0.0.1 from being handled by the plugin. Will do the same for the Synology.

Thanks for your quick reaction and ideas!

**Comment by zaadstra** [comment] 2018-02-04 19:41
The "SABnzbd shutdown finished" behaviour is back too.

**Comment by zaadstra** [comment] 2018-02-04 20:05
Somehow SABnzbd reacts on the plugin, given "[panic:209]" in the log.....

**Comment by Safihre** [comment] 2018-02-05 08:47
@zaadstra So, it's fixed with the plugin disabled?

**Comment by zaadstra** [comment] 2018-02-05 14:08
Yes.

Now I have the plugin enabled and de SABnzbd pages 'blacklisted' in its config.
It still is strange that a plugin for showing pictures is interfering with the SABnzbd interface.
There is some interacting when hovering around that causes SABnzbd to shutdown.
But this config solution is ok.

**Comment by Safihre** [comment] 2018-02-05 15:23
:+1:

**Closed by Safihre** 2018-02-05 15:23 UTC
