### ISSUE TITLE
disk error on creating file - pauses sab

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2113] opened 2022-03-09 20:52 UTC
person on discord was talking about running into issues on 3.5.1 x64 windows binary build, 
```
2022-03-09 03:22:46,527::ERROR::[assembler:192] Disk error on creating file C:\SabInter\The.Last.Kingdom.S05E05.1080p.WEB.h264-GOSSIP\the.last.kingdom.s05e05.1080p.web.h264-gossip.r06
2022-03-09 03:22:46,533::INFO::[assembler:194] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\assembler.py", line 110, in run
  File "sabnzbd\assembler.py", line 219, in assemble
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\SabInter\\The.Last.Kingdom.S05E05.1080p.WEB.h264-GOSSIP\\the.last.kingdom.s05e05.1080p.web.h264-gossip.r06'
```

had them upgrade to 3.5.2 and still seeing the assemble issue:
```
2022-03-09 13:10:50,354::INFO::[postproc:807] Verification and repair finished for Teen.Titans.Go.S07E33.720p.WEB-DL.AAC2.0.H.264
2022-03-09 13:10:50,355::INFO::[filesystem:320] Checking if any resulting filenames need to be sanitized
2022-03-09 13:10:50,359::INFO::[postproc:424] Running unpacker on Teen.Titans.Go.S07E33.720p.WEB-DL.AAC2.0.H.264
2022-03-09 13:10:50,362::INFO::[newsunpack:285] Unrar starting on \\?\C:\SabInter\Teen.Titans.Go.S07E33.720p.WEB-DL.AAC2.0.H.264
2022-03-09 13:10:50,439::INFO::[assembler:117] Decoding finished \\?\C:\SabInter\Teen.Titans.Go.S07E34.720p.WEB-DL.AAC2.0.H.264-BTN\3OaLNBQq63hC2T3wZjdRMdH8VD.part6.rar
2022-03-09 13:10:50,451::INFO::[notifier:123] Sending notification: Error - Disk error on creating file C:\SabInter\Teen.Titans.Go.S07E34.720p.WEB-DL.AAC2.0.H.264-BTN\3OaLNBQq63hC2T3wZjdRMdH8VD.part2.rar (type=error, job_cat=None)
2022-03-09 13:10:50,451::ERROR::[assembler:192] Disk error on creating file C:\SabInter\Teen.Titans.Go.S07E34.720p.WEB-DL.AAC2.0.H.264-BTN\3OaLNBQq63hC2T3wZjdRMdH8VD.part2.rar
2022-03-09 13:10:50,454::INFO::[assembler:194] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\assembler.py", line 110, in run
  File "sabnzbd\assembler.py", line 218, in assemble
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\SabInter\\Teen.Titans.Go.S07E34.720p.WEB-DL.AAC2.0.H.264-BTN\\3OaLNBQq63hC2T3wZjdRMdH8VD.part2.rar'
2022-03-09 13:10:50,457::INFO::[assembler:196] Winerror: 0xc0000034
2022-03-09 13:10:50,458::INFO::[downloader:394] Pausing
```

they noted they never had this issue until 3.5.1, it is a htpc and doesnt have antivirus software running. 

asked them to change logging to DEBUG and test again and provide logs

**Comment by Safihre** [comment] 2022-03-09 20:56
In that case it must be some Python thing... Because the code didn't change. I just released 3.5.2 to revert the buffer change, bug if that isn't it.. I have no clue.

**Comment by thezoggy** [comment] 2022-03-09 21:19
I run sab from win x64 binaries myself and I've never seen this issue on 3.5.1/3.5.2.. 

looking at
```
2022-03-09 13:10:50,457::INFO::[assembler:196] Winerror: 0xc0000034
```

the output there came from:
https://github.com/sabnzbd/sabnzbd/commit/1eb83e4eb09296b12960e695f7dedc7957dd97a9

I'm not sure if the output of that hex value + some number is getting the winerror code correctly, as the one noted above is about a boot problem which we know this is not.

Looking online I see people take the hexvalue and ` & (2**32-1)` to get the actual code...

**Comment by Safihre** [comment] 2022-03-10 06:59
@thezoggy Not sure if the hex value is correct or not, but `0xc0000034` seems to be `STATUS_OBJECT_NAME_NOT_FOUND`: https://efmsoft.com/what-is/amp/?code=0xC0000034

I am not sure what to do with this.
It doesn't seem Python depend, as 3.5.0 and 3.5.1 both use 3.10.1.
It doesn't seem long-path dependent.
It doesn't seem to matter if `buffer=0` or not (the change in 3.5.2).
What else can I try?

**Comment by Safihre** [comment] 2022-03-10 07:57
@thezoggy Can you send me the full logs if/when you have them at safihre@sabnzbd.org?

**Comment by sanderjo** [comment] 2022-03-10 09:28
> That winerror isnt too useful as I'm not certain its even the right hexvalue let alone a way to look it up.

From https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55


```
0xC0000034
STATUS_OBJECT_NAME_NOT_FOUND
The object name is not found.
```

**Comment by puzzledsab** [comment] 2022-03-10 11:33
Does the problem go away if he downgrades to 3.5.0? Did he use that version previously or an earlier one?

**Comment by thezoggy** [comment] 2022-03-11 06:58
I reached out to see if he had updated logs, so far he has not seen it re-occured to provide any updated logs. I don't believe he downgraded back to 3.5.0 to re-test that, I did share this GHI with him so he can just update here directly

**Comment by jamesmacwhite** [comment] 2022-03-11 08:42
I've been getting permission issues on sabnzbd on Windoes since the 3.5.x series. I saw permission denied errors in debug logs but I believe it to be file locking related rather than write issues. It seems to happen towards the end of a download, which seems to support the theory of the recent posts here.

Downgrading to 3.4.2 has been my solution for now.

**Comment by Safihre** [comment] 2022-03-11 08:46
I hope you guessed it already, but I need Debug logs from 3.5.1 or 3.5.2 when it happens in order to fix it.. It's only theory now.

**Comment by jamesmacwhite** [comment] 2022-03-11 08:48
Understood. The issue is that it isn't consistent on every nzb, but I did enable debug logs and capture the error. I will try and provide these to you over the weekend.

**Comment by jamesmacwhite** [comment] 2022-03-11 18:41
Here's an example on what looks like a file locking issue, Sonarr is in the mix as well, but I hadn't any problems like this until 3.5.x. Hope this helps

> 2022-03-05 03:52:15,809::INFO::[assembler:194] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\assembler.py", line 110, in run
  File "sabnzbd\assembler.py", line 219, in assemble
PermissionError: [Errno 13] Permission denied: '\\\\?\\E:\\SABnzbd\\Temp\\[redacted]\\c8kCNj0qm68v5HbCpuwA1wOoyrz8Og.part19.rar'
2022-03-05 03:52:15,810::INFO::[assembler:196] Winerror: 0xc000003a
2022-03-05 03:52:15,810::INFO::[downloader:394] Pausing
2022-03-05 03:52:15,811::INFO::[notifier:123] Sending notification: SABnzbd - Paused (type=pause_resume, job_cat=None)
2022-03-05 03:52:15,811::INFO::[downloader:414] Forcing disconnect
2022-03-05 03:52:15,812::DEBUG::[assembler:109] Decoding part of \\?\E:\SABnzbd\Temp\[redacted]\c8kCNj0qm68v5HbCpuwA1wOoyrz8Og.part20.rar
2022-03-05 03:52:15,812::DEBUG::[assembler:109] Decoding part of \\?\E:\SABnzbd\Temp\[redacted]\c8kCNj0qm68v5HbCpuwA1wOoyrz8Og.part20.rar
2022-03-05 03:52:15,813::INFO::[assembler:117] Decoding finished \\?\E:\SABnzbd\Temp\[redacted]\c8kCNj0qm68v5HbCpuwA1wOoyrz8Og.part20.rar
2022-03-05 03:52:15,813::DEBUG::[nzbstuff:463] Removing article database for SABnzbd_nzf_lmtmx5fp
2022-03-05 03:52:15,814::DEBUG::[filesystem:904] [sabnzbd\nzbstuff.py.remove_admin] Deleting file \\?\E:\SABnzbd\Temp\[redacted]\__ADMIN__\SABnzbd_nzf_lmtmx5fp
2022-03-05 03:52:15,884::DEBUG::[filesystem:937] Removing dir recursively \\?\E:\SABnzbd\Sonarr\_UNPACK_[redacted]
2022-03-05 03:52:15,885::INFO::[filesystem:941] Cannot remove folder \\?\E:\SABnzbd\Sonarr\_UNPACK_[redacted]
Traceback (most recent call last):
  File "sabnzbd\filesystem.py", line 939, in remove_all
  File "shutil.py", line 739, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 615, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\E:\\SABnzbd\\Sonarr\\_UNPACK_[redacted]\\aR0HeYhMEMZYWbDb5yH3Pw5C9cUt4.mkv'
2022-03-05 03:52:16,396::DEBUG::[directunpacker:334] DirectUnpack Unrar output

**Comment by Safihre** [comment] 2022-03-11 19:14
Can you try this updated build?
https://github.com/sabnzbd/sabnzbd/actions/runs/1969584588

**Comment by thezoggy** [comment] 2022-03-11 22:46
> Can you try this updated build? https://github.com/sabnzbd/sabnzbd/actions/runs/1969584588

I passed this build along to the person on discord that had the issue to try out. I went ahead and installed it myself just to see if issues come about with it.

**Comment by Safihre** [comment] 2022-03-12 06:16
We have a Discord?

**Comment by thezoggy** [comment] 2022-03-12 18:35
Ha no, it's from sonarr's.

**Comment by Slikkster** [comment] 2022-03-15 19:54
> Can you try this updated build? https://github.com/sabnzbd/sabnzbd/actions/runs/1969584588

So far this test build has fixed this issue for me, though it has only been a couple of days so it might be a little early to tell. I was getting the disk error on creating file pretty frequently before though.

**Comment by thezoggy** [comment] 2022-03-15 23:00
> > Can you try this updated build? https://github.com/sabnzbd/sabnzbd/actions/runs/1969584588
> 
> So far this build has fixed this issue for me, though it has only been a couple of days so it might be a little early to tell. I was getting the disk error on creating file pretty frequently before though.

you can also now just upgrade to latest: 3.5.3rc1 - https://github.com/sabnzbd/sabnzbd/releases/tag/3.5.3RC1

**Comment by Slikkster** [comment] 2022-03-15 23:28
> > > Can you try this updated build? https://github.com/sabnzbd/sabnzbd/actions/runs/1969584588
> > 
> > 
> > So far this build has fixed this issue for me, though it has only been a couple of days so it might be a little early to tell. I was getting the disk error on creating file pretty frequently before though.
> 
> you can also now just upgrade to latest: 3.5.3rc1 - https://github.com/sabnzbd/sabnzbd/releases/tag/3.5.3RC1

Ahh, thank you, I did not think to check for a newer release first (came here from Google).

**Comment by Safihre** [comment] 2022-03-17 20:25
3.5.3 released with the fix.

**Closed by Safihre** 2022-03-17 20:25 UTC
Labels: Bug

**Comment by jamesmacwhite** [comment] 2022-03-19 08:07
3.5.3 seems to be working great now, thank you!

**Comment by drmanhatin** [comment] 2022-12-13 00:01
Running into this error on 3.7, also on ~3.4...

2022-12-13 00:57:05,350::INFO::[notifier:123] Sending notification: Error - Disk error on creating file C:\tempdw\asdfasdfads-\5y02Hh2uyCzkZE2ua8Ox.part002.rar (type=error, job_cat=None)
2022-12-13 00:57:05,350::ERROR::[assembler:113] Disk error on creating file C:\tempdw\asdfasdfads-\5y02Hh2uyCzkZE2ua8Ox.part002.rar
2022-12-13 00:57:05,351::INFO::[assembler:116] Winerror: None - 0xc0000034
2022-12-13 00:57:05,351::INFO::[assembler:121] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\assembler.py", line 86, in run
  File "sabnzbd\assembler.py", line 178, in assemble
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\tempdw\\asdfasdfads-\\5y02Hh2uyCzkZE2ua8Ox.part002.rar'
2022-12-13 00:57:05,352::INFO::[downloader:393] Pausing
2022-12-13 00:57:05,352::INFO::[notifier:123] Sending notification: SABnzbd - Paused (type=pause_resume, job_cat=None)
2022-12-13 00:57:05,352::INFO::[downloader:413] Forcing disconnect

**Comment by drmanhatin** [comment] 2022-12-13 00:22
Problem does not occur when I throttle net speed to 10MB/s instead of the ~95-100MB/s I get usually

Smells like a race condition? After pausing, part002.rar in the example above actually exists and has data written to it. 

My C drive is an NVME, fwiw...

**Comment by Safihre** [comment] 2022-12-13 02:55
Due to the lack of other users reporting problems for many months (this issue is old) I don't think it's a race condition, just Windows Defender or another virus scanner that's scanning the file after we write part of it and then try to open it again to write more.

**Comment by drmanhatin** [comment] 2022-12-15 14:41
I agree its probably defender as I see the file pop up in event viewer. Tried disabling defender, adding exclusion lists... But Windows 11 has made it pretty much impossible to do this.

I have switched to NZBGet for now and it works.

Maybe a retry mechanism could solve this problem.
