### ISSUE TITLE
sabnzbd does not proper free allocated memory

### ISSUE THREAD

**Issue by Hubfront** [sabnzbd/sabnzbd#177] opened 2014-08-09 08:55 UTC
The python process seems to keep allocated memory, even after all jobs are fully downloaded and processed and sabnzbd is idle. This behaviour is problematic on Nas machines with rather small amounts of Ram. I use a DS214play with 1GB Ram and a DS214 with 512 MB Ram.

Sabnzbd should instantly free allocated memory when it's not needed anymore.

**Comment by shypike** [comment] 2016-04-20 09:27
Duplicate of  #439

**Closed by shypike** 2016-04-20 09:27 UTC
Labels: Cannot reproduce
