### ISSUE TITLE
sab 3.0.0Alpha1 -- "No module named 'cheroot.ssl'"

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1409] opened 2020-04-28 18:16 UTC
Stopped sab 2.3.9. Installed windows binary 3.0.0Alpha1 to upgrade my existing 2.3.9. Started up sab and seeing it fail:

```
2020-04-28 13:13:56,591::INFO::[SABnzbd:1090] --------------------------------
2020-04-28 13:13:56,591::INFO::[SABnzbd:1091] SABnzbd.exe-3.0.0Alpha1 (rev=c33cabdff663d5a9c1997b5a262e100025d11e0a)
2020-04-28 13:13:56,591::INFO::[SABnzbd:1092] Full executable path = C:\Program Files\SABnzbd\SABnzbd.exe
2020-04-28 13:13:56,591::INFO::[SABnzbd:1098] Platform = Windows-7-6.1.7601-SP1 (win64)
2020-04-28 13:13:56,591::INFO::[SABnzbd:1103] Python-version = 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
2020-04-28 13:13:56,591::INFO::[SABnzbd:1104] Arguments = "C:\Program Files\SABnzbd\SABnzbd.exe"
2020-04-28 13:13:56,591::INFO::[SABnzbd:1108] Not inside a docker container
2020-04-28 13:13:56,591::INFO::[SABnzbd:1111] Preferred encoding = cp1252
2020-04-28 13:13:56,591::INFO::[SABnzbd:1118] SSL version = OpenSSL 1.1.1d  10 Sep 2019
2020-04-28 13:13:56,591::INFO::[SABnzbd:1125] Loaded additional certificates from C:\Program Files\SABnzbd\cacert.pem
2020-04-28 13:13:56,591::DEBUG::[SABnzbd:1131] Available certificates: {'x509': 64, 'crl': 0, 'x509_ca': 58}
2020-04-28 13:13:56,591::DEBUG::[SABnzbd:1138] My local IPv4 address = 192.168.0.2
2020-04-28 13:13:56,872::DEBUG::[SABnzbd:1144] My public IPv4 address = 72.191.12.185
2020-04-28 13:13:56,872::DEBUG::[SABnzbd:1152] Could not determine my IPv6 address
2020-04-28 13:13:57,309::DEBUG::[SABnzbd:1158] CPU Pystone available performance = 204961
2020-04-28 13:13:57,309::DEBUG::[SABnzbd:1163] CPU model = Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
2020-04-28 13:13:57,309::INFO::[SABnzbd:1165] Using INI file \\?\C:\Users\zoggy\AppData\Local\sabnzbd\sabnzbd.ini
2020-04-28 13:13:57,309::DEBUG::[__init__:916] [sabnzbd\__init__.py.load_admin] Loading data for rss_data.sab from \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin\rss_data.sab
2020-04-28 13:13:57,309::DEBUG::[__init__:916] [sabnzbd\__init__.py.load_admin] Loading data for totals10.sab from \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin\totals10.sab
2020-04-28 13:13:57,309::DEBUG::[downloader:164] Initializing downloader/decoder
2020-04-28 13:13:57,309::INFO::[postproc:129] Loading postproc queue
2020-04-28 13:13:57,309::DEBUG::[__init__:916] [sabnzbd\__init__.py.load_admin] Loading data for postproc2.sab from \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin\postproc2.sab
2020-04-28 13:13:57,309::DEBUG::[__init__:916] [sabnzbd\__init__.py.load_admin] Loading data for queue10.sab from \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin\queue10.sab
2020-04-28 13:13:57,309::DEBUG::[__init__:916] [sabnzbd\__init__.py.load_admin] Loading data for watched_data2.sab from \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin\watched_data2.sab
2020-04-28 13:13:57,309::DEBUG::[scheduler:170] Skipping speedlimit(['0K']) on days [1, 2, 3, 4, 5, 6, 7] at 17:25
2020-04-28 13:13:57,309::DEBUG::[scheduler:170] Skipping speedlimit(['9000K']) on days [1, 2, 3, 4, 5, 6, 7] at 07:00
2020-04-28 13:13:57,309::DEBUG::[scheduler:180] Scheduling RSS interval task every 1440 min (delay=52)
2020-04-28 13:13:57,309::DEBUG::[scheduler:192] Scheduling VersionCheck on day 1 at 14:56
2020-04-28 13:13:57,309::INFO::[scheduler:207] Setting schedule for midnight BPS reset
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (252, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (1067, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (1692, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (2507, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (3132, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (3947, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (4572, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (5387, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (6012, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (6827, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (7452, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (8267, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (8892, 'speedlimit', '0K', '0 25 17 * speedlimit 0K', '0')
2020-04-28 13:13:57,309::DEBUG::[scheduler:322] Schedule check result = (9707, 'speedlimit', '9000K', '0 0 7 1234567 speedlimit 9000K', '0')
2020-04-28 13:13:57,309::DEBUG::[__init__:580] PAUSED_ALL inactive
2020-04-28 13:13:57,309::INFO::[__init__:340] All processes started
2020-04-28 13:13:57,309::INFO::[SABnzbd:276] Template location for Glitter is \\?\C:\Program Files\SABnzbd\interfaces\Glitter
2020-04-28 13:13:57,309::INFO::[SABnzbd:276] Template location for Config is \\?\C:\Program Files\SABnzbd\interfaces\Config
2020-04-28 13:13:57,309::INFO::[config:852] Writing settings to INI file \\?\C:\Users\zoggy\AppData\Local\sabnzbd\sabnzbd.ini
2020-04-28 13:13:57,933::INFO::[SABnzbd:377] SABYenc module (v4.0.1)... found!
2020-04-28 13:13:57,933::INFO::[SABnzbd:389] Cryptography module (v2.9.2)... found!
2020-04-28 13:13:57,933::INFO::[SABnzbd:392] par2 binary... found (C:\Program Files\SABnzbd\win\par2\par2.exe)
2020-04-28 13:13:57,933::INFO::[SABnzbd:399] MultiPar binary... found (C:\Program Files\SABnzbd\win\par2\multipar\par2j64.exe)
2020-04-28 13:13:57,933::INFO::[SABnzbd:404] UNRAR binary... found (C:\Program Files\SABnzbd\win\unrar\x64\UnRAR.exe)
2020-04-28 13:13:57,933::INFO::[SABnzbd:421] unzip binary... NOT found!
2020-04-28 13:13:57,933::INFO::[SABnzbd:424] 7za binary... found (C:\Program Files\SABnzbd\win\7zip\7za.exe)
2020-04-28 13:13:57,933::INFO::[SABnzbd:1223] HTTPS keys are OK
2020-04-28 13:13:57,933::INFO::[SABnzbd:1326] Starting web-interface on 192.168.0.2:8082
2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Bus STARTING
2020-04-28 13:13:57,933::ERROR::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x0000000003B84460>>
Traceback (most recent call last):
  File "lib\site-packages\cheroot\server.py", line 2106, in get_ssl_adapter_class
KeyError: 'cheroot.ssl.builtin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\cherrypy\process\wspbus.py", line 230, in publish
  File "lib\site-packages\cherrypy\_cpserver.py", line 179, in start
  File "lib\site-packages\cherrypy\_cpserver.py", line 170, in httpserver_from_self
  File "lib\site-packages\cherrypy\_cpwsgi_server.py", line 98, in __init__
  File "lib\site-packages\cheroot\server.py", line 2111, in get_ssl_adapter_class
ModuleNotFoundError: No module named 'cheroot.ssl'

2020-04-28 13:13:57,933::ERROR::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "lib\site-packages\cherrypy\process\wspbus.py", line 268, in start
  File "lib\site-packages\cherrypy\process\wspbus.py", line 248, in publish
cherrypy.process.wspbus.ChannelFailures: ModuleNotFoundError("No module named 'cheroot.ssl'")

2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Bus STOPPING
2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE HTTP Server None already shut down
2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Bus STOPPED
2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Bus EXITING
2020-04-28 13:13:57,933::INFO::[_cplogging:213] [28/Apr/2020:13:13:57] ENGINE Bus EXITED
```

**Comment by thezoggy** [comment] 2020-04-28 18:27
windows build script not putting stuff in `lib` folder anymore?

**Comment by thezoggy** [comment] 2020-04-28 18:53
and to note per irc, macosx build is also busted if you try to use https due to not able to import cheroot.ssl

**Comment by sanderjo** [comment] 2020-04-28 18:53
What if you temporarily turn off HTTPS? I guess it's `enable_https = 0` in sabnzbd.ini

**Comment by thezoggy** [comment] 2020-04-28 18:54
if you dont use the missing libs then it 'works'

**Comment by Cpuroast** [comment] 2020-04-28 18:56
> What if you temporarily turn off HTTPS? I guess it's `enable_https = 0` in sabnzbd.ini

It works fine without HTTPS enabled, that's why I didn't catch it earlier.

**Comment by sanderjo** [comment] 2020-04-28 18:57
> > What if you temporarily turn off HTTPS? I guess it's `enable_https = 0` in sabnzbd.ini
> 
> It works fine without HTTPS enabled, that's why I didn't catch it earlier.

Good. I would advise to keep using Alpha1 to see how the other functionality behaves ... because ... no testers no results.

**Comment by Cpuroast** [comment] 2020-04-28 18:59
> > > What if you temporarily turn off HTTPS? I guess it's `enable_https = 0` in sabnzbd.ini
> > 
> > 
> > It works fine without HTTPS enabled, that's why I didn't catch it earlier.
> 
> Good. I would advise to keep using Alpha1 to see how the other functionality behaves ... because ... no testers no results.

I've been using the various git test builds Safihre has been pushing out, so I know the other core functionality has been good.

**Comment by thezoggy** [comment] 2020-04-28 19:00
> 
> 
> > > What if you temporarily turn off HTTPS? I guess it's `enable_https = 0` in sabnzbd.ini
> > 
> > 
> > It works fine without HTTPS enabled, that's why I didn't catch it earlier.
> 
> Good. I would advise to keep using Alpha1 to see how the other functionality behaves ... because ... no testers no results.

yes, but the fact its showing up as a warning to 2.3.9 users they are going to mindlessly click on it and upgrade to 3.x and break their install from even starting is not good.

**Comment by sanderjo** [comment] 2020-04-28 19:03
> ~ didnt realize i had my win install set to show test releases, so that makes sense. was thinking it was not flag as such.

Oh? Current SAB 2.3 (test?) users get a message there is a new (test) release?

**Comment by thezoggy** [comment] 2020-04-28 19:11
> 
> 
> > ~ didnt realize i had my win install set to show test releases, so that makes sense. was thinking it was not flag as such.
> 
> Oh? Current SAB 2.3 (test?) users get a message there is a new (test) release?

yes, which is how i knew there was an upgrade and was like.. oh i've been meaning to test that :)
i made a backup so no big deal for me to revert

**Comment by jeffgeorge** [comment] 2020-04-28 19:25
@Safihre These SSL issues may be worth pulling the build over.

**Comment by Safihre** [comment] 2020-04-28 20:02
Fixed by https://github.com/sabnzbd/sabbuild/commit/eda1c980c70074ded4993d1178f42bc4ff2289ab

Pushed new Windows builds already. Waiting for Travis to build macOS, but this can take a _while_ this time of day.

**Closed by Safihre** 2020-04-28 20:02 UTC

**Comment by Safihre** [comment] 2020-04-28 21:36
macOS release also updated.

**Comment by Cpuroast** [comment] 2020-04-28 21:37
Yup, tested confirmed fixed, I was keeping an eye on the travis build process.
Let me quickly check on older versions of macOS if it still runs.

**Comment by Cpuroast** [comment] 2020-04-28 22:02
Yup, still runs without any issues on 10.9 through 10.15, enabled HTTPS as well as HTTP in all the VMs, so I can catch this if ever it happens again.

**Comment by thezoggy** [comment] 2020-04-28 22:29
can confirm that new build does start just fine after 2.3.9 upgrade. 

@Safihre whats the 39 (767 KB) of `api-ms-win-crt-*.dll` used for?

**Comment by Safihre** [comment] 2020-04-29 06:15
No it is not the same, because Python 3.5 now uses VS2015 and nog VS2010. For VS2015 only Windows 10 users have it installed by default. See: https://pyinstaller.readthedocs.io/en/latest/usage.html#windows
I want to build a check in the installer to check if it is installed and download it otherwise, but this will take a lot more work.
Remember that this is an Alpha-release.
