### ISSUE TITLE
Crash when public IPv6 address is unusable

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#506] opened 2016-03-11 08:19 UTC
See: https://forums.sabnzbd.org/viewtopic.php?f=2&t=20360
Two bugs:
* Python crashes when a traceback contains %1, %2 etc, in its error message
* ipv6_hosting option doesn't influence the use of a public IPv6 address

Why IPv6 doesn't work in this specific case, is another matter.

**Comment by sanderjo** [comment] 2016-03-11 15:37
I think the root cause is different than "when public IPv6 address is unusable"; the OP's IPv6 is working correctly, but he has a IPv4 VPN running at the same time.

**Comment by Safihre** [comment] 2016-03-11 16:01
So, not something that will affect many people (and delay 1.0.0 final)? Or we cannot help it at all?

**Comment by shypike** [comment] 2016-03-11 16:03
At the least I will remove the CherryPy crash, otherwise the user knows even less about what's going on.

**Comment by sanderjo** [comment] 2016-03-13 17:56
I can NOT reproduce it. See https://forums.sabnzbd.org/viewtopic.php?f=2&t=20360&p=104883#p104883

So probably even more obscure and niche-of-a-niche. Not a reason for delay of 1.0.0.

**Comment by shypike** [comment] 2016-03-13 19:32
I can reproduce it sometimes on my iMac. The reason I wanted to fix it, is the crash when % is part of the IPv6 address. Because that obscures the true cause.
The Python crash should be fixed now.

**Comment by sanderjo** [comment] 2016-03-13 20:54
**Short**
The "%" should only show up in case of of link-local address, starting with FE80:. Not with public IPv6 addresses.
So if such an address shows up ... I suggest SABnzbd should ignore that address

**You can ignore the rest of this message ... ;-)**

**Long**

I think those FE80:: addresses are not very useful for SABnzbd. Or, more precise: they are only relevant on the specific LAN. On a LAN you can easier use IPv4 addresses. Oh, wait, one advantage of FE80 addresses on a (W)LAN: the FE80 address is based on the MAC address, and thus the FE80 address is fixed:
```
wlan0     Link encap:Ethernet  HWaddr 18:f4:6a:9c:ce:d4  
          inet6 addr: fe80::1af4:6aff:fe9c:ced4/64 Scope:Link
```
So no matter what, once you know that FE80 address, you can keep using it. :-)

But let's see if it works at all, and note the ```%wlan0``` in the address:

```
$ lynx --dump 'http://[fe80::1af4:6aff:fe9c:ced4%wlan0]:8080/sabnzbd/' | head -30
   (BUTTON)
   (BUTTON) (BUTTON)
     * [1]Pause for 5 minutes
     * [2]Pause for 15 minutes
     * [3]Pause for 30 minutes
     * [4]Pause for 1 hour
     * [5]Pause for 3 hours
     * [6]Pause for 6 hours
     *
     * [7]Custom

   0:00
     *
     * (BUTTON) 0 KB/s (BUTTON)
       [8]You must set a maximum bandwidth before you can set a bandwidth
       limit
```
So, yes lynx does understand it. Chrome and wget and curl don't understand it. So: not so useful.

From https://en.wikipedia.org/wiki/IPv6_address#Link-local_addresses_and_zone_indices
Because all link-local addresses in a host have a common prefix, normal routing procedures cannot be used to choose the outgoing interface when sending packets to a link-local destination.
When an address is written textually, the zone index is appended to the address, separated by a percent sign (%)


- the Microsoft Windows IPv6 stack uses numeric zone indices, e.g., fe80::3%1. The index is determined by the interface number;
- most Unix-like systems (e.g., BSD, Linux, OS X) use the interface name as a zone index: fe80::3%eth0.
- alternatively, on BSD based operating systems (including OS X), a numeric zone index can be used in the second 16-bit word, e.g.: fe80:1::3

**Comment by Safihre** [comment] 2016-10-21 14:15
Fixed now that ```ipv6_hosting``` option is not ignored anymore via #711 / 8e97097dfdcc81c0945fad869b8b7d04ee1e74a5.

**Closed by Safihre** 2016-10-21 14:15 UTC
Labels: Confirmed, Fixed
