### ISSUE TITLE
OS X: Bundled unrar has wrong permissions set. 

### ISSUE THREAD

**Issue by middling** [sabnzbd/sabnzbd#555] opened 2016-04-28 13:41 UTC
On the Mac OS X version the bundled copy of unrar (SABnzbd.app/Contents/Resources/osx/unrar/unrar) has its permissions set to 700 instead of 755, resulting in SABnzbd being unable to use unrar when it's run as a different user from the one that installed it.

The bug is present in versions 1.0 and 1.0.1.

**Comment by shypike** [comment] 2016-04-28 13:48
Oops. Will be fixed.

**Comment by shypike** [comment] 2016-04-28 20:55
Are you quite sure? Isn't this caused by how your umask is set?
When I look at the DMG image, the permissions of the tools are correct:
```
ls -l /Volumes/SABnzbd-1.0.1/SABnzbd.app/Contents/Resources/osx/
total 0
drwxr-xr-x  4 user  staff  136 26 apr 20:48 7zip
drwxr-xr-x  6 user  staff  204 10 feb  2015 par2
drwxr-xr-x  4 user  staff  136 26 apr 20:48 unrar
```

**Closed** 2016-05-12 13:51 UTC
Labels: 3 - Fixed, Bug
