### ISSUE TITLE
Issue with Deobfuscate final filenames and no folder for job

### ISSUE THREAD

**Issue by Jabroni** [sabnzbd/sabnzbd#1598] opened 2020-09-04 19:20 UTC
I just started testing 3.1.0b1, and I thing i found a missing feature/bug.

If i download an obsurcated nzb and it outputs with a folder for the job it works ok (creates /complete/Job.Name/ and filenames within that job name are renamed correctly), however if on the Default category I add a * (to prevent having a folder for each job name), the file that ends in the /complete/ folder isnt renamed and still has the obsucated .mkv name

**Comment by sanderjo** [comment] 2020-09-04 19:34
in your sabnzbd.log, is there any lines with "deobfuscate" ?
Best to set SAB's Logging to +Debug, and redownload



2020-08-23 22:32:51,534::DEBUG::[postproc:515] Running deobfuscate on final result for dir /home/sander/Downloads/complete/test_download_100MB.1 and job name test_download_100MB
2020-08-23 22:32:51,534::DEBUG::[deobfuscate_filenames:196] par2 files matches is []
2020-08-23 22:32:51,534::DEBUG::[deobfuscate_filenames:201] No par2 files found to process.
2020-08-23 22:32:51,535::DEBUG::[deobfuscate_filenames:215] Trying to see if there are qualifying files to be renamed
2020-08-23 22:32:51,535::DEBUG::[deobfuscate_filenames:218] Inspecting 100MB.bin
2020-08-23 22:32:51,535::DEBUG::[deobfuscate_filenames:175] Obfuscated: entropy < 3.5
2020-08-23 22:32:51,535::INFO::[deobfuscate_filenames:234] Renaming /home/sander/Downloads/complete/test_download_100MB.1/100MB.bin to /home/sander/Downloads/complete/test_download_100MB.1/test_download_100MB.bin
2020-08-23 22:32:51,536::DEBUG::[deobfuscate_filenames:240] Renaming succeeded on run 1

**Comment by Jabroni** [comment] 2020-09-04 20:38
Just did both tests with and without * on the category.

If I dont have the * on the default category, I see the deobfuscate_filename on the log and it renames correctly within the folder, If I put the * on the default category, seems that the deobfuscate module isnt invoked (no lines regarding it)

**Comment by Safihre** [comment] 2020-09-04 20:44
Yes, this is by design. I should update the wiki.
Because we scan all the files in the folder, if you omit folders for each job, we might rename stuff we shouldn't. 
So if you use *, you cant use this feature.

**Comment by Cpuroast** [comment] 2020-09-05 03:10
As an alternative to the "Deobfuscate final filenames", use Series or Movie Sorting with the "Job Name as Filename" preset.
It works well with Categories set to *, to omit job folders.

You'll see during extraction it creates a temp job job folder in the target location, renames the resulting obfuscated file inside this temp job folder to the job name, then simply moves the files out of the temp folder to the path below it and nukes the now empty temp job folder.

**Comment by Safihre** [comment] 2020-09-05 09:05
Maybe that should in general be the way we handle the no-folder setting.. There are more special cases in the code now when no-folder is enabled.

**Comment by Safihre** [comment] 2020-09-11 14:40
I labeled this as feature request, since we will have to make some significant changes to support it.

**Comment by Safihre** [comment] 2020-09-19 08:38
Closed in #1612

**Closed by Safihre** 2020-09-19 08:38 UTC
Labels: Feature request
