### ISSUE TITLE
sab 0.8.x -- Invalid par2 files, cannot verify or repair

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#328] opened 2015-09-13 06:39 UTC
win7 w/sab dev latest
randomly tonight I've started to see nzb fail with `Invalid par2 files, cannot verify or repair`.
they work just fine on other clients. upon looking into the sab logs and the incomplete folder.. I see that sab is creating an invalid folder (windows doesnt allow for trailing period). Because of the bad folder, then we see par fails because it cant find the files...

```
2015-09-12 23:49:59,694::INFO::[__init__:623] Adding Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws Sleep.Spells.1080p.WEB-DL.AAC2.0.H.264-iT00NZ.nzb
2015-09-12 23:49:59,698::INFO::[nzbstuff:654] Replacing spaces with underscores in Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws Sleep.Spells.1080p.WEB-DL.AAC2.0.H.264-iT00NZ
2015-09-12 23:49:59,703::INFO::[misc:782] Creating directories: \\?\C:\Users\xxxxx\downloads\incomplete\Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws Sleep.Spells.1080p.WEB-DL.AAC2.0.H.
```

so now  I have a few folders in my incomplete folder that I cant even delete via explorer/cmd.
found this page which talks about the post result issue:
http://stackoverflow.com/questions/21072767/cant-delete-a-folder-on-windows-7-with-a-trailing-space

**Comment by thezoggy** [comment] 2015-09-13 06:44
so while sab couldnt remove the dir per logs even after clicking on the delete from history.. 

I could manually remove the dir via:
```
C:\Users\xxxxx\Downloads\incomplete>rd /S "\\?\C:\Users\xxxxx\Downloads\incomplete\Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws Sleep.Spells.1080p.WEB-DL.AAC2.0.H."
\\?\C:\Users\xxxxx\Downloads\incomplete\Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws Sleep.Spells.1080p.WEB-DL.AAC2.0.H., Are you sure (Y/N)? y
```

**Comment by shypike** [comment] 2015-09-13 19:11
Do you have the size limit still on in Config->Special?
It looks like the folder is clipped to size and yes of course it shouldn't end with a period.

**Comment by thezoggy** [comment] 2015-09-13 22:02
`size_limit` is set to 0. and plenty of longer named items worked fine.

**Comment by shypike** [comment] 2015-09-13 22:13
Ok, just a regular bug then. I'll look into it.

**Comment by thezoggy** [comment] 2015-09-13 22:32
shortpath.py -- https://gist.githubusercontent.com/thezoggy/5616465cef1ee866d427/raw/6ef0cab8a888e3e5b18111a305632c3d9f905093/shortpath.py

use -f/--force to apply the long path logic to kick in
`python shortpath.py folder [-f]`

example:
```
C:\>python shortpath.py C:\Users\zoggy\Downloads\complete\TV\Star.vs.The.Forces.of.Evil.S01E19.St.Olgas.Reform.School.for.Wayward.Princesses.1080p.WEB-DL.AAC2.0.H.264-iT00NZ
before:  C:\Users\zoggy\Downloads\complete\TV\Star.vs.The.Forces.of.Evil.S01E19.St.Olgas.Reform.School.for.Wayward.Princesses.1080p.WEB-DL.AAC2.0.H.264-iT00NZ
 after:  C:\Users\zoggy\Downloads\complete\TV\Star.vs.The.Forces.of.Evil.S01E19.St.Olgas.Reform.School.for.Wayward.Princesses.1080p.WEB-DL.AAC2.0.H.264-iT00NZ

C:\>python shortpath.py C:\Users\zoggy\Downloads\complete\TV\Star.vs.The.Forces.of.Evil.S01E19.St.Olgas.Reform.School.for.Wayward.Princesses.1080p.WEB-DL.AAC2.0.H.264-iT00NZ -f
before:  C:\Users\zoggy\Downloads\complete\TV\Star.vs.The.Forces.of.Evil.S01E19.St.Olgas.Reform.School.for.Wayward.Princesses.1080p.WEB-DL.AAC2.0.H.264-iT00NZ
 after:  C:\Users\zoggy\DOWNLO~1\complete\TV\STA89F~1.264
```

**Comment by shypike** [comment] 2015-09-14 07:45
The trailing "." has to be removed. Windows has no problem creating a folder with a trailing period, in the sense that it ignores the period and creates a folder without one. The problem is that SABnzbd keeps using the name with the period along and when it tests for existence, then all of a sudden the folder no longer seems to exist. That happens in "short_path()", causing the last part not to be shortened, leading to par2 not finding the files. Will be fixed tonight.

**Comment by shypike** [comment] 2015-09-14 08:03
Yikes, there's a very old function hiding in misc.py, it's called trim_win_path() and it bluntly sets an upper limit of 125 and (of course) doesn't remove the trailing period.
It's obsolete now that the path is trimmed in a better way.
Can you remove line 655 from nzbstuff.py and test again?
```
665            wdir = trim_win_path(wdir)
```

**Comment by shypike** [comment] 2015-09-14 09:41
This function was actually implemented later on in the "long paths for Windows" saga.
It needs some more investigation.
The simplest fix is to remove the trailing period, which I have done now: 687aab7f90bfe6c5369f926e242bb93b1791794b

**Comment by shypike** [comment] 2015-09-14 19:57
@thezoggy Solved now?

**Comment by thezoggy** [comment] 2015-09-14 20:12
testing again.. it unpacked+extracted just fine. 

i see it created this in incomplete:
`Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws_Sleep.Spells.1080p.WEB-DL.AAC2.0.H`

when it completed, it did name it the full name:
`Star.vs.The.Forces.of.Evil.S01E13E14.Lobster.Claws_Sleep.Spells.1080p.WEB-DL.AAC2.0.H.264-iT00NZ`

**Comment by shypike** [comment] 2015-09-14 20:19
The shortening is on purpose to avoid the limitations of par2.

**Closed** 2015-10-27 05:37 UTC
Labels: 1 - Confirmed, 3 - Fixed
