### ISSUE TITLE
Python shebang

### ISSUE THREAD

**Issue by tingvold** [sabnzbd/sabnzbd#1663] opened 2020-10-29 14:53 UTC
Hi,

Any particular reason as to why we use `/usr/bin/python3` as the shebang, and not `/usr/bin/env python3`? Makes it harder to universally apply different Python versions (i.e. via pyenv and similar).

I'm aware that `-OO` is not passed using the latter, but I'd assume there was better ways to achieve that? And even if not, do we actually need it? Does it actually impact performance in a noticeable way?

I know for large systems, or where this were to be run on many, many servers, controlled by the same entity, it probably makes sense. But for "home use", where flexibility maybe should be the key focus, I don't really see the big advantage?

I must admit that I rarely see hardcoded Python shebangs, as most of them seems to use the `/usr/bin/env` approach (even for systems that still use Python2), at least for systems like sabnzbd.

**Comment by sanderjo** [comment] 2020-10-29 15:43
Dupe of https://github.com/sabnzbd/sabnzbd/issues/1394 ?

**Comment by tingvold** [comment] 2020-10-29 15:49
If anything, it's a dupe of #1157 and #400, but neither of those address the rationale behind the usage of `-OO`, which seems to be the "main" argument for using the current shebang.

**Comment by Safihre** [comment] 2020-10-29 15:53
The `-OO`, specifically `-O` makes a big difference for a CPU-heavy application such as SABnzbd.
I tested this when it was still Python 2, but doubt it has changed much in Python 3. 
Back then it was around a 10% improvement.

**Comment by tingvold** [comment] 2020-10-29 16:00
Seems it can be set via `PYTHONOPTIMIZE` environmental variable. Maybe that is a better way to achieve this? (i.e. set `PYTHONOPTIMIZE` in the init script or whatever).

**Comment by Safihre** [comment] 2020-10-29 16:30
There is no universal init-script, so that's not really an option.
Whatever we choose for this shebang, someone else will open an issue saying it should be the other way.. I am kind of tired of it.

Why not just simply run SABnzbd by running `python3 ./SABnzbd.py` instead of just `./SABnzbd.py`. Problem also solved..

**Closed** 2020-11-08 17:10 UTC
