### ISSUE TITLE
0.8.x -- glitter - tweaks

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#315] opened 2015-09-06 04:12 UTC
had two sab sessions going.. i see the warning section in smpl in 0.7.x which told me it was too many connections to the usp.. i couldnt find this info in glitter.. 

in glitter, the `Status and interface options` modal is getting a bit cluttered -- especially if you have multiple servers (i have two primary, two backup, and one free one.. so 5 total). perhaps this page could be revamped to segment some of the data better / move stuff to a different modal.

**Comment by Safihre** [comment] 2015-09-06 07:05
Need some more info: Can you check if smpl in the 0.8 session does display the error? I never had a situation where errors were not displayed, so it could also just be that the 0.8 session hadn't noticed the error yet. 
You mean the main errors right, not the server specific errors in the status window?  

Yes,  the status window could use a revamp, but I don't know how. Currently it works fine for regular users with 1 to 2 servers, but not for power users. 
It could be out into tabs.

**Comment by thezoggy** [comment] 2015-09-06 08:38
so loaded up same sab instance with both skins,  `/m` to get to the other skin..
so few things i notice that i miss from using smpl (which is normally my default skin)..

* not seeing age/size for the queue item without having to drill down to see it
  > maybe we should show tooltip with that info? maybe on the progress field since the context of % makes sense to the size..

* on the history, could move the info modal from the down caret to the status image in front, (click on the check mark).. since its not doing much anyways and also gets people away from accidentally clicking on the delete...

![glitter1](http://zoggy.net/glitter1.png)

**Comment by Safihre** [comment] 2015-09-06 09:03
Will add age as tooltip. However, you can see the size easily already, it's always the last the last in the progress-bar.

I personally like the size first and then the description (see Plush), like in Left and This Month. I tried it the other way around and did not like the result so much:
![image](https://cloud.githubusercontent.com/assets/5703454/9703521/e0201c1c-5486-11e5-856d-ebc569532827.png)

**Comment by thezoggy** [comment] 2015-09-06 09:06
yes, you can see age in the progress bar when its downloading.. not during pp/afterwards. at least after pp you can drill down into the report... dunno if you want to talk about this on irc? vs playing tag in github.

**Comment by Safihre** [comment] 2015-09-06 09:11
IRC sounds good

**Comment by thezoggy** [comment] 2015-09-07 12:27
so if you have 6 items in your queue and it set to show 5. so 5 on page 1 and 1 on page 2. its pretty hard to move the 6th item to anywhere.. have to toggle how many to show on the page.. and upon doing so this breaks pagination.. as i changed it from 5->10 but still see just the one entry and clicking on page 1 or 2 does nothing. have to force reload page to 'fix'

**Comment by thezoggy** [comment] 2015-09-07 13:04
clicked on pause at the top next to the sab logo, told sab to restart. after restart.. it wont resume.. using the multi-operation also isnt working to set it to play. tried a bit of stuff, eventually realized had to shift+f5 to see that yes it was actually working.. just glitter died again on updating ui... this seems to happen a LOT.

win7 w/latest firefox :(

**Comment by shypike** [comment] 2015-09-07 13:07
@thezoggy I can confirm that sometimes Glitter stops updating the UI. For me it's fixed after a simple refresh (browser button). FF on OSX.

**Comment by thezoggy** [comment] 2015-09-07 13:22
this happens every 2-6 mins for me it seems..  its getting to the point where i cant 'trust' what i see because i dont know if its really working/updating. other themes dont have this problem

**Comment by Safihre** [comment] 2015-09-07 14:03
I never had that, is there anything in the console?
Are the API calls still being made?

**Comment by Safihre** [comment] 2015-09-07 14:19
> so if you have 6 items in your queue and it set to show 5. so 5 on page 1 and 1 on page 2. its pretty hard to move the 6th item to anywhere.. have to toggle how many to show on the page.. and upon doing so this breaks pagination.. as i changed it from 5->10 but still see just the one entry and clicking on page 1 or 2 does nothing. have to force reload page to 'fix'
I cannot reproduce this on FF on Windows or any browser. Pagination code works fine but it seems to be due to brake in the updating of the GUI on FF.

Will try to reproduce.. Does it happen when actively doing stuff or inactive? I had it open for 30 min now and working fine. Wonder if it maybe has to do with Knockout, the lost-connection-detection or something else..

**Comment by Safihre** [comment] 2015-09-07 20:52
Now it actually happened to me, freeze of the GUI in Firefox. However it was still calling the API, just not showing any changes.
Not sure where to start to fix this.. Probably somewhere in Knockout a problem. If you have any more debug info, it's very welcome.

**Comment by thezoggy** [comment] 2015-09-07 21:04
so when the ui stalls on me, firebug does show that the xhr are still being sent... i'll see if i can get more info to help figure this out

**Comment by thezoggy** [comment] 2015-09-08 02:01
the queue/history header takes up a bit of space.. could combine bulk functions in that spot.. move totals to the bottom where its logical..  free space = ? is that incomplete? complete? on what drive? etc.. 

![glitter8](http://zoggy.net/glitter8.png)

**Comment by thezoggy** [comment] 2015-09-08 05:56
also on the queue line, where you show how much is left in the queue.. should do human readable.. seeing it always in MB isnt so great. 22096 MB vs 21.56GB. pretty sure sab already has code to do this..

think this is it: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L635

**Comment by Safihre** [comment] 2015-09-08 07:39
I will change that indeed to the human-readable version.
But I want to keep it in MB for the Queue so it's more clear whats happening and you can see if it's just hanging on 1 MB.

**Comment by Safihre** [comment] 2015-09-08 08:21
I think I found 1 reason for the freezes in FF, hopefully it's fixed by d91f27c.

**Comment by thezoggy** [comment] 2015-09-10 14:22
with latest dev, long names cause wrapping with age being shown
![glitter10](http://zoggy.net/glitter10.png)

**Comment by Safihre** [comment] 2015-09-10 14:42
I noticed, just fixed it with 1c35d8f

**Comment by thezoggy** [comment] 2015-09-10 23:32
in other downloaders.. when the file is d/ling it shows a color for each server.. so you can somewhat visually see if backup/fill servers are being used... sure would be nice if that could be done on the download progress bar (not the nav but the one in the queue). also they go another step to show different colors when the article is being fetched vs being downloaded

random example:
![image](http://ic.tweakimg.net/ext/i/1336552204.png)

**Comment by thezoggy** [comment] 2015-09-13 02:25
should move the dir/path to be the tooltip:
![glitter14](http://zoggy.net/glitter14.png)

get rid of retry, let people just use the icon (add tooltip):
![glitter15](http://zoggy.net/glitter15.png)

**Comment by albino1** [comment] 2015-09-13 07:06
> when the file is d/ling it shows a color for each server

This is a pretty good idea.  Even something as simple as a two-color primary/backup would be a good addition.  If you wanted to get fancy you could do something where it scaled up in color based on how far down the priority chain it had gotten before turning red for completely missing articles.

**Comment by Safihre** [comment] 2015-09-13 10:58
I don't want to move it to the tooltip, doesn't save lots of space or make it easier to understand what is each item, especially on mobile. 

It also has to be clear that there is the option to retry, just the icon would not stand out enough and could easily be mistaken for just being indicator of error, not option to retry.

The server color thing would require some extra backend code, maybe for the next release?

**Comment by Safihre** [comment] 2015-09-14 21:14
@thezoggy did you ever experience any more freezing of Glitter?

**Comment by thezoggy** [comment] 2015-09-14 22:04
@Safihre so far its been good since that last commit of fixes

**Comment by thezoggy** [comment] 2015-11-27 10:11
one feature of plus that is nice but niche is the fact you can navigate the download report for each item very easily.. just click the < or >. for glitter you have to click off to hide modal to get to the next hit target..

**Comment by Safihre** [comment] 2015-11-27 14:02
I tried to come up with something, but since it's a dropdown of the current item it would shift up or down (depending on which direction you go). So you'd still have to move the mouse, kind of defying it's purpose to be easy.
Also important: I couldn't come up with nice JS to correctly fire the next dropdown. :expressionless:

**Comment by thezoggy** [comment] 2015-11-28 04:18
not sure if your doing this on purpose, but the completed size/age becomes blurry:
![sab8](http://zoggy.net/sab8.png)

**Comment by thezoggy** [comment] 2015-11-28 04:23
about seeing the download report, maybe just add some keyboard shortcuts, so those that are power users can just press a key to go to the next one.. vs having to rely on mouse and hitting the tiny hit target thats awfully close to the delete..

**Comment by thezoggy** [comment] 2015-11-29 08:03
the check counter can easily get out of sync (also missing tooltip).. example check off all items.. then one item finishes downloading.. thus shows wrong amount.
first page has 5, 2nd page has one.. check all (only checks off the first page.. so then checking off the last one.. it shows 7 not 6).

![glitter16](http://zoggy.net/glitter16.png)

**Comment by Safihre** [comment] 2015-11-29 09:10
It's simply the best I can do with the tools I have. I can't check all on all pages, because I don't know their ID when they are not visible. I can't know about a finished download, because it might be the same as moving from page to page. 
Still think it's better than nothing at all..

**Comment by Safihre** [comment] 2015-11-29 11:06
#399:
Made the text darker in the filelist popup.
Increased the hit target for the dropdown and checkboxes links.

**Comment by thezoggy** [comment] 2015-12-04 04:22
Just FYI, Not sure if you plan on upgrading JUI but next version has some decent things to note: http://jqueryui.com/upgrade-guide/1.12/

**Comment by Safihre** [comment] 2015-12-04 07:11
Sounds indeed like a nice upgrade that hopefully lowers the size. Although seems the final release might take some time more..

**Comment by thezoggy** [comment] 2015-12-04 11:49
i was just noting so you dont blindly jump to it.. as theres a lot of stuff that needs to change if you do..  just forewarning :)

**Comment by shypike** [comment] 2016-01-19 12:55
What's the status?
Maybe write a new issue for what you plan to do and close this one?

**Comment by Safihre** [comment] 2016-01-19 13:25
@thezoggy Maybe close this one, I changed most and others (like the color per-server) will most probably never happen.
New things are reported in #408.

**Closed** 2016-02-03 22:03 UTC
