### ISSUE TITLE
Setup wizard triggers phishing warning in Chrome v106

### ISSUE THREAD

**Issue by GOATS2K** [sabnzbd/sabnzbd#2310] opened 2022-10-15 03:20 UTC
As soon as I started setting up SABnzbd, my domain got flagged by Google and I got a "deceptive site" warning preventing me from using my domain.

<img width="1104" alt="Screenshot 2022-10-15 at 04 18 54" src="https://user-images.githubusercontent.com/55696338/195966632-410b70f7-2541-4c21-9e1b-e47275cf3ac4.png">

**Comment by sanderjo** [comment] 2022-10-15 04:30
I had that too with Chrome. Mark it as safe

**Comment by Safihre** [comment] 2022-10-15 07:25
Wonder what triggers it? The list of IP addresses in the setup?
Don't know what special thing we do..

**Comment by sanderjo** [comment] 2022-10-15 07:29
> Wonder what triggers it? The list of IP addresses in the setup?

For me: a hostname via dyndns by duckdns.org. So collateral damage caused by other host within that domain.

My own domain was never marked as unsafe.

**Comment by sanderjo** [comment] 2022-10-15 08:23
So @GOATS2K ... the blacked-oud domain ... is that a shared / dyndns domain, or your own domain ... ?

**Comment by GOATS2K** [comment] 2022-10-15 12:12
This is my own domain.

**Comment by sanderjo** [comment] 2022-10-15 12:13
> This is my own domain.

Wow.

DId you click Request Review?

**Comment by GOATS2K** [comment] 2022-10-15 12:14
I did, so I am waiting to see if that changes anything. :)

**Comment by sanderjo** [comment] 2022-10-15 12:18
> I did, so I am waiting to see if that changes anything. :)

It did work for my hostname via duckdns (on which I have a sab instance)... no more warnings from Chrome anymore.

**Comment by GOATS2K** [comment] 2022-10-15 12:21
It seems to have worked! :)

**Comment by thezoggy** [comment] 2022-10-15 23:52
Sounds like just reputation report for personal domain, nothing for sab. You should report this to the offending service/browser. They prob flag new domains not seen/no public facing services...

**Closed** 2022-10-18 08:02 UTC

**Comment by GOATS2K** [comment] 2022-10-20 14:38
For what it's worth, it happened again.

**Comment by thezoggy** [comment] 2022-10-20 17:26
What's your domain?

**Comment by Safihre** [comment] 2023-04-19 07:10
So what do you want us to do? SABnzbd has a web interface with countless buttons and inputs, how can we know what triggered it and what can we really do about it?
Or do you really think we are phishing you?

**Comment by mnightingale** [comment] 2023-04-19 07:41
Mine has started flagging this again, the subdomain I access SABnzbd from isn't even on the internet, only accessible from my LAN.

I don't have login enabled and it's only flagging /config/folders/

Last time I requested a review explaining what it was, in my case a locally running service not accessible over the internet and it was fixed within a few days. So I guess I'll do the same again.

**Comment by thezoggy** [comment] 2023-04-19 17:40
prob flag because its never seen your domain and thinks its a phishing site because of login page..  prob never ending battle of trying to guesstimate what browser side is doing to try to guesstimate the reason why.
