### ISSUE TITLE
Can't deobfuscate certain names

### ISSUE THREAD

**Issue by Diniboy1123** [sabnzbd/sabnzbd#1682] opened 2020-11-18 14:53 UTC
Good day,

I often pull linux isos from a specific indexer that's known to obfuscate their releases in an interesting format which results in having abc.xyz.EXT filenames in the resulting folders.

I looked around inside the nzb file itself and I came across the fact that these abc.xyz names are nowhere mentioned actually. Also, these files are not packed to rars or anything, therefore its a bit unclear for me where this naming comes from. However the subject field contains the right filename:

`<file poster="<redacted>&gt;" date="<redacted>" subject="[PRiVATE]-[GROUPNAME]-[INSTALLER.ISO]-[3/82] - &quot;&quot; yEnc  100000 (1/1)">`

I obviously want the file to have the INSTALLER.ISO name in this case. I have tried to enable the "Deobfuscate final filenames
" feature, but that seemingly didn't do anything with the files. I also tried the movie sorting with the %dn, but that just placed each abc.xyz.EXT file to the root download folder.

Is there a way I can extract titles from the subject with a regex a script or whatsoever? Also, where does this abc.xyz gets fetched from?

For investigating purposes I can provide nzbs but due to the nature of their contents I can only do so in email.

**Comment by thezoggy** [comment] 2020-11-18 16:21
you can look at sab logs (debug) for more info.
but most of the time its just the rarset filename or the parset data to rename. ideally you should have the deobfuscated name from the nzbjob name unless the indexer is indexing the obfuscated name..

**Comment by Diniboy1123** [comment] 2020-11-18 16:28
The nzb doesn't contain abc.xyz namings anywhere, there is no par in this specific nzb and the files are not in rar containers or anything, just raw uploaded. The name still gets picked up from somewhere when I start the download however. If I keep it in paused state it still has the names from the subject which is my goal. But as soon as it starts to download, I can see all of them changing to this abc.xyz thing.

**Comment by thezoggy** [comment] 2020-11-18 16:29
check logs, it will show where it is extracted with the name or renamed to it.

**Comment by Diniboy1123** [comment] 2020-11-18 16:30
It mentions: `[nzbstuff:1697] Detected filename from yenc: ` Is there a way to disable that?

**Comment by thezoggy** [comment] 2020-11-18 16:37
its doing that because of no pars. but this is just gathering data that can be used later on.

**Comment by Diniboy1123** [comment] 2020-11-18 16:58
Nope, it is actually the one line that renames the files from the subject field to the abc.xyz ones. I wanna get rid of that feature completely. Since in this indexer's case it just makes everything obfuscated.

There are no par files. that's right.

But looking at the code sab has no such feature to disable this yenc matching. I will just monkey patch the code.

**Comment by sanderjo** [comment] 2020-11-18 17:31
You have to set SAB's logging to +Debug. Then you will see lines like:

```
2020-09-05 20:22:22,678::INFO::[postproc:520] Running deobfuscate on directory /home/sander/Downloads/complete/test_download_100MB.2
2020-09-05 20:22:23,286::DEBUG::[deobfuscate_filenames:143] No par2 files found to process, running renamer.
2020-09-05 20:22:23,290::DEBUG::[deobfuscate_filenames:157] Trying to see if there are qualifying files to be deobfusted
2020-09-05 20:22:23,296::DEBUG::[deobfuscate_filenames:160] Deobfuste inspecting 100MB.bin
2020-09-05 20:22:23,307::DEBUG::[deobfuscate_filenames:122] Obfuscated: entropy < 3.5
2020-09-05 20:22:23,313::INFO::[deobfuscate_filenames:174] Deobfuscate renaming 100MB.bin to /home/sander/Downloads/complete/test_download_100MB.2/test_download_100MB.bin
```

or
```
2020-09-06 06:34:31,749::DEBUG::[deobfuscate_filenames:106] Not obfuscated: capitals >= 2 and smallletters >= 2  and spacesdots >= 1

2020-09-12 19:49:16,132::DEBUG::[deobfuscate_filenames:103] Not obfuscated: spacesdots >= 3

```
... or just share the NZB with me (I'm the creator of the built-in deobfuscate function)

**Comment by Safihre** [comment] 2020-11-18 17:45
Indeed there is no way to disable the fetching of the name from yenc. It's because we have a level of "trust": NZB is least trusted, followed by yenc, and the best is par2 information. That's the order we use information. 
This is usually because the NZB names are more often than not messed up due to uploaders not understanding naming conventions.. 
Indeed the Deobfuscate final filenames should work.

**Comment by Diniboy1123** [comment] 2020-11-18 18:20
```
2020-11-18 20:17:27,971::INFO::[postproc:530] Running deobfuscate
2020-11-18 20:17:27,971::DEBUG::[deobfuscate_filenames:132] No par2 files found to process, running renamer.
2020-11-18 20:17:27,971::DEBUG::[deobfuscate_filenames:146] Trying to see if there are qualifying files to be deobfuscated
2020-11-18 20:17:27,971::DEBUG::[deobfuscate_filenames:148] Deobfuscate inspecting /home/mary/Downloads/completed/mysecretdownload/abc.xyz.randomhashwashere.VOB
```

And so on the list is huge but there is nothing else, just all the files listed after this.

@sanderjo if you could send me your email address, I can send you the specific nzb file.

**Comment by thezoggy** [comment] 2020-11-18 18:23
Blue ray iso files are purposely skipped from deobfuscation

**Comment by Diniboy1123** [comment] 2020-11-18 18:38
Yeah, but they get the name from yenc before the deobfuscation. So they are abc.xyz names which I can't properly play then. I need to get the VIDEO_TS stuff back which is only present in the subject fields.

I wanna skip the yenc name retrieval completely.

**Comment by Safihre** [comment] 2020-11-18 18:49
You can't. And we won't change that because this is just a terrible way to upload files. The uploaders needs to be instructed to use proper packaging techniques.

**Comment by Diniboy1123** [comment] 2020-11-18 20:36
Well, it's a big enough group to be notable on usenet. They do that obfuscation on purpose, I am sure about that. But sadly if there is no other way I will just monkey patch such a feature.

Thanks anyway

**Comment by Safihre** [comment] 2020-11-19 03:38
@sanderjo we could use your `is_obfuscated_filename` function to determine if either the yEnc filename or the NZB filename is best?
@Diniboy1123 could you send the NZB to safihre@sabnzbd.org?

**Comment by Diniboy1123** [comment] 2020-11-19 23:15
@Safihre email sent. Thanks for taking a deeper look.

**Comment by sanderjo** [comment] 2020-11-20 10:06
I analysed the post

Multiple yenc files are pointing the **same** VOB file. That is bad; that means this post contains multiple "linux images". And they have obfuscated file names.
I've inspected the VOB and the IFO files, but I see no info inside them about original name

I woud say this is a very strange post. Mistake on side of poster? Incomplete NZB, with massing par2 renaming file?

@Diniboy1123  ... how do you play these files? Just click on a VOB file, and see if that is what you want to see? Or do you have a manual method to re-order / rename them?

**Comment by sanderjo** [comment] 2020-11-20 13:52
Update based on further analysis: with some reverse engineering and manual magic and plain luck, I'm able to sort & rename the fileset. BTW: It's four separate "Linux images", each with their own files. If you want that mapping so you can do manual renaming, let me know.

However: @Safihre tells me the the Subject formatting is incorrect. That would make automatiation quite hackery. Which leads to the following question:

@Diniboy1123 how often do you see these posts? To me, it looks like an abnormality.

**Comment by Diniboy1123** [comment] 2020-11-20 18:14
It's pretty often. All releases from thats specific group uses that. A quick filtering returned 800k results approximately but there is a lot more just my indexer doesn't return them.

I could get back the names from the subject indeed as I already mentioned. If you monkey patch the yenc renamer function and dl with the original names, you can see the actual names then with a simple regex and a python script I could rename them to the proper filenames.

**Comment by Safihre** [comment] 2020-11-20 19:40
I hope @sanderjo has a solid solution, because to me it looks quite hard. They deliberately put the filename in the wrong spot in the subject. It should be between the 2 `&quot` in `"[PRiVATE]-[GROUPNAME]-[INSTALLER.ISO]-[3/82] - &quot;&quot; yEnc 100000 (1/1)`.
How else can we know the difference between `[PRiVATE]` and `[INSTALLER.ISO]`?

**Comment by sanderjo** [comment] 2020-11-20 19:41
@Safihre I use this regexp:

`maybetag, maybeindexer, wannebefilename, ordernumber = re.findall(r'\[([^]]*)\]', nzf.filename)`

and then only wannebefilename & ordernumber are needed.

All based on N=1 ... :1234:

**Comment by Diniboy1123** [comment] 2020-11-20 21:06
Sorry, sent a few more examples. 

I also believe its quite hard to make a 100% working version, that's why I was wondering if you could at least make an option where we could toggle this yenc name fetching per tag (or if per tag this setting wouldn't be possible, then globally). With the original subject names I can still use a script to rename them myself.

Or I don't think that's possible, but a regex per tag would be amazing too. Or some custom user provided rules. Like if the %subject contains private then apply regex `\[([^]]*)\]` etc.

**Comment by sanderjo** [comment] 2020-11-20 21:56
> Sorry, sent a few more examples.

Thanks! But ... those wore too easy for SAB ... SAB's current deobfuscator did rename them nicely and correctly.

I need more difficult NZBs like the one you shared. So if you could find them?

**Comment by sanderjo** [comment] 2020-11-23 12:29
Same report https://forums.sabnzbd.org/viewtopic.php?f=2&t=25062 ... but worse: one post with 12 mkv's ... which deobfuscate should rename (unlike DVD files).

So @Safihre why is it skipped by deobfuscate? Is is because SAB does find yenc info ("Detected filename from yenc")? Is deobfuscate then skipped?

FWIW: 
* deobfuscate would not have helped much because the files would get names like "NZBname - 3.mkv"
* the nice file info is in the yenc, in the weird format outside the qoute, with the nice filename in the third "[]"

`2020-11-23 12:58:41,498::INFO::[nzbstuff:1701] Detected filename from yenc: [PRiVATE]-[WtFnZb]-[Supertje-_S03E11-12_-blabla_+_blabla_WEBDL-480p.mkv]-[4/12] - "" yEnc  978648209 (1/1366) -> abc.xyz.32dee2f83eae31.mkv`

**Comment by Safihre** [comment] 2020-11-23 12:32
> So @Safihre why is it skipped by deobfuscate? Is is because SAB does find yenc info ("Detected filename from yenc")? Is deobfuscate then skipped?

No, there should be another reason why it is skipped.

**Comment by sanderjo** [comment] 2020-11-23 12:40
Oh, wait, PEBKAC. 

2020-11-23 13:08:40,083::DEBUG::[deobfuscate_filenames:149] Deobfuscate inspecting /media/zeegat/Bla_Season_3-xpost/abc.xyz.32dee2f83eae13.mkv
2020-11-23 13:08:40,084::DEBUG::[deobfuscate_filenames:108] Not obfuscated: (upperchars + lowerchars >= 4) and decimals > 3 and spacesdots > 1

So ... deobfuscate is triggered ... but thinks there are enough Capitals ... is it seeing the directory name? Or something else wrong? That *I* can find out.

So we can back the original problem: do we want to get the info from the yenc part (third [ ] element)

**Comment by Safihre** [comment] 2020-11-23 12:52
It's not a standard, just something some group came up with...

**Comment by sanderjo** [comment] 2020-11-24 14:57
Question: could the information now already reported with "Detected filename from yenc: <yenc info with cryptic stuff> -> <obfuscated filename>" be provided as-is to a post-processing script? Maybe in an ENVVAR (https://sabnzbd.org/wiki/scripts/post-processing-scripts)?

If so, then someone could create a PP script to do the renaming afterwards based on that info (without the to need parse sabnzbd.log) 

That way, SAB itself is not effected by this non-standard scheme.

**Comment by Safihre** [comment] 2020-11-24 17:50
The information is available on a per-file basis, while we only report job-level things to post processing scripts..

**Comment by sanderjo** [comment] 2020-11-24 18:33
So ... then close this issue?

**Comment by Diniboy1123** [comment] 2020-11-25 01:24
What I am saying is that it would be a great compromise for people like me to have an option to disable fetching the name from yenc completely. Like if there would be a global setting under Switches or whatever.

I wouldn't mind setting up a separate sab instance just for that indexer, but if it would be supported out of the box I wouldn't have to always monkey patch after each update of sab.

I can then do the renaming myself with my own script and some regexes. Or if that wouldn't be possible, having the opportunity in post process scripts to read the original subjects which are not yet abc.xyz ones would be great.

**Comment by sanderjo** [comment] 2020-11-25 11:00
> Note that it was a vob file here that's skipped by the deobfuscation script AFAIK, but the IFOs were skipped too.

VOB's are skipped by design because of their extension; see https://github.com/sabnzbd/sabnzbd/blob/ade477c6e53c8077ccc5b0f3ebb0b7abe576cad5/sabnzbd/deobfuscate_filenames.py#L40
IFO's are skipped by desisgn because of their small size: https://github.com/sabnzbd/sabnzbd/blob/ade477c6e53c8077ccc5b0f3ebb0b7abe576cad5/sabnzbd/deobfuscate_filenames.py#L41

**Comment by sanderjo** [comment] 2020-11-25 11:06
> What I am saying is that it would be a great compromise for people like me to have an option to disable fetching the name from yenc completely.

I wanted to say: I think SAB does not do anything with yenc renaming in your case. 
... but ... if my statement were true, where does SAB get the filename abc.xyz.blabla from ... ? It is in the NZB (so test with editing the NZB before feedind it to SAB?), but possibly also in the article itself ... ?

Editing the NZB before feeding it to SAB might be interesting not only for testing, but also for solving the problem of the non-standard posts?

**Comment by sanderjo** [comment] 2020-11-25 11:09
@Diniboy1123 based on the info in sabnzbd.log (and current SAB, no changes), one can write a post-processing script to do renaming. So if you have a lot of these downloads ... worth the time?
Bonus points for solving your case where multiple different files have the same file name to be ... which is solvable deterministically!

**Comment by Diniboy1123** [comment] 2020-11-25 16:15
The abc.xyz names are nowhere in the nzb file. Grep it for yourself. They are picked up from yenc, which is done here: https://github.com/sabnzbd/sabnzbd/blob/d867881162a1f707f42952787d2f0373ba4f2a44/sabnzbd/nzbstuff.py#L1691

But check it for yourself. Add the nzb I sent in paused state to sab. The names of the files will be the subjects. If you start the dl they are getting replaced to abc.xyz ones. Currently its inevitable. I would love to have an option for that if to not to be ran with a switch on sab's global settings. Then i would have the name from the original subject from the nzb which is perfect.

I can't really search for more nzbs containing dvds there on that indexer since they don't have a filter for that sadly.

**Comment by sanderjo** [comment] 2020-11-25 19:47
> The abc.xyz names are nowhere in the nzb file.

You're right

@Diniboy1123 can you share the monkey patch you use?
And how often do you now see this kind of strange formatting? And any idea wether it's a mistake from the poster, or a New Method?

**Comment by Diniboy1123** [comment] 2020-11-25 21:31
Yeah exactly. What you just described is exactly what I imagined doing when I firstly opened this issue.

My monkey patch was simply to make the if statement always false. So the renaming won't run at all. Since for legit posts I don't need the yenc and in all other cases it retrieves a bad result.

Tomorrow I could try to dig the indexer for more linux isos then.

**Comment by sanderjo** [comment] 2020-11-25 21:33
> Yeah exactly. What you just described is exactly what I imagined doing when I firstly opened this issue.

It took me quite some time to understand you ... and the relevant internal of SAB. Sorry!

**Comment by Diniboy1123** [comment] 2020-11-26 01:07
Nah, it's rather my bad that I expressed myself so complicated. I am glad you put so much effort dealing with my stupid case and taking your time considering a few workarounds to solve the issue.

**Comment by Safihre** [comment] 2020-11-30 10:30
The way I see it there are 2 options:

1. Introduce a new switch to disable the use of yEnc-names.
2. Automatically detect bad-yEnc names and not use them.

I would really like to use option 2, but in this case it seems `is_probably_obfuscated('abc.xyz.32dee2f83eae13.mkv') -> False`. 
@sanderjo is there something we can improve here to make it detect it is obfusacted?
This way I can make the `if`-statement use your much better function instead of the very simple `is_obfuscated_filename()` that is used now:
```python
        if (
            yenc_filename
            and yenc_filename != nzf.filename
            and not is_probably_obfuscated(yenc_filename)
            and not nzf.filename.endswith(".par2")
        ):
```

**Comment by thezoggy** [comment] 2020-11-30 16:17
You might want to look at sonarrs logic on how they detect and handle what is obfuscated. As they have a whole list of indexer specific ones that they look out for

**Comment by thezoggy** [comment] 2020-12-01 18:19
sonarr test - https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core.Test/ParserTests/CrapParserFixture.cs
and hash regexes - https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Parser/Parser.cs#L319

**Comment by sanderjo** [comment] 2020-12-02 07:00
> sonarr test - https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core.Test/ParserTests/CrapParserFixture.cs
> and hash regexes - https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Parser/Parser.cs#L319

Thanks, @thezoggy 

`@"^abc[-_. ]xyz"`.. yes, that's an easy way: if it starts with abc.xyz or format is abc.xyz.d8eedc128f866d (so with a hex pattern), and SAB could decide it's certainly obfuscate.

@Safihre OK for you if I do that?

**Comment by Safihre** [comment] 2020-12-02 08:27
Sounds good!

**Comment by sanderjo** [comment] 2020-12-02 08:36
OK, good.

Note: I'm quite sure it will **not** solve the problem of @Diniboy1123 but I'll check that later on.

**Comment by sanderjo** [comment] 2020-12-02 18:00
Proof it works:

`2020-12-02 18:53:59,978::DEBUG::[deobfuscate_filenames:93] Obfuscated: starts with 'abc.xyz'`

**Comment by sanderjo** [comment] 2020-12-02 19:52
Tested: As I predicted, the above patch does not improve the NZB-download of @Diniboy1123 (codename DEMO*). 
I proposed a solution (no rename from yenc if `'[WtFnZb]' in nzf.filename`), but @Safihre doesn't want that.

So ... I would say we're on the wrong path.

**Comment by sanderjo** [comment] 2020-12-02 19:52
Ah, now I understand the effect of `and not is_probably_obfuscated(yenc_filename)` ... it puts the raw stuff from the NZB as filename if the yenc is obfuscated (which abc.xyz now is) And indeed that way a postprocessing script could solve it.

BUT ... I think it is time to share something an insight I got a few days ago: on indexer from sov uni a lot / all NZBs are of this format, and most of them (guesstimate: 95-99%) just have one file, obfuscated, and/but current sab's built-in deobfuscator would rename it to NZB name. Everybody happy.

... until @Diniboy1123 and forum user MauganRa provided same very strange NZBs

- Diniboy1123 (DEMO*): double trouble, because VOB files (which SAB deobfuscater does not touch) and colliding filenames
- MauganRa (Anim*): multiple files

These two users would be helped with the `and not is_probably_obfuscated(yenc_filename)` patch, but 95-99% users / download would be unhappy. And that would be bad.

So .. "not rewriting" would be bad for most downloads.

**Comment by Safihre** [comment] 2020-12-23 10:59
Seems we fixed it all now!
Tested with all @sanderjo's file's and they work well now. Or at least the best we could possible do.

**Closed by Safihre** 2020-12-23 10:59 UTC
