### ISSUE TITLE
3.4.0 beta1: postproc.y has incorrect `newfiles` in certain cases (causing deobfuscate not working)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1930] opened 2021-07-18 17:11 UTC
`newfiles` in postproc.py sometimes has two times the job name as dir. That is wrong, as that directory does not exist. 

See the /media/sander/6665-6464/**Tree Car 1234/Tree Car 1234**/b082fa0beaa644d3aa01045d5b8d0b11.mkv below.

It seems to happen if the job names ends with a number with 2 decimals or more. @jcfp something to do with guessit? Althought I have Sorting turned off (AFAIK)

Result: the call `deobfuscate.deobfuscate_list(newfiles, nzo.final_name)` has incorrect input, and so deobfuscate does not work.

```
2021-07-18 19:05:51,581::INFO::[postproc:523] Running deobfuscate
2021-07-18 19:05:51,581::DEBUG::[postproc:524] SJ000: newfiles ['/media/sander/6665-6464/Tree Car 1234/Tree Car 1234/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:05:51,581::DEBUG::[postproc:525] SJ001: nzo.final_name Tree Car 1234
2021-07-18 19:05:51,581::DEBUG::[deobfuscate_filenames:145] SJ100: filelist ['/media/sander/6665-6464/Tree Car 1234/Tree Car 1234/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:05:51,582::DEBUG::[deobfuscate_filenames:147] SJ200: filelist []
```

OK (no decimals at end):

```
2021-07-18 19:05:23,524::DEBUG::[postproc:524] SJ000: newfiles ['/media/sander/6665-6464/Seven Eight Nine/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:05:23,524::DEBUG::[postproc:525] SJ001: nzo.final_name Seven Eight Nine
```

Bad (double dir), 4 decimals at end

```
2021-07-18 19:05:51,581::DEBUG::[postproc:524] SJ000: newfiles ['/media/sander/6665-6464/Tree Car 1234/Tree Car 1234/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:05:51,581::DEBUG::[postproc:525] SJ001: nzo.final_name Tree Car 1234
```

Bad (double dir), 2 decimals at end

```
2021-07-18 19:12:16,199::DEBUG::[postproc:524] SJ000: newfiles ['/media/sander/6665-6464/One One One 11/One One One 11/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:12:16,199::DEBUG::[postproc:525] SJ001: nzo.final_name One One One 11
```

OK, 1 decimal at end:

```
2021-07-18 19:12:36,602::DEBUG::[postproc:524] SJ000: newfiles ['/media/sander/6665-6464/two two 2/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
2021-07-18 19:12:36,602::DEBUG::[postproc:525] SJ001: nzo.final_name two two 2
```

**Comment by sanderjo** [comment] 2021-07-18 17:24
In postproc.py, close after line 422, `newfiles` becomes:
`['/media/sander/6665-6464/hello moon 1234/_UNPACK_hello moon 1234/b082fa0beaa644d3aa01045d5b8d0b11.mkv']
`
... looks suspicious already ... twice the job name

At line 503, `newfiles` has turned into:

`['/media/sander/6665-6464/hello moon 1234/hello moon 1234/b082fa0beaa644d3aa01045d5b8d0b11.mkv']`

That's bad

**Comment by sanderjo** [comment] 2021-07-18 19:46
https://github.com/sabnzbd/sabnzbd/commit/b2cbb8c8d0ab7172c05bd99b08ae51c5c41919d0#diff-5242b2869e77ea17dd2047e446434821a82db00800f901458e40a39b8b5979dbL518-R519 has changes to/with `newfiles`

After revert / drop commit b2cbb8c8d0ab7172c05bd99b08ae51c5c41919d0, it works again

Good:
`2021-07-18 21:41:31,632::INFO::[postproc:435] Unpacked files ['/media/sander/6665-6464/_UNPACK_Bla One 7777/b082fa0beaa644d3aa01045d5b8d0b11.mkv']`

Good result:
`/media/sander/6665-6464/Bla One 7777/Bla One 7777.mkv`

So, @jcfp , could you have a look at this issue please

**Comment by puzzledsab** [comment] 2021-07-19 12:06
From what I can tell, this is triggered because 1234 is now detected as season 12 episode 34, which means it's an episode. That makes it call code added in this commit from 2008, which adds the nzb name to the complete dir: https://github.com/sabnzbd/sabnzbd/commit/18e7530f8f07096b3ca046fcbd68a5fa088ea1be (line 625).

I have no idea why it works like this but it seems intentional. Adding the extra level didn't cause problems when I tested with an nzb that ended in 1234.

**Comment by sanderjo** [comment] 2021-07-19 15:17
> Adding the extra level didn't cause problems when I tested with an nzb that ended in 1234.

Reference NZB, which you can put directly into SAB's "Fetch NZB from URL": https://raw.githubusercontent.com/sanderjo/NZBs/master/My%20Very%20Very%20Important%20Download%202021.nzb 

With "Deobfuscate" on, what is your result with 3.4.0 Beta1 resp 3.3.1?

**Comment by puzzledsab** [comment] 2021-07-19 20:06
Yes, it does break deobfuscate. I also noticed that if there is an existing dir with the same name in the complete dir, instead of adding a .1 dir, it will move the new files to the same dir but rename them to for instance existingfile.1.jpg. I tried returning just `self.original_path` instead of `os.path.join(self.original_path, self.original_job_name)`, but then the new files will be moved to the root of the incoming dir.

I don't know how to make it consistent because I don't understand why the old code is the way it is. Maybe @jcfp will understand it quickly so I won't spend any more time on it for now.

**Comment by sanderjo** [comment] 2021-07-19 20:13
OK, so confirmed. Good.

More hypotheses:
- mix up of working directory _UNPACK_blabla and real destination directory
- I don't see that `Unpacked files` message in my older logging. So maybe that part of the `postproc` is now called, but it shouldn't?

Yes, my hope is on @jcfp too.

**Comment by Safihre** [comment] 2021-07-25 07:35
The problem is that `file_sorter.detect` doesn't seem to check if Sorting is enabled or not, it always returns a path.
https://github.com/sabnzbd/sabnzbd/blob/1052f37d02724417fd36cfff3af07a075becaae6/sabnzbd/postproc.py#L695

**Comment by Safihre** [comment] 2021-07-25 07:55
Oke I fixed this.
Next problem: the sorter renames folders and files, but doesn't update `newfiles`.

**Comment by Safihre** [comment] 2021-08-13 06:55
I will close this, as Deobfuscate never worked with Sorting. It's not 3.4.0 specific.

**Closed by Safihre** 2021-08-13 06:55 UTC

**Comment by sanderjo** [comment] 2021-08-13 07:07
> I will close this, as Deobfuscate never worked with Sorting. It's not 3.4.0 specific.

So it's caused by Sorting?
I checked, and AFAIK I haven't sorting on.

**Comment by Safihre** [comment] 2021-08-13 07:56
355d02faa3d27ac2096d130ce5eabdecbdc623a4 fixes the problem if Sorting is not enabled.
