### ISSUE TITLE
sabnzbd truncates its own config file

### ISSUE THREAD

**Issue by sym3tri** [sabnzbd/sabnzbd#186] opened 2014-11-02 01:50 UTC
This happened when I ran out of disk space. Noticed the config file was on disk, but empty. No backup file around. Found this in the logs:

```
2014-11-01 11:48:40,801::INFO::[SABnzbd:335] Web dir is /usr/share/SABnzbd/interfaces/Plush
2014-11-01 11:48:40,802::INFO::[SABnzbd:335] Web dir is /usr/share/SABnzbd/interfaces/Config
2014-11-01 11:48:40,807::WARNING::[config:782] Cannot create backup file for /etc/sabnzbd.ini.bak
2014-11-01 11:48:40,807::INFO::[config:783] Traceback:
Traceback (most recent call last):
  File "/usr/share/SABnzbd/sabnzbd/config.py", line 779, in save_config
    shutil.copyfile(filename, bakname)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/etc/sabnzbd.ini.bak'
2014-11-01 11:48:40,814::ERROR::[config:791] Cannot write to INI file /etc/sabnzbd.ini
2014-11-01 11:48:40,815::INFO::[config:792] Traceback:
Traceback (most recent call last):
  File "/usr/share/SABnzbd/sabnzbd/config.py", line 787, in save_config
    CFG.write()
  File "/usr/share/SABnzbd/sabnzbd/utils/configobj.py", line 2113, in write
    h.close()
IOError: [Errno 28] No space left on device
```

**Comment by Safihre** [comment] 2016-10-14 21:40
I tried to reproduce, but SAB already first tries to make the backup and only if that succeeds it will save a new config. Don't think we can make it safer than that..
This is a very exotic problem since it was not reported again in 2 years.
Closing for now, nothing we can really do more.

**Closed by Safihre** 2016-10-14 21:40 UTC
Labels: Confirmed
