### ISSUE TITLE
SABnzbd ignores NZB-embedded password.

### ISSUE THREAD

**Issue by octan3** [sabnzbd/sabnzbd#466] opened 2016-02-08 11:52 UTC
Hi there,

I tried to get the NZB-embedded passwords to work ([as defined here](http://wiki.sabnzbd.org/nzb-specs)). Without success.

To reproduce: Just copy [this piece of code](http://wiki.sabnzbd.org/nzb-specs) as a file und try upload it to your sabnzbd.

Thank you.

**Comment by Safihre** [comment] 2016-02-08 12:29
Indeed, I added ```<meta type="password">secret</meta>``` to the ```<head>``` just like suggested on our Wiki and SAB ignored it.

**Comment by thezoggy** [comment] 2016-02-09 05:58
https://forums.sabnzbd.org/viewtopic.php?f=3&t=15275
https://forums.sabnzbd.org/viewtopic.php?f=4&t=11564

apparently its a 1.1 nzb feature..

**Comment by Safihre** [comment] 2016-02-09 10:02
That was very easy to add: 04c74bd
Or am I missing something? I tested it with normal and unicode passwords, works fine.

**Comment by octan3** [comment] 2016-02-09 10:16
Looks valid to me.

**Comment by thezoggy** [comment] 2016-02-09 18:06
@Safihre meta pw should be added to the list of pw to be used, not the only pw. 
ex: if user provides a pw manually, pw list is provided via sab setting and there's already a pw in the meta.. all of them should be tried.

**Comment by Safihre** [comment] 2016-02-09 18:40
@thezoggy unfortunately, ```self.password``` is not a list and I don't think it needs to be. This meta-value is extracted before the NZB is visible in the interface, so before the user can set anything. It could possibly set the password by changing the name to ```name{{{password}}}```, in that case the user knowingly overwrites the password and that one will be used. 
And from my understanding the password-list-file is always tried in case the user-set one fails, so no harm there.

**Comment by thezoggy** [comment] 2016-02-09 19:00
note that there can be many meta passwords per the spec

**Comment by thezoggy** [comment] 2016-02-09 19:15
for reference, nzbget's pw meta routine: https://github.com/nzbget/nzbget/blob/develop/daemon/queue/NzbFile.cpp#L416

**Comment by Safihre** [comment] 2016-02-09 19:40
So it also only reads the first one.. Right?

**Comment by thezoggy** [comment] 2016-02-09 20:06
I suspect so, only briefly glanced at the code though. It's be easy to test though.. Although I would think that the meta password is rarely used let alone there being multiple... Only reason I could see there being multiple ones was for something like a season pack and each ep is separately packed with a password... Thus the season pack has all the passwords... Or the wrong pw was purposely put first to thwart apps (dmca/indexing) 

-----Original Message-----

**Comment by octan3** [comment] 2016-02-09 21:31
@thezoggy The [specification](http://sabnzbd.org/resources/nzb-1.1.dtd) says:

> exactly one metadata element per item of arbitrary metadata.

So there is only one password allowed.

**Comment by thezoggy** [comment] 2016-02-09 21:39
per the page you originally linked:
```
password - if any password is required for the contents of the NZB, it can be specified in a password meta-tag. If there are multiple passwords, this tag could simply be specified more than once and they can all be tried. If it becomes a common requirement we may develop a way to associate a password tag (or indeed any meta tag) with a specific file block.
```

**Comment by octan3** [comment] 2016-02-09 21:50
Jep, I read this. They contradict themselves. But I would be lucky if it is possible to put at least one password in the NZB file.

**Comment by thezoggy** [comment] 2016-02-10 01:20
they dont contradict themselves

**Comment by shypike** [comment] 2016-02-10 08:21
Embedded multiple passwords in the "header" have been supported by SABnzbd for a while.
There may be some implementation issues, because no sites actually add them.

**Comment by thezoggy** [comment] 2016-02-10 11:33
yep sure enough, 
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L509

now you can see that the meta passwords are in fact appended to the list to try, if the user does not provide a password.. so prob need to check your logs to see if you have a `Got a password set by user ` (bad grammar) or if you see `Read 'x' passwords from meta data in NZB`. Both are at the INFO level.

**Comment by Safihre** [comment] 2016-02-11 08:35
I can verify this @octan3, I see in my logs:
```
2016-02-11 09:29:41,549::INFO::[newsunpack:512] Read 1 passwords from meta data in NZB
```
So cannot reproduce the main issue reported.

@thezoggy @shypike However, I still think we should still do 04c74bd.
This case the user will actually see in the interface that (at least 1) password has been found and that it will be tried.
We should then change those lines in newsunpack.py so that it still appends the (other) meta-passwords and the password-list. With just 04c74bd they would not be used since it's like a user password has been set.
What do you think?

**Comment by thezoggy** [comment] 2016-02-11 09:52
@Safihre by doing your code change.. will that force it to always try another pass at the rarset as a pw is always included?

**Comment by Safihre** [comment] 2016-02-11 10:05
If a meta-password is included, yes.

**Comment by shypike** [comment] 2016-02-11 11:50
@Safihre I'm working on a slightly different solution.
SABnzbd will try the following list.
1: password set by user
2: meta password(s)
3: passwords file
4: no password
I can show the first meta-password in the UI when no 1) password was set.

**Comment by thezoggy** [comment] 2016-02-11 12:14
Perhaps glitter can show the pw found in theui. Then also sab can show the pw  used in the pp report

-----Original Message-----

**Comment by shypike** [comment] 2016-02-11 21:38
Please look at this solution: https://github.com/sabnzbd/sabnzbd/pull/469

**Comment by Safihre** [comment] 2016-04-04 10:27
Merged, so this can be closed?

**Comment by shypike** [comment] 2016-04-04 11:01
Yes, I usually wait until feedback comes from the author of the issue.

**Closed by shypike** 2016-04-04 11:01 UTC
