### ISSUE TITLE
Glitter layout needs tweaking before release

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#408] opened 2015-12-08 13:42 UTC
I find the glitter layout a bit too constrained.

For example you have this huge progress bar with tons of empty space where the category could be relocated to, right in the middle of it, instead of requiring a huge window to display.

Also, the job name should get prioritized over the progress bar in terms of screen real estate, meaning the progress bar should shrink to some extent to make space for the job name.

I understand that it's a universal UI, so things are large for touch devices as well as mouse cursors.
But compared to plush(which obviously isn't really touch optimized), it's very inefficient as far as space usage goes, there must be a middle ground and I have a feeling it could be tweaked a bit to make it a bit less awkward on a non-touch device.

**Comment by Safihre** [comment] 2015-12-08 14:11
Well actually, it is so big not because of touch devices but just because I like it and people seem to like it..

One of the key annoyance I had with Plush (and of the 'competition', NZBGet) that made me create Glitter was the tiny progress bar and how much space is taken by job settings on the right.
The progress bar is also a little wider because it will display 'x articles missing' in the bar, something else that was not easy to see in Plush.

**Comment by thezoggy** [comment] 2015-12-08 16:15
up top it shows the filespace.. but doesnt seem to use the scale to highest human readable, for example: ` 3441.4 GB Free Space ` is shown instead of 3.4TB or whatever.

**Comment by thezoggy** [comment] 2015-12-08 16:16
the sab logo on the dark skin looks meh compared to it on the normal skin.. because the logo was made to go on a dark bg.. thus really needs a new version for white.. or ideally a better version that uses png transparency to do either cleanly.

**Comment by thezoggy** [comment] 2015-12-08 16:17
click on status + interface icon, modal show up.. on the dark skin.. you cant see anything behind it.. while on the normal skin you can still see stuff.. thus difference in transparency? or just byproduct of dark shadow on dark skin

**Comment by thezoggy** [comment] 2015-12-08 16:19
0.8.0b3 on dark theme, click on the status + interface icon, then click out of the modal.. the icon is still 'active'

**Comment by thezoggy** [comment] 2015-12-08 16:24
config > categories 
-- on desktop viewpoint, make the folder input wider to accommodate the fact your adding the browse button to it and there is no more left sidebar there..  
-- on mobile viewpoint, groups/indexer tag input can be reduce.. drop text label from save/add/buttons.. etc

**Comment by Cpuroast** [comment] 2015-12-08 16:25
>> 0.8.0b3 on dark theme, click on the status + interface icon, then click out of the modal.. the icon is still 'active'

Also applies to the default version of Glitter

**Comment by thezoggy** [comment] 2015-12-08 16:29
on dev, the normal (light) version is fine for me (havent tested night on dev)

**Comment by Cpuroast** [comment] 2015-12-08 16:32
> on dev, the normal (light) version is fine for me (havent tested night on dev)

This is in 0.8 beta3 on windows using Chrome, so it may have been fixed since.
I have the dark as primary and default as secondary.

**Comment by Safihre** [comment] 2015-12-09 08:47
> up top it shows the filespace.. but doesnt seem to use the scale to highest human readable, for example: 3441.4 GB Free Space is shown instead of 3.4TB or whatever.
Fixed #409
> the sab logo on the dark skin looks meh compared to it on the normal skin.. because the logo was made to go on a dark bg.. thus really needs a new version for white.. or ideally a better version that uses png transparency to do either cleanly.
@thezoggy Could you make one that works for both? All icons we have should be here: http://sabnzbd.org/icon/
We were actually thinking of making a new (vector) logo that is in the same style as the old one, but just 'flatter' and more 'modern'. But I'm not good enough with Illustrator to do this.. Maybe you or someone else has interest in this?
> click on status + interface icon, modal show up.. on the dark skin.. you cant see anything behind it.. while on the normal skin you can still see stuff.. thus difference in transparency? or just byproduct of dark shadow on dark skin
Was already fixed in dev by #402
> 0.8.0b3 on dark theme, click on the status + interface icon, then click out of the modal.. the icon is still 'active'
Cannot reproduce this anymore (know it happened before), maybe I also fixed this 'by accident' in #402.
> -- on desktop viewpoint, make the folder input wider to accommodate the fact your adding the browse button to it and there is no more left sidebar there..
Fixed #409 for >1200px
> -- on mobile viewpoint, groups/indexer tag input can be reduce.. drop text label from save/add/buttons.. etc
One should not be doing these kind of things on mobile, it will never fit in a proper way on mobile.

**Comment by thezoggy** [comment] 2015-12-11 11:03
![glitter16](http://zoggy.net/glitter16.png)
would be nice if the date being set in glitter is also used when displaying errors...

**Comment by thezoggy** [comment] 2015-12-11 11:04
@Safihre yes I can prob output a decent image to use, i have the icon source..  ill see if I can get to it by this weekend

**Comment by Safihre** [comment] 2015-12-11 11:09
The date is used, but needs a refresh after changing to also apply to errors:
![image](https://cloud.githubusercontent.com/assets/5703454/11742394/ddace25c-9fff-11e5-9708-679ae40ac75a.png)

**Comment by Safihre** [comment] 2015-12-11 11:10
@thezoggy you have the vector-source? From what I understood there was none!

**Comment by albino1** [comment] 2015-12-11 20:20
They're not vectored, but there's some reasonably clean large versions located here:

http://sabnzbd.org/icon/

Also, you can just pay a guy $5 on Fiverr to make a new vector version if you don't already have one.

**Comment by thezoggy** [comment] 2015-12-11 22:07
@Safihre I do believe so (if i dont its pretty easy to remake), just gotta recall where I placed the image from when I last touched it for http://thezoggy.github.io/sabnzbd/api/

**Comment by Safihre** [comment] 2015-12-12 13:51
@thezoggy, you also want to give a redesign of the logo a try if you have the vector? Matching Glitter and new config styles :)

**Comment by thezoggy** [comment] 2015-12-14 19:12
I have a few ideas, I'll respond back later to get some opinions.

-----Original Message-----

**Comment by thezoggy** [comment] 2015-12-19 01:44
when viewing a nzb while its downloading, the modal in glitter allows you to hide completed files... but it seems to hide par files with that.. even if they arent completed? also the modal wont let you check off samples even if they arent downloaded (as i'd wanted to remove them myself to save the bw / help out incomplete)

**Comment by Safihre** [comment] 2015-12-19 02:41
Indeed the button is confusing, I will change that. 
It hides the ones that don't have a ```nzf_id```, so that cannot be removed (anymore). Plush doesn't even show these ones without ```nzf_id``` at all.
This is also the reason you cannot check some files, because they have no ```nzf_id``` to remove it. Don't know why that is.. @shypike?

**Comment by shypike** [comment] 2015-12-19 09:47
Once the first complete par2 file is in, the others are put on a separate list and no longer reported as being in the queue. They are considered to be complete, unless they're needed in a later run. It has been like this since release 0.2.4

**Comment by thezoggy** [comment] 2015-12-19 10:32
@shypike does it change what it thinks is 'complete' if you have it set to 'download all par' vs only download first / as needed.

**Comment by shypike** [comment] 2015-12-19 20:36
@thezoggy No, it just sends the par2 files back to the normal queue when QuickCheck fails.
Having said that, I have seen some odd behaviour in that area.

**Comment by thezoggy** [comment] 2015-12-19 20:39
@shypike what about samples/samples-par. that was my issue, i couldnt select the samples to remove.. i normally have it set for sab to delete samples after d/l. but i was running into incomplete.. and looking at what it was failing on.. it was the sample and its pars.. thus if i could delete the samples i could let it complete.. but i couldnt remove the samples as the checkbox was not editable.. and then toggling the complete showed them hiding but they were at 0%.

**Comment by shypike** [comment] 2015-12-19 22:45
The samples are files just like any other, no special treatment. I'll look into that.
Or you mean that you could not delete the par2 files of the samples?

**Comment by Safihre** [comment] 2015-12-26 19:42
I also just found that when 'Download all PAR2' is turned on, the par2 is also put on this seperate list and in the queue. So the API ```get_files``` actually reports the files twice (status='active' and status='queued'):
![image](https://cloud.githubusercontent.com/assets/5703454/12007700/d4eda602-ac10-11e5-8b73-60c678b61303.png)

This had the side effect that Glitter was confused since it only has the filename to go on as unique identifier of the Object, and so it would update the wrong files in the list. I fixed that behavior, but it still looks like there is more par2 then there actually is.
I know this is a more exotic case, so probably is fine this way.

**Comment by Safihre** [comment] 2015-12-29 09:39
@thezoggy Did you by any chance have some time to look at an improved (vector) logo? 
@inpheaux is working on the new website and I have high hopes the release of 0.8.0 final is now getting close :)

**Comment by thezoggy** [comment] 2015-12-29 11:46
I had hope to do something before the trip but sadly I did not. I'll be back from Thailand in a few days..  I'll take a stab then.

-----Original Message-----

**Comment by thezoggy** [comment] 2016-01-04 23:44
i'm back.. still trying to get everything back to normality.. came up with one logo real quick to get some ideas:
![sab_logo1](http://zoggy.net/sab_logo1.png)

**Comment by Safihre** [comment] 2016-01-05 08:44
I like the shape of the arrow, but doesn't it match the icons of for example bootstrap too much? 
![image](https://cloud.githubusercontent.com/assets/5703454/12110860/b93a6b8e-b390-11e5-9d7a-50d712fa457a.png)
Maybe we can do something where the arrow comes out of the SAB? Or just of the S? Just guessing here, I'm not too good with the stuff!

**Comment by thezoggy** [comment] 2016-01-10 16:38
really think glitter's add nzb modal could benefit from some layout changes.. similar to nzbget's
![nzbget](http://nzbget.net/images/Web-Interface-02-Add-Downloads.png)

**Comment by thezoggy** [comment] 2016-01-16 04:35
you can click on a history row to show its details, clicking on that row again does not hide said details..

**Comment by thezoggy** [comment] 2016-01-17 14:12
http://stackoverflow.com/questions/26960703/how-to-change-the-color-of-header-bar-and-address-bar-in-newest-android-chrome-v

example:
```
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#4285f4">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#4285f4">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="#4285f4">
```

should check this out and see if its worthwhile addition for glitter

**Comment by thezoggy** [comment] 2016-01-17 17:18
looks like missing space after icon for Folders:
![sab_nav](http://zoggy.net/sab_0.8_nav.png)

**Comment by thezoggy** [comment] 2016-01-17 17:26
on config > special.. if you set non default values it shows the `*` but if you change them back to default.. the `*` remains until page refresh..

**Comment by thezoggy** [comment] 2016-01-17 17:37
on glitter > Status and interface options
trying the speed test, if i click the 'repeat test' icon for either download or completed it only reports back a speed for downloaded..  looking at logs (debug) all I see is:
```
2016-01-17 11:34:17,696::DEBUG::[interface:2663] Dashboard: Refresh button pressed
2016-01-17 11:34:18,210::DEBUG::[interface:2672] Dashboard: Refresh had a problem
```
both on the modal show
` (C:\Users\zoggy\downloads\…) ` as the path

going to config > folders.. both have the default entered..
Temporary Download Folder: `downloads\incomplete`
and
Completed Download Folder: `downloads\complete`

**Comment by Safihre** [comment] 2016-01-17 21:34
I personally don't like the NZBGet upload window at all (plain Bootstrap), right now Glitter's seems pretty clear: You choose an URL or file and then you specify it's options below.

Folder icon is just winder than default glyphicon so overlaps, but added it a little margin.

Added the coloring for mobile! Only knew about the Apple one, not the Android/WP. Thanks.

The Config>Special page is so rarely used that I opted for the simple solution of just not making it an AJAX submit but a real submit so it's ```*``` always gets updated.
I thought about change the text color, but if you make it red/green it's sort of like saying you chose the wrong/perfect option.

**Comment by thezoggy** [comment] 2016-01-20 23:41
copying the text from the download report produces a ugly result.. 

```
Name
Fixer.Upper.S03E07.A.Home.for.Country.Living.720p.WEB-DL.AAC2.0.H.264-koalf
Completed
2016-01-20 5:36pm
Status
Running script: SABPostProcess.py
Size
1.3 GB
Category
bypass
Path
\\?\C:\Users\zoggy\downloads\incomplete\Fixer.Upper.S03E07.A.Home.for
Source
Fixer.Upper.S03E07.A.Home.for.Country.Living.720p.WEB-DL.AAC2.0.H.264-koalf.nzb
Download
Downloaded in 2 mins 15 seconds at an average of 9.9 MB/s
Age: 5d
Servers
SuperNews=1.3 GB
Repair
[8d32402f3998402cce6f3ec5b8eb5007] Repaired in 0 seconds
Unpack
[123] Unpacked 1 files/folders in 1 sec
Script
Running user script SABPostProcess.py
```

would be nice if it was nicely formatted even if its just something like

```
Name: Fixer.Upper.S03E07.A.Home.for.Country.Living.720p.WEB-DL.AAC2.0.H.264-koalf
Completed: 2016-01-20 5:36pm
Status: Running script: SABPostProcess.py
Size: 1.3 GB
Category: bypass
Path: \\?\C:\Users\zoggy\downloads\incomplete\Fixer.Upper.S03E07.A.Home.for
Source: Fixer.Upper.S03E07.A.Home.for.Country.Living.720p.WEB-DL.AAC2.0.H.264-koalf.nzb
Download: Downloaded in 2 mins 15 seconds at an average of 9.9 MB/s
Age: 5d
Servers: SuperNews=1.3 GB
Repair: [8d32402f3998402cce6f3ec5b8eb5007] Repaired in 0 seconds
Unpack: [123] Unpacked 1 files/folders in 1 sec
Script: Running user script SABPostProcess.py
```

**Comment by shypike** [comment] 2016-01-24 17:03
Finished?

**Comment by thezoggy** [comment] 2016-01-28 00:12
@Safihre ran into this recently:
![sab11](http://zoggy.net/sab11.png)

**Comment by Safihre** [comment] 2016-01-28 09:25
Firefox/Chrome difference again, fixed in 9014ee4

**Comment by thezoggy** [comment] 2016-01-28 18:56
just fyi, @Safihre and @shypike one of my coworkers is going to work on the Japanese translations for sab.

**Comment by thezoggy** [comment] 2016-02-01 06:06
do you like this concept (could easily turn to svg so it scales nicely in browser):

![sab_logo2](http://zoggy.net/sab_logo2.png)

without border:

![sab_logo2b](http://zoggy.net/sab_logo2b.png)

**Comment by Safihre** [comment] 2016-02-01 07:26
I like that! We could see how it works out with some colors? 
Maybe a gold version like the old logo?

**Comment by thezoggy** [comment] 2016-02-03 10:05
we can play with color sure.. do you like it with the black border or not... the black border i would think puts us back in the same scenario where white vs black background.. one looks better than the other.. so personally i'd say we get away from using outlines.... or specifically a white or black one.

**Comment by Safihre** [comment] 2016-02-03 10:08
I would say without border indeed and then let see how it works out with the big logo (with SAB or SABnzbd also on/below it). Maybe it would need some outline then.

**Comment by thezoggy** [comment] 2016-02-03 21:52
went and looked back at my notes, found where that sab icon came from:
nuvola's download_manger icon: ![download_manager](http://zoggy.net/download_manager.png)

thus if we want a vector one we would have to make our own.. also used this to redo that vector one I showed you last time.. nuvola's icon is not symmetrical.. one half is slightly larger.

**Comment by jeffgeorge** [comment] 2016-02-03 22:12
I like the flat look, couple thoughts:
- Maybe have the focal point off to one side rather than the tip of the arrow, similar to where the low-point is on nuvola's highlight 'dip':

![nuvola_annotated](https://cloud.githubusercontent.com/assets/806112/12798530/f37b7bc6-ca97-11e5-8287-e0b40e482d1a.png)
- I'd like to see it rendered out in some oranges for use as the main logo. An achromatic option might be helpful in some cases, but I'd like to keep orange for the main version. Maybe pull some color choices from the "amber" section of the [Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette).
- I'm not sure what I think about the stroke. Without it, it feels way too "sharp". With it, it feels a bit too chunky. Maybe try an option with less-chunky of a stroke?

**Comment by Safihre** [comment] 2016-02-04 09:07
The center horizontal split breaks it for me a little, I would like to see it without that. So basically an arrow within an arrow, seems cool to me :)

**Comment by thezoggy** [comment] 2016-02-05 04:29
my internet has been out at my house, tech is suppose to come tomorrow.. so anyways ill hopefully be able to provide some updates after then. ill play with some color ideas (thanks @inpheaux ).

**Comment by thezoggy** [comment] 2016-02-06 00:08
4a - amber color:
![sab_logo4a](http://zoggy.net/sab_logo4a.png)

4b - with one piece move:
![sab_logo4b](http://zoggy.net/sab_logo4b.png)

4c - with one piece offset:
![sab_logo4c](http://zoggy.net/sab_logo4c.png)

**Comment by markus101** [comment] 2016-02-06 08:36
Pretty minor nit: The add NZB dialog allows you to click add without the relevant field containing any data, be nice to have some validation to prevent that.

Another piece is the alerts/warnings under the queue, sometimes I just see a cherrypy error and need to scroll to find the remove button, not sure if thats an error I'm supposed to be reading because the low height scroll window makes it awkward to follow. Overall I find it a bit awkward over all when there are multiple pages of warnings because when you hit the end the browser starts scrolling the main content. I don't really have a recommendation there, might just have to live with it unless the approach is reworked.

Love the new UI and as always the functionality is solid, nothing major since I started using it.

**Comment by thezoggy** [comment] 2016-02-06 10:34
@markus101 what cherrypy error? yeah the error/warning being at the bottom of the queue is a bit annoying since it dynamically changes sizes...  prob should move that to its own container / modal with a counter somewhere visible..  also personal quirk i hate that we have like 3 icons that look similar.. thus i always click the wrong one to get to what i want..

**Comment by jeffgeorge** [comment] 2016-02-06 21:18
I wasn't super sold on 4a on its own, but composited with [the logotype](http://www.dafont.com/fff-freedom.font) I think it looks pretty good!

![sab_new](https://cloud.githubusercontent.com/assets/806112/12869400/68e71c48-ccec-11e5-852e-30d41a496df4.png)

Anyone else have thoughts on this? If it's good, I'd like a couple SVGs rendered out:
- just the arrow, no stroke
- just the arrow, with a black stroke
- the arrow + logo composited as above, with strokes

... then we get to make new application icons, the most tedious job in the world! :weary:

**Comment by shypike** [comment] 2016-02-06 21:44
I like it, but I'm not the graphics expert.

**Comment by Safihre** [comment] 2016-02-06 22:36
What I actually ment is this, make it bi-color.
More uniform :)

![687474703a2f2f7a6f6767792e6e65742f7361625f6c6f676f34612e706e67](https://cloud.githubusercontent.com/assets/5703454/12869814/4f20fd22-cd2a-11e5-9847-47fd2ce3829c.png)


And for the stroke, make it pointy. 
No more rounded stuff in Glitter!
![68e71c48-ccec-11e5-852e-30d41a496df4](https://cloud.githubusercontent.com/assets/5703454/12869813/4f06a134-cd2a-11e5-9944-c48ada5f4dc6.png)

**Comment by Stanzilla** [comment] 2016-02-07 00:04
I like 4a, b and c look too much like the Gitlab logo :D https://about.gitlab.com/images/wordmark.png

**Comment by jeffgeorge** [comment] 2016-02-07 00:28
I *knew* that reminded me of something but I couldn't place it. I don't think the full arrow is too similar, though.

I agree with @Safihre's comments above. The horizontal facet isn't really necessary, and I'd be fine with seeing the corners eased all around the arrow, not just on the points. (Photoshop's stroke logic freaks out on acute angles like that.)

**Comment by Safihre** [comment] 2016-02-07 09:59
@jeffgeorge is it maybe also possible to make a version where also the SAB text has non-rounded stroke? Wonder what that looks like together with non-rounded stroke on the logo

**Comment by thezoggy** [comment] 2016-02-07 14:54
4d - amber color:
![sab_logo4d](http://zoggy.net/sab_logo4d.png)

4e - amber color:
![sab_logo4e](http://zoggy.net/sab_logo4e.png)

**Comment by Safihre** [comment] 2016-02-07 21:55
Can't say I'm a big fan of 4d-f, seems too light and colorful.

**Comment by thezoggy** [comment] 2016-02-08 07:34
perhaps we should offer up a dark theme for sab something along the lines of:
http://wrapbootstrap.com/preview/WB0BLML90

**Comment by Safihre** [comment] 2016-02-08 07:55
But we do? Glitter - Night? Or you mean for the Config?

**Comment by thezoggy** [comment] 2016-02-08 20:39
most of the time for dark themes.. people just take the light theme and inverse it... and it looks well.. not very good. anyways that theme i ran across yesterday looks nice without being too overtly dark..

**Comment by thezoggy** [comment] 2016-02-11 23:25
@Safihre fyi on the `Status and interface options` modal 
 * the refresh icon in the title bar has no visual change on hover / always looks 'active' due to the default color (really stands out against the close button)
 * the repeat test icon has no visual change on hover / always looks 'active' due to the default color

(if it matters, i'm using firefox)

**Comment by thezoggy** [comment] 2016-02-12 08:13
![glitter18](http://zoggy.net/glitter18.png)

still cant remove par's from the download (wanted to remove the sample stuff...)

**Comment by Safihre** [comment] 2016-02-12 08:34
The buttons intentionally have no hover state because otherwise it's not clear enough that there is a refresh button. If I make the repeat test icon less opacity it looks more like it's a disabled state than a link. 
Same for the Multi-edit and Sorting buttons above the queue, making them 0.8 opacity makes them look disabled.
This is different for the buttons in the queue/history etc where there is a background.

The par-removal thing was never addressed and has worked like this for years already since they only get downloaded when needed (see the other issue where @shypike explained this).. 
If you want to remove it you will have to turn quick check off and download all pars on. Then you will see another SABnzbd quirk: all par2 will then show up twice in the filelist

**Comment by Safihre** [comment] 2016-04-04 10:24
Let's close this and continue the discussion in #521.

**Closed** 2016-04-04 11:34 UTC

**Comment by thezoggy** [comment] 2016-04-04 21:03
there is still plenty of stuff to tweak/fix in glitter imho.. but we can create a new github issue for those if you'd like

**Comment by Safihre** [comment] 2016-04-05 04:59
Yes, this issue was getting a little of track with the logo etc so time for a new one.
