### ISSUE TITLE
rar 5.5.5 upgrade 

### ISSUE THREAD

**Issue by Freki123** [sabnzbd/sabnzbd#960] opened 2017-07-04 13:27 UTC
Seems like every version less than 5.5.5 got some problems.

https://bugs.chromium.org/p/project-zero/issues/detail?id=1286&desc=6

Given the wide prevalence of the unrar source code in third-party software, quite a few
downstream parties will be affected. The source code with the fixes can be found
under http://www.rarlab.com/rar/unrarsrc-5.5.5.tar.gz - downstream parties are
encouraged to quickly update and ship fixes.

**Comment by Safihre** [comment] 2017-07-04 13:32
I know, but there's no stable release yet. Waiting for that. 

As a side note, we don't control the unrar on Linux systems, it's the system job.

**Comment by sanderjo** [comment] 2017-07-04 19:53
Seems a dupe of https://github.com/sabnzbd/sabnzbd/issues/935#issuecomment-309974670

**Comment by Freki123** [comment] 2017-07-05 11:31
For me it reads like #935 is saying all is fine while there still seems to be a rar problem if is not version 5.5.5. And since the usenet got lots of rars it better to be save than sorry.

**Comment by thezoggy** [comment] 2017-07-05 13:53
5.5 is still in beta, we're waiting for the final version..

**Comment by thezoggy** [comment] 2017-07-05 13:56
You can just download it yourself and extract over the one that comes with Sab (rename file to match). If you don't want to wait. Each time we add a new binary file it bloat the repo a bit which increases checkout times. Thus we try to be mindful on updating our 3rd party binaries.

**Comment by Safihre** [comment] 2017-07-05 14:30
Exactly. Closing this now while we wait for the stable release.

**Closed by Safihre** 2017-07-05 14:30 UTC

**Comment by thezoggy** [comment] 2017-07-05 15:15
for those that cant wait until we include 5.5 ourselves, note that the directories may be different on your machine (this was done from win7 box).

**Windows:**
1. Install `WinRAR x64 (64 bit) 5.50 beta 5` from http://www.rarlab.com/download.htm
> direct link: http://www.rarlab.com/rar/winrar-x64-55b5.exe
2. Copy `C:\Program Files\WinRAR\UnRAR.exe` to `C:\Program Files\SABnzbd\win\unrar\x64`, say yes to overwrite.

Now both the system wide winrar is upgraded and the unrar version that sab uses is (*assuming your using 64bit tools with sab).
