### ISSUE TITLE
Large Files Failing Post-Processing

### ISSUE THREAD

**Issue by thespad** [sabnzbd/sabnzbd#2256] opened 2022-07-31 11:22 UTC
Since moving to a new host I've been seeing issues with large files (> 15Gb) failing during post-processing. They all show log errors of the form:
```
2022-07-31 12:07:37,446::INFO::[notifier:123] Sending notification: Error - Post Processing Failed for Some.File.Ive.Downloaded (see logfile) (type=error, job_cat=None)
2022-07-31 12:07:37,446::ERROR::[postproc:596] Post Processing Failed for Some.File.Ive.Downloaded (see logfile)
2022-07-31 12:07:37,448::INFO::[postproc:597] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/postproc.py", line 388, in process_job
    par_error, re_add = parring(nzo)
  File "/app/sabnzbd/sabnzbd/postproc.py", line 751, in parring
    need_re_add, res = par2_repair(nzo, setname)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1123, in par2_repair
    qc_result = quick_check_set(setname, nzo)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1980, in quick_check_set
    new = quick_check_set_new(setname, nzo)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 2118, in quick_check_set_new
    elif os.path.getsize(nzf.filepath) != par2info.filesize:
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
2022-07-31 12:07:37,456::INFO::[notifier:123] Sending notification: Download Failed - Some.File.Ive.Downloaded (type=failed, job_cat=tv)
```
I can manually run par/sfv checks and extract the archives and they work fine, but Sab fails them every time. Anything smaller works just fine.

Sab version: 3.6.0 (docker) on Ubuntu 22.04 LTS
Python 3.9.13
Linux server 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Intel Celeron N3450 / 8Gb RAM / 500Gb SATA SSD.

**Comment by thezoggy** [comment] 2022-07-31 14:16
Dupe of #2251

**Closed** 2022-07-31 14:59 UTC
