### ISSUE TITLE
0.8.x -- unable to find .s00

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#415] opened 2015-12-20 07:33 UTC
dont see it in the nzb or anywhere in logs.. just randomly shows up.
`2015-12-18 21:35:13,825::WARNING::[newsunpack:645] ERROR: unable to find "120828.s00"`

emailed you log+nzb

**Comment by Cpuroast** [comment] 2015-12-30 18:38
Same here, I've had it twice in a row.
Main archive extracts, all files are fine, yet sab fails the job.
This is using 0.8 beta4.

2015-12-29 21:24:10,315::WARNING::[newsunpack:645] ERROR: unable to find "file.r11"
2015-12-30 13:28:21,211::WARNING::[newsunpack:645] ERROR: unable to find "file.s00"

**Comment by Safihre** [comment] 2015-12-31 15:20
Yes me too, happens very randomly and the main file is still fine 100% although SAB fails and leaves it __UNPACK__. 
I emailed the NZB to Shypike a few months ago but he couldn't reproduce it.. and now the file is already DCMA removed so I cannot run it again with Debug.
@Cpuroast can you run yours again with Debug turned on? See what goes wrong in the rar command?

**Comment by Cpuroast** [comment] 2016-01-03 05:19
I ran with debug and what seems to happen:

If there's a broken rar file which uses a different name than what is contained in the par2 set:
Sab generates a repaired file using par2 which has the original name and renames all complete files with their original names.
Sab extracts the now renamed rar set successfully.
Sab erases the whole renamed rar set, but here's what seems to be the issue, it forgets to erase the source broken rar file which still has the download name.
Sab then proceeds to extract and erase other rar files which are also included in the download, until it finally reaches that lost broken rar file which obviously fails extraction and the job fails.

**Comment by shypike** [comment] 2016-01-03 13:42
Sounds convincing. Can you email a example NZB, so that I don't need to hunt one down? I can "damage" it myself. Bugs@sabnzbd.org

**Comment by Safihre** [comment] 2016-01-22 07:55
Fixed by 2b71ce8

**Closed** 2016-01-23 12:59 UTC
Labels: 1 - Confirmed, 3 - Fixed
