### ISSUE TITLE
Jobs stuck at 100%

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1095] opened 2018-01-29 03:26 UTC
using github latest develop, while i did think i was on master.
switch back to master and rebuilding teh queue. will close if it goes away.

seeing this type of activity over and over but the 100% jobs never actually get stopped.
manually stopping the jobs is not working.
rebuilding the queue did not fix.
restarting did not fix.
```
2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job star trek voyager s01e03 dvdrip ac3 xvid-sfm-[TRP]
2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Walk of Shame Shuttle S01E01 HDTV x264-W4F
2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Hack My Life S01E10 Hack or Wack HDTV x264-W4F-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Allegiance S01E08 HDTV x264-BATV-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job X Company S01E06 HDTV x264-KILLERS-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E10 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E09 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E08 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E07 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E06 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E05 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E04 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E03 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E02 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Young and Hungry S02E01 HDTV x264-2HD-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E12 DVDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E13 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E11 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E10 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E08 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E07 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E06 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E05 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E02 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E01 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idl

2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job star trek voyager s01e03 dvdrip ac3 xvid-sfm-[TRP]
2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Walk of Shame Shuttle S01E01 HDTV x264-W4F
2018-01-28 22:09:32,342::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Hack My Life S01E10 Hack or Wack HDTV x264-W4F-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Allegiance S01E08 HDTV x264-BATV-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job X Company S01E06 HDTV x264-KILLERS-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E10 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E09 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E08 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E07 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E06 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E05 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E04 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E03 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job TURN S01E02 BDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job Young and Hungry S02E01 HDTV x264-2HD-Obfuscated
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E12 DVDRip X264-OSiTV
2018-01-28 22:09:32,343::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E13 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E11 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E10 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E08 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E07 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E06 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E05 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E02 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idle_jobs] Ending job State Of Affairs S01E01 DVDRip X264-OSiTV
2018-01-28 22:09:32,344::INFO::[nzbqueue:799] [sabnzbd.nzbqueue.stop_idl
```

**Comment by mgaulton** [comment] 2018-01-29 03:26
2018-01-28 22:10:05,440::INFO::[nzbqueue:893] Found idle job ReGenesis S02E12 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,440::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E12 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,440::INFO::[nzbqueue:893] Found idle job ReGenesis S02E11 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,440::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E11 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,442::INFO::[nzbqueue:893] Found idle job ReGenesis S02E09 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,442::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E09 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,442::INFO::[nzbqueue:893] Found idle job ReGenesis S02E07 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,442::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E07 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:893] Found idle job ReGenesis S02E03 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E03 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:893] Found idle job ReGenesis S02E05 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E05 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:893] Found idle job ReGenesis S02E01 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:907] Resetting bad trylist for job ReGenesis S02E01 INTERNAL BDRip x264-ARCHiViST
2018-01-28 22:10:05,443::INFO::[nzbqueue:893] Found idle job Thunderbirds Are Go S01E07 HDTV x264-FiHTV-Obfuscated
2018-01-28 22:10:05,443::INFO::[nzbqueue:907] Resetting bad trylist for job Thunderbirds Are Go S01E07 HDTV x264-FiHTV-Obfuscated
2018-01-28 22:10:05,443::INFO::[nzbqueue:893] Found idle job Bering Sea Gold S04E09 The Battle for Tomcod HDTV x264-W4F

**Comment by Safihre** [comment] 2018-01-29 05:08
We need a bit more information.
What kind of system do you run Sabnzbd on? How much Article cache do you have set? 
Manually stopping job you mean setting priority to Stop? 
Do you have any servers with problems? Like login failures etc?

**Comment by thezoggy** [comment] 2018-01-29 05:41
also, change your logging level to DEBUG

**Comment by mgaulton** [comment] 2018-02-02 17:54
Apologies, I was away a few days.
It seems to have stopped since switching back to master from devel.
just to backfill in case it happens again.

Opensuse 42.3 with Python 2.7.13
Yes, changing priority to Stop is what I was referring to, it was 
None of the servers appear to be having issues.
My delug logging was enabled, but other than those stop_idle  lines, nothing really jumped out at me.

**Comment by Safihre** [comment] 2018-02-04 18:32
Could you possibly switch back to `develop` and do a `git pull` to make sure you get the changes I made today?
I hope this helps and we can go from there :)

**Comment by kucharskim** [comment] 2018-02-04 21:56
I see similar issue with SABnzbd 2.3.2 on OpenBSD/amd64 6.2-current (Feb  2 18:24:53 MST 2018) on Python 2.7.14 and SABYenc module 3.3.2 (without sabyenc also had this problem).

**Comment by Safihre** [comment] 2018-02-04 22:01
Please verify that all your servers are working correctly by doing a server test.

**Comment by kucharskim** [comment] 2018-02-04 22:06
> Please verify that all your servers are working correctly by doing a server test.

I belive they are working as problem started after upgrade of SABnzbd. I took the failed nzb-file and used very simple Perl script which talks NNTP and fetches articles from a server and I have no issues downloading entire set. Then I verified archive with par2 cli and all is good. Each failed nzb-file from SABnzbd I verified like that and all works, but not for SABnzbd.

**Comment by Safihre** [comment] 2018-02-04 22:10
Oke but please perform the server test within Sabnzbd just to be sure.
When jobs are stuck at 100%, are any files inside the job not finished yet? (hover over the job name and click the folder icon)

**Comment by kucharskim** [comment] 2018-02-04 22:16
This is from memory as I don't have problem at hand:

> When jobs are stuck at 100%, are any files inside the job not finished yet?

Yes, there were 2 files at 99% or 98%. On main view of the download page says 100% and all is green. Download was progressing as I could see space used on the disk and I could see network traffic from SABnzbd.

I will do test server when I will have problem again. To do what you asked (test server and files not finished) I need some time.

**Comment by kucharskim** [comment] 2018-02-10 10:16
I've tested this today and when download is stuck going to settings and testing connection for two servers which I have defined is successful (`Connection Successful!`).

For the file today (which is small, only 1.6GB) all files in Web UI in under the NZB details (the folder icon) are at 100% and the whole nzb-set is also at 100% (main view, the queue), however from logs you can see which file(s) from the set is problematic:

```
[nzbqueue:903] Resetting bad trylist for file DOWNLOAD_NAME.part15.rar in job DOWNLOAD_NAME
[nzbqueue:903] Resetting bad trylist for file DOWNLOAD_NAME.vol07+3.par2 in job DOWNLOAD_NAME
[nzbqueue:907] Resetting bad trylist for job DOWNLOAD_NAME
```

Then after a couple of minutes with the job at 100% logs which this:

```
[nzbqueue:907] Resetting bad trylist for job DOWNLOAD_NAME
[nzbqueue:799] [N/A] Ending job DOWNLOAD_NAME
[nzbqueue:893] Found idle job DOWNLOAD_NAME
[nzbqueue:907] Resetting bad trylist for job DOWNLOAD_NAME
[nzbqueue:799] [N/A] Ending job DOWNLOAD_NAME
[nzbqueue:893] Found idle job DOWNLOAD_NAME
[nzbqueue:907] Resetting bad trylist for job DOWNLOAD_NAME
```

**Comment by kucharskim** [comment] 2018-02-10 10:21
```
# ls -1 incomplete/DOWNLOAD_NAME/__ADMIN__/ | cut -f1-2 -d_ | sort | uniq -c | sort -n
   1 DOWNLOAD_NAME.nzb.gz
   1 SABnzbd_attrib
   1 SABnzbd_nzo
  21 SABnzbd_nzf
4134 SABnzbd_article

# du -sh incomplete/DOWNLOAD_NAME/__ADMIN__/
1.5G    incomplete/DOWNLOAD_NAME/__ADMIN__/
```

Directory `incomplete/DOWNLOAD_NAME` contains nothing except `__ADMIN__` directory.

**Comment by Safihre** [comment] 2018-02-10 10:22
Could you send me the whole debug log at safihre@sabnzbd.org?

**Comment by kucharskim** [comment] 2018-02-10 10:30
Do you mean `SABnzbd.py --logging 2 --log-all` or something else/more?

**Comment by Safihre** [comment] 2018-02-10 10:35
Click in the interface on Status and Interface settings window and click Show Logging, that should include all.

**Comment by Safihre** [comment] 2018-02-11 16:33
@kucharskim Could you go into Status and Interface settings window and there change the logging from `+Info` to `+Debug`?
I am not sure I understand what is going wrong. The `Ending job` should do a force-end of the job, so it doesn't make sense that it doesn't end..

**Comment by Safihre** [comment] 2018-02-12 08:51
Very strange, the log you send is the whole log right? No changes?
There is not 1 line from the Assembler, no files written to disk, that's super strange.
What kind of device is this on?

**Comment by kucharskim** [comment] 2018-02-12 10:42
It's current OpenBSD/amd64 VM running on qemu-kvm under Linux.

```
OpenBSD 6.2-current (GENERIC) #4: Sat Feb 10 18:00:13 MST 2018
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC
```

**Comment by scriptzteam** [comment] 2018-02-26 16:19
Doing the same for me ;)

Large queue about 2000 items, and it downloads and just stuck at 100% and nothing more ...

Have sab 2.3.2 and ubuntu 16

**Comment by Safihre** [comment] 2018-02-26 16:20
What if you pause the queue, does it eventually continue? Because so far I've only seen this if the system just can't keep up with the writing to disk.

**Comment by scriptzteam** [comment] 2018-02-26 16:46
paused and cannnot unpause

hmm i also tried one single file in queue and it stuck at 100%, tried different settings at Switches but nothing helps

**Comment by Safihre** [comment] 2018-02-26 16:54
Do you have any servers that are less reliable or unavailable?
In any case, could you enable Debug logging in the Status window and then after it happens again save the log by clicking Show Logging so it gets anonymized and post it here (drag and drop the text file into the window, Github will post it as a link).

**Comment by Safihre** [comment] 2018-05-03 15:08
Closing until there are more logs to analyze.

**Comment by kucharskim** [comment] 2018-09-02 20:48
This is still present with 2.3.5RC1 and it seems it's related to `download_free` and maybe with `direct_unpack=0` setting. I deselected `Direct Unpack` via web UI as I don't want to have it enable and I have `download_free=40G`. Once in a while I force download an nzb-file when free space is below 40GB and that is when the problem happens. When download fails because it's stuck at 100% I free space above 40GB and retry the download it succeeds.

**Comment by kucharskim** [comment] 2018-09-15 23:36
Tested with SABnzbd.py-2.3.5 and problem is still there. I can reproduce this with attached [998-nzb-testing.nzb.gz](https://github.com/sabnzbd/sabnzbd/files/2386177/998-nzb-testing.nzb.gz) each time disk space is below 40GB (see download_free setting) even when I use priority -> forced in web UI.

[sabnzbd-github-issue-1095-20180915-debug.log.gz](https://github.com/sabnzbd/sabnzbd/files/2386174/sabnzbd-github-issue-1095-20180915-debug.log.gz)

**Comment by thezoggy** [comment] 2018-09-16 05:37
so you set a download min space limit.. and you have less than that.. and it stops. and you dont want that? just change the limit/remove the limit? (as it is doing what it is intended to do).

**Comment by kucharskim** [comment] 2018-09-16 08:33
> you set a download min space limit and sab pauses when you have less than that.

This is expected behavior and it's not what is reported in this GitHub issue.

> if you dont want that? just change the limit/remove the limit? (as it is doing what it is intended to do).

I know how to workaround the problem. However it's a bug as when priority is set to `force` and download stops after reaching `100%` of download and doesn't proceed to verification, repair and extraction of data.

In version of sabnzbd 1.2.1 this worked as intended and was intuitive as I leveraged that feature a lot. It allows me to go through download queue which is paused because it's below 40GB of free space and hand pick items which are small enough and can be downloaded.

**Comment by kucharskim** [comment] 2018-09-16 08:40
Also, what is confusing, SABnzbd reports after idle download timeout, that nzb file failed and one can think download is damaged, but it's not. Using different nzb downloader fetches data successfully.

**Comment by Safihre** [comment] 2018-09-16 09:06
Ah, now I understand it better. I could reproduce this probably.

> idle download timeout

What timeout do you mean?

**Comment by kucharskim** [comment] 2018-09-16 09:14
>> idle download timeout
>
> What timeout do you mean?

```
2018-09-16 00:02:07,424::INFO::[nzbqueue:892] Found idle job 998-nzb-testing
2018-09-16 00:02:07,425::INFO::[nzbqueue:906] Resetting bad trylist for job 998-nzb-testing
2018-09-16 00:02:07,426::INFO::[nzbqueue:798] [N/A] Ending job 998-nzb-testing
2018-09-16 00:02:25,423::INFO::[nzbqueue:434] [N/A] Removed job 998-nzb-testing
```

I didn't know how to best express this, but I was referring to above scenario in logs. When idle job finally gets removed, as it reached a timeout, didn't finish in time and in web UI is reporting the job as failed.

**Comment by thezoggy** [comment] 2018-09-16 16:36
so from your limited logs, you can see that the logic is in `stop_idle_jobs`. which is kicked off by the `check_all_tasks` logic which happens every (30 sec > 9+, so 4.5 mins). 
`check_all_tasks` - none of that code has change in 9 years (the specific check was added to the code 6 years ago). so that code is probably fine.

looking at `stop_idle_jobs`, that is prob where the issue lies.. can see its been changed a few times, recently:
https://github.com/sabnzbd/sabnzbd/commit/8ec53a3bce8ef37f3533fb05718d23f15d8580a0

a blanket logic of knowing if something stalled is hard because the job could just be giant or the system specs could just be low..  so trying to catch both scenarios requires better logic than what we have currently (use cpumarks/job size/etc to alter the logic)

**Comment by kucharskim** [comment] 2018-09-16 17:07
As I jump from 1.2.1 to 2.3.x behavior change could be done not even recently. I would need to look deeper, but interesting change which caught my eye is 3d6dfec47ad63b21c1459035b4cef07cd71d631e. Based on my testing behavior is driven by `download_free` setting, so I'm looking at code which handles this variable.

**Comment by kucharskim** [comment] 2018-09-16 19:03
My repro steps with following diff:

```
diff --git a/sabnzbd/assembler.py b/sabnzbd/assembler.py
index 4bebadad..c99f4504 100644
--- a/sabnzbd/assembler.py
+++ b/sabnzbd/assembler.py
@@ -81,11 +81,6 @@ class Assembler(Thread):
                         # Abort all direct unpackers, just to be sure
                         sabnzbd.directunpacker.abort_all()
 
-                    # Place job back in queue and wait 30 seconds to hope it gets resolved
-                    self.process(job)
-                    sleep(30)
-                    continue
-
                 # Prepare filename
                 nzo.verify_nzf_filename(nzf)
                 nzf.filename = sanitize_filename(nzf.filename)
```

makes it work again, like it was with version 1.2.1. This reverts part of 3d6dfec47ad63b21c1459035b4cef07cd71d631e commit.

**Comment by thezoggy** [comment] 2018-09-17 00:11
so what i think is going on is that the job is idle, while idle it gets placed to re-process.. but then due to it being idle it gets removed/re-added to be re-processed.. so endless loop.  to verify if this is true, in your logs can you do `grep "Found idle" sabnzbd.log` and post the output here

**Closed** 2018-10-09 13:14 UTC

**Comment by kucharskim** [comment] 2018-10-16 15:48
Thank you!

**Comment by LeeThompson** [comment] 2019-08-06 03:50
Just had this happen on Windows 7 (2.3.9 [03c10dc]) (running as a binary).

```
2019-08-05 20:44:27,572::INFO::[nzbqueue:784] [N/A] Ending job (JOB NAME)
2019-08-05 20:45:00,573::INFO::[nzbqueue:878] Found idle job  (JOB NAME)
2019-08-05 20:45:00,573::INFO::[nzbqueue:892] Resetting bad trylist for job  (JOB NAME)
2019-08-05 20:45:00,573::INFO::[nzbqueue:784] [N/A] Ending job  (JOB NAME)
2019-08-05 20:45:33,608::INFO::[nzbqueue:878] Found idle job (JOB NAME)
2019-08-05 20:45:33,608::INFO::[nzbqueue:892] Resetting bad trylist for job  (JOB NAME)
```

Just loops over and over again at 100% for 20 minutes so far.

**Comment by Safihre** [comment] 2019-08-06 08:10
If you have a large Article Queue, it can be stuck indeed writing to disk and decoding. Those queues usually are in balance and not too big.. But sometimes :O

**Comment by agrajag9** [comment] 2020-02-22 21:58
I know this was closed, but I want to drop some more debugging here because it's definitely still an issue for many.

I noticed a pattern in a lot of the "stuck at 100%" posts I've seen on reddit and the forums, in that a lot of it occurs on systems with bottlenecked drive IO. In my case I'm storing everything over NFS on GbE links, both `download_dir` and `complete_dir`. My sab host and NFS exports are on the same subnet and same switch, so no routing to introduce latency issues at all; but sometimes the NFS latency can get slow.

What I noticed really is the log churn is EXTREMELY slow during the `+Delete` post-processing phase. Each file delete takes >1s and when you have hundreds of files to delete, that can take a pretty long time.

For a single one of my downloads there were 653 "Deleting file" lines in the logs. The average delta between them was 3.6 seconds with a standard deviation of 0.9, for a total of 2349.043 seconds.

I think this points to this being less "broken" and more "highly inefficient". I haven't had a chance to dig into this post-processing script yet, but I'm guessing it's in there...

**Comment by agrajag9** [comment] 2020-02-24 16:25
I re-ran a bunch of my "slow to post-process" NZBs again using local storage for the `download_dir` and confirmed that they all completed and moved out of the queue MUCH faster. To me this confirms that there's a filesystem-level optimization issue in the post-processor.
