### ISSUE TITLE
Download hangs forever if server cannot be resolved

### ISSUE THREAD

**Issue by thespad** [sabnzbd/sabnzbd#2320] opened 2022-10-29 16:55 UTC
If a server's hostname cannot be resolved then a download trying to check against it will hang forever. Disabling the server, pausing and restarting the download, restarting sab entirely, does not allow it to recover. Only removing the download entirely and re-importing (or the server in question coming back online) seems to allow it to resume.

![image](https://user-images.githubusercontent.com/8425502/198843471-8253308c-1b3a-47ef-85a4-1b0f9bd6d7cc.png)

I would have assumed that there was some kind of timeout in place for name resolution, similar to or using the timeout value attached to the server configuration, but it never seems to fail and just tries indefinitely.

Running 3.7.0 RC1 in docker.

**Comment by Safihre** [comment] 2022-10-29 18:08
There's indeed no timeout.
@sanderjo do you maybe know why here we don't use the functions from `getipaddress` that timeout after 3 seconds?
Seems pretty straightforward to use those also for getting newsserver info, wonder why we never did..

**Comment by sanderjo** [comment] 2022-10-29 18:29
AFAIK, and I might be completely wrong, but anyway:

> why here we don't use the functions from `getipaddress` that timeout after 3 seconds?

Would that solve it? 
My guess at the above problem is that SAB does not declare an unresolvable server as 'dirty' / 'ignore for 10 minutes', so that other newssrvers can take over.

A bit like filling out www.google.nl (resolvable, but no newsserver) as newsserver with best prio ... SAB will keep trying, and will bog down. See screenshot and logging.

SAB does have a mechanism "if failed login => ignore for 10 minutes", right? If so, use that for any misbehaving newsserver?

![image](https://user-images.githubusercontent.com/1273502/198847085-052d2e55-aac3-4596-aa9b-1b699a95c7e9.png)



```
2022-10-29 20:23:14,571::DEBUG::[downloader:173] www.google.nl: Re-using address None
2022-10-29 20:23:14,573::INFO::[downloader:670] 6@www.google.nl: Initiating connection
2022-10-29 20:23:14,575::DEBUG::[downloader:173] www.google.nl: Re-using address None
2022-10-29 20:23:14,575::INFO::[downloader:670] 7@www.google.nl: Initiating connection
2022-10-29 20:23:14,575::DEBUG::[downloader:173] www.google.nl: Re-using address None
2022-10-29 20:23:14,576::INFO::[downloader:670] 8@www.google.nl: Initiating connection
2022-10-29 20:23:14,577::DEBUG::[downloader:173] www.google.nl: Re-using address None
2022-10-29 20:24:14,656::INFO::[downloader:950] Thread 1@www.google.nl: timed out
2022-10-29 20:24:14,656::DEBUG::[downloader:975] Re-adding article OyGyQxWoHmMxHzPaRdGeMlXz-1658672640035@nyuu from sometestfile-100MB.part02.rar to server <Server: www.google.nl:563>
2022-10-29 20:24:14,657::INFO::[downloader:950] Thread 2@www.google.nl: timed out
2022-10-29 20:24:14,657::INFO::[downloader:950] Thread 3@www.google.nl: timed out
2022-10-29 20:24:14,657::INFO::[downloader:950] Thread 4@www.google.nl: timed out
2022-10-29 20:24:14,658::INFO::[downloader:950] Thread 5@www.google.nl: timed out
2022-10-29 20:24:14,658::INFO::[downloader:950] Thread 6@www.google.nl: timed out
2022-10-29 20:24:14,658::INFO::[downloader:950] Thread 7@www.google.nl: timed out
2022-10-29 20:24:14,658::DEBUG::[downloader:975] Re-adding article NiFsKxNsWjCxXxQfPtNmGyOw-1658672640039@nyuu from sometestfile-100MB.part02.rar to server <Server: www.google.nl:563>
2022-10-29 20:24:14,658::INFO::[downloader:950] Thread 8@www.google.nl: timed out
2022-10-29 20:24:14,659::DEBUG::[downloader:975] Re-adding article JqMdEoVhTaRtAdLeYfAeCvRi-1658672640078@nyuu from sometestfile-100MB.part02.rar to server <Server: www.google.nl:563>
```

**Comment by sanderjo** [comment] 2022-10-29 18:32
With www.google.nl filled out as newsserver, SAB keeps on trying and pushing and doing things with it. Per minute around 16 things done.

I'm surprised about that. Why doesn't SAB put www.google.nl in the dugout with a 10 minute yellow card?


```
$ cat .sabnzbd/logs/sabnzbd.log | grep google.nl | cut -c-16 | uniq -c
     20 2022-10-29 20:06
     16 2022-10-29 20:07
     17 2022-10-29 20:08
     16 2022-10-29 20:09
     17 2022-10-29 20:10
     10 2022-10-29 20:11
     17 2022-10-29 20:12
     13 2022-10-29 20:13
      1 2022-10-29 20:14
     16 2022-10-29 20:15
     16 2022-10-29 20:16
     17 2022-10-29 20:17
     11 2022-10-29 20:18
     17 2022-10-29 20:19
     13 2022-10-29 20:20
     17 2022-10-29 20:21
     16 2022-10-29 20:22
     17 2022-10-29 20:23
     11 2022-10-29 20:24
     17 2022-10-29 20:25
     13 2022-10-29 20:26
     17 2022-10-29 20:27
     16 2022-10-29 20:28
     17 2022-10-29 20:29
```

**Comment by Safihre** [comment] 2022-10-30 08:00
@sanderjo that's on purpose, and also good to consider for the case of @thespad:
We seperate problems in 2 types of failures, temporary and permanent ones. With the temporary ones like a timeout, we don't want SABnzbd to just ignore the primary server and drain the potential secondary block server.
For permanent failures, like wrong username/password we do want it to continue to the next server.

Bit of a tough spot here: if we let it back off after such temporary failures like timeouts, we will probably get angry users where SABnzbd drained their block accounts because the primary server just had an hour timeout..

**Comment by thespad** [comment] 2022-10-30 09:49
Could you not compromise and at least have it gracefully handle if you disable the affected server? Right now if you do that, existing downloads that were stuck trying to resolve/connect will stay hung even after a restart of sab.

That way you don't accidentally consume peoples' block accounts but if a user knows a server is broken they can disable it to get things working again (in the case that triggered this issue it was a block account that stopped resolving). Perhaps even have a "disable for X time" option on the servers similar to the queue pause?

**Comment by Safihre** [comment] 2022-10-30 10:15
It indeed should handle that gracefully, wonder why it did not.
Wonder in this case if the Python `getaddrinfo` never returned.
Don't know if there's a good way for me to reproduce this, since if I fill an invalid hostname it returns instantly empty.

**Comment by thespad** [comment] 2022-10-30 11:00
Yeah, this was a valid hostname (eu.usenetfire.com) but the nameservers for the domain appeared to be down entirely for a few hours.

What's interesting is that if I disabled the server and restarted it no longer showed the "Resolving address" message, and the server wasn't listed in the connection summary, but the downloads seemed to be stuck. As this was the last server in the list, I guess it should have just failed those missing parts and continued to check/repair.

**Comment by puzzledsab** [comment] 2022-10-30 22:19
> Bit of a tough spot here: if we let it back off after such temporary failures like timeouts, we will probably get angry users where SABnzbd drained their block accounts because the primary server just had an hour timeout..

That's what the Required server option is there for.

**Comment by sanderjo** [comment] 2022-11-02 20:03
> > Bit of a tough spot here: if we let it back off after such temporary failures like timeouts, we will probably get angry users where SABnzbd drained their block accounts because the primary server just had an hour timeout..
> 
> That's what the Required server option is there for.

From SAB GUI: 
**Required**  In case of connection failures, the download queue will be paused for a few minutes instead of skipping this server

So ... that is not checked, but at this moment SAB behaves like it is checked ... ? 

What would happen if SAB would follow that setting strictly? So, if not checked, and something goes wrong with a server (unresolvable, no login prompt at all, login fails), put that server on the penalty bench with a 10 minute yellow card, and continue with other servers.

**Comment by thezoggy** [comment] 2022-11-02 21:02
Just set max retires, don't set it as required. So it retries z times and move on. There is also the thing to not make it sit in timeout so long. But yes we don't want to just toss out a server. We don't want to cater towards handling it users misconfigure something to affect how we just handle when a server is having a temp outage or local network issue. If it's an important server, set it as required. But honestly most usenet servers are distributed and rarely ever have any customer facing outage unless it's a major thing..

**Comment by thespad** [comment] 2022-11-02 21:46
The point here is that I *have* set timeouts and max retries, and it doesn't make a difference to this behaviour. The retries don't apply because it never successfully connects *or* fails, it just hangs in the name resolution phase, and the downloads don't gracefully recover even if you manually disable the affected server.

**Comment by thezoggy** [comment] 2022-11-03 00:49
if you go config > servers > and test, does it fail there?

to better understand your situation, you are not adding a new server.. but this was existing server and had been working.
but then something caused you to not have dns and sab doesn't recover gracefully from this scenario?

share debug logs, is it trying v4? v6? does it show it tried and failed.. or traceback?

share your docker compose as well.
also are you using reverse proxy?

**Comment by sanderjo** [comment] 2022-11-03 06:39
> The point here is that I _have_ set timeouts and max retries, and it doesn't make a difference to this behaviour. The retries don't apply because it never successfully connects _or_ fails, it just hangs in the name resolution phase, and the downloads don't gracefully recover even if you manually disable the affected server.

Ah, yes. The only hypothesis I can think of: SAB assigns an article to a newsserver, and if that server is not there, that article gets stuck and thus the whole download gets stuck... ? But there are more knowledgable people in this thread.

**Comment by thespad** [comment] 2022-11-03 09:03
Yes, the server test fails in this scenario.

The server in question is the 3rd of 3. The issue, as best I can tell, is that their nameservers both went offline for several hours, meaning that the server was no longer resolvable. For the duration of the outage, all in-progress downloads, or downloads that started after the outage began (which needed to check that server for parts) hung trying to connect to the dead server, even after disabling it and restarting sab.

I'm afraid I can't provide debug logs as I didn't have debugging enabled at the time and obviously can't replicate their infrastructure being down, but if it happens again I'll make sure I get them.

I don't think the way I've got things setup is a factor here, but:

```yaml
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:unstable
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/data:/data:rw
      - sabnzbd_data:/config:rw
      - ./sabnzbd_temp:/sabnzbd_temp:rw
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - wireguard
    security_opt:
      - no-new-privileges=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd-http.rule=Host(`sabnzbd.example.org`)
      - traefik.http.routers.sabnzbd-http.entrypoints=http
      - traefik.http.routers.sabnzbd-http.middlewares=middleware-ipwhitelist@file
      - traefik.http.routers.sabnzbd-http.service=sabnzbd-svc
      - traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080
```

**Comment by puzzledsab** [comment] 2022-11-03 23:57
I think I replicated this by having multiple available servers, edit the sabnzbd.ini so that the last one has an invalid hostname, and then add an nzb with missing parts. This results in this line being repeated over and over (so not a timeout problem):
[downloader:227] Retrieving server address information for nonexistenusenetserver.us`

No article is registered as checked on that server, so the download percentage does not increase.  The name resolving does not give up until I disable the server. After a short while Sab will do
[nzbqueue:901] Resetting bad trylist for file [...]

but this does not make it realize that all servers have been tried. Possibly because the failing server is the last in the list. Instead it will try to reset the trylist repeatedly.

I think there are several issues that should be fixed here. Servers with an invalid host name should be treated like a failure to connect instead of retrying over and over and the handling of the trylist needs to be improved.

@Safihre : Have you looked into it yet? If not I can try.

**Comment by Safihre** [comment] 2022-11-04 07:57
@puzzledsab Would be great if you have time to take a look!

**Closed** 2022-11-16 18:51 UTC
Labels: Bug
