### ISSUE TITLE
Sabnzbd duplicate download job after repair failed

### ISSUE THREAD

**Issue by Magikarplvl4** [sabnzbd/sabnzbd#1861] opened 2021-04-20 21:28 UTC
Hi Dev's of Sabnzbd,

I like to report an issue according to the strange behavior of sabnzbd.
Initially, the issue was reported on the GitHub of Sonarr (https://github.com/Sonarr/Sonarr/issues/4451).
After some Discord chatting with Markus from Sonarr, we figured out that sabnzbd duplicates (3 times) the download job when sab tries to repair a broken download.
the duplication creates confusion on the end of Sonarr because the unique ID returned 3 times with different status from an API call from Sonarr.
At the end Sonarr got confused and can't track the status correctly & import the file.
![image](https://user-images.githubusercontent.com/2944704/115465479-f8206500-a22e-11eb-850c-4a74371ce7bb.png)

You can see the behavior visually in the web GUI of sabnzbd. The same entry appears 3 times in the history tab:
![image](https://user-images.githubusercontent.com/2944704/115465917-98768980-a22f-11eb-8688-f355a3b36a8e.png)

This issue is reproducible with an nzb file that I can provide, debug logs also available if I can share it in a safe way.

**Comment by thezoggy** [comment] 2021-04-21 00:33
What version of sab and do you have logs?

**Comment by Magikarplvl4** [comment] 2021-04-21 09:31
Hi @thezoggy,

version:  3.2.1 [0542c25]

debug logs Sabnzbd:
[sabnzbd Debug.log](https://github.com/sabnzbd/sabnzbd/files/6349721/sabnzbd.Debug.log)

**Comment by Magikarplvl4** [comment] 2021-04-21 09:34
Also the trace logs from Sonarr with the response from Sabnzbd api:
[sonarr.trace.txt](https://github.com/sabnzbd/sabnzbd/files/6349741/sonarr.trace.txt)

**Comment by Safihre** [comment] 2021-04-22 07:02
I can confirm that it was added once, but then for some reason added to the postprocessing queue 3 times.. Why, I don't know..

**Comment by Magikarplvl4** [comment] 2021-04-22 10:30
> I can confirm that it was added once, but then for some reason added to the postprocessing queue 3 times.. Why, I don't know..

Hi @Safihre ,

 I can provide the nzb file over the mail if you need it for reproducing the problem.
Is there something else i can provide to tackle this issue down?

**Comment by Safihre** [comment] 2021-04-22 10:41
Yes, maybe that helps: safihre@sabnzbd.org

**Comment by puzzledsab** [comment] 2021-04-22 10:42
I noticed that the first thing that happens 3 times is nzbqueue:776, which is the end_job method. A stack trace for that call might be helpful. I don't expect you to do that, @Magikarplvl4, but someone here can. Can you tell which indexer you got the nzb from? If not, @Safihre can forward it to me if he wants help.

**Comment by puzzledsab** [comment] 2021-04-22 10:52
Also, `caller_name()` returns N/A. That's not very helpful.

**Comment by Safihre** [comment] 2021-04-22 11:14
> Also, `caller_name()` returns N/A. That's not very helpful.

It does that when logging is set to Info, because calculating the caller takes cpu cycles.

Calling multiple times end_job shouldn't matter, because the first thing it does is check it the deleted flag is set.

**Comment by Magikarplvl4** [comment] 2021-04-22 11:18
> Yes, maybe that helps: [safihre@sabnzbd.org](mailto:safihre@sabnzbd.org)
Sended!

> I noticed that the first thing that happens 3 times is nzbqueue:776, which is the end_job method. A stack trace for that call might be helpful. I don't expect you to do that, @Magikarplvl4, but someone here can. Can you tell which indexer you got the nzb from? If not, @Safihre can forward it to me if he wants help.

Hi @puzzledsab, i provided the nzb file on the mail to  safihre.
according to Sonarr, the Indexer was NZBFinder.ws

**Comment by puzzledsab** [comment] 2021-04-22 12:38
> Calling multiple times end_job shouldn't matter, because the first thing it does is check it the deleted flag is set.

But then if everything was working as intended, this problem wouldn't have happened ;)

Actually, the first thing it does is call logging.info. Maybe it would help if `nzo.deleted = True` as done before that.

**Comment by Safihre** [comment] 2021-04-22 13:46
Wow something strange is going on.. This NZB got stuck at the end and then tripples itself 🙃 
![image](https://user-images.githubusercontent.com/5703454/115725100-d5eb2c00-a381-11eb-86bf-02dd02ad61e2.png)

**Comment by Safihre** [comment] 2021-04-22 14:37
I think it has to do with CRC errors, but haven't figured out what yet.
Other recent reports on the forums about stuck downloads also had CRC errors.

**Comment by puzzledsab** [comment] 2021-04-22 15:21
It downloaded successfully for me without tripling. I can't test it extensively right now because I'm downloading some other stuff. I got everything that downloaded successfully from the UsenetExpress backbone, with one missing and one bad article. Other differences are that I used my own fork (https://github.com/puzzledsab/sabnzbd/tree/feature/optimized) and had more stuff in the queue.

**Comment by Safihre** [comment] 2021-04-22 20:47
Closed by  a644579

**Closed by Safihre** 2021-04-22 20:47 UTC

**Comment by Magikarplvl4** [comment] 2021-04-22 20:59
@Safihre thanks for the fix and help 👍 . I will wait for the full stable release for the hotio docker in unraid
