### ISSUE TITLE
ENGINE Error in HTTPServer.tick

### ISSUE THREAD

**Issue by joostiphone** [sabnzbd/sabnzbd#1648] opened 2020-10-22 07:31 UTC
I'm getting the following error every day. Any idea how to solve this? 

```

 [22/Oct/2020:03:02:08] ENGINE Error in HTTPServer.tick

Traceback (most recent call last):
  File "cheroot\server.py", line 1788, in serve
  File "cheroot\server.py", line 2023, in tick
  File "cheroot\connections.py", line 188, in get_conn
  File "cheroot\connections.py", line 207, in _from_server_socket
  File "cheroot\ssl\builtin.py", line 277, in wrap
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1124)
```

**Comment by sanderjo** [comment] 2020-10-22 08:15
Is your SABnzbd reachable from Internet? If so: then it is caused by robots / scanners that try to access with an too low ssl version. 

If SAB only on your LAN, then one of your own services is doing that.

**Comment by joostiphone** [comment] 2020-10-22 09:32
SABnzbd is indeed reachable from internet. How can I ignore/suppress that error? Because, every time I receive that error, SABnzbd remote nzb uploading stops working (I can still reach it remotely though) and I need to restart SABnzbd to make it working again.

**Comment by sanderjo** [comment] 2020-10-22 12:37
First, easy step is to put SABnzbd (or at least the outside port of your router) on a unusual port, for example 29182. That way, the change that you get a robot / scanner, is 10.000x times smaller.

> Because, every time I receive that error, SABnzbd remote nzb uploading stops working (I can still reach it remotely though) and I need to restart SABnzbd to make it working again.

Oh, really? So the web interface is stil, working but NZB uploading not?

**Comment by thezoggy** [comment] 2020-10-22 18:52
can you share logs showing the full error? also what version of sab/etc. as its hard to make assumptions on what version of ssl or libs you have installed. we've switched form native ssl to pyopenssl and back, along with cherrpy code changes that can change how things are reported with sab's web. 

the error is just telling me your using outdated openssl/ssl. so server is using ssl3 instead of tls1.1+
which could be fixed by just updating pyopenssl / python

if your stuck just running outdated code/libs, you could do a reverse proxy to act as a gatekeeper (or use firewall)

**Closed** 2020-11-02 18:51 UTC
