### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by r3mko** [sabnzbd/sabnzbd#2895] opened 2024-06-26 09:15 UTC
### SABnzbd version

4.3.2 [8a42abd]

### Operating system

Linux / Debian 12.5

### Using Docker image

None

### Description

While downloading the following error is sometimes displayed and SABnzbd has to be restarted to continue downloading.
Happens with random nzb's.

> Traceback (most recent call last):
  File "/usr/local/bin/sabnzbd/sabnzbd/downloader.py", line 693, in process_nw_worker
    self.process_nw(read_fds[nw_queue.get()])
  File "/usr/local/bin/sabnzbd/sabnzbd/downloader.py", line 703, in process_nw
    bytes_received, end_of_line, article_done = nw.recv_chunk()
                                                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/sabnzbd/sabnzbd/newswrapper.py", line 207, in recv_chunk
    additional_bytes_recv, additional_end_of_line, additional_end_of_article = self.recv_chunk()
                                                                               ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/sabnzbd/sabnzbd/newswrapper.py", line 207, in recv_chunk
    additional_bytes_recv, additional_end_of_line, additional_end_of_article = self.recv_chunk()
                                                                               ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/sabnzbd/sabnzbd/newswrapper.py", line 207, in recv_chunk
    additional_bytes_recv, additional_end_of_line, additional_end_of_article = self.recv_chunk()
                                                                               ^^^^^^^^^^^^^^^^^
  [Previous line repeated 979 more times]
  File "/usr/local/bin/sabnzbd/sabnzbd/newswrapper.py", line 185, in recv_chunk
    self.nntp.nw.increase_data_buffer()
  File "/usr/local/bin/sabnzbd/sabnzbd/newswrapper.py", line 236, in increase_data_buffer
    logging.info("Increased buffer from %d to %d for %s", len(self.data), len(new_buffer), str(self))
  File "/usr/lib/python3.11/logging/__init__.py", line 2148, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 688, in format
    if self.usesTime():
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 656, in usesTime
    return self._style.usesTime()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 433, in usesTime
    return self._fmt.find(self.asctime_search) >= 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

If you need more info, let me know!

**Comment by mnightingale** [comment] 2024-06-26 12:30
Related to #2752, will need to figure out what is causing the repeated recursive call.

**Comment by Safihre** [comment] 2024-07-31 08:20
@r3mko What Python version is this?

**Comment by r3mko** [comment] 2024-07-31 08:21
Python 3.11.2

**Comment by sanderjo** [comment] 2024-07-31 10:03
> Happens with random nzb's.

But ... specific NZBs? So if you repeat such a NZB, it happens again?

**Comment by Safihre** [comment] 2024-07-31 10:47
Which providers do you use? Any special things in your connection? Like proxy or something?

**Comment by r3mko** [comment] 2024-07-31 11:21
> > Happens with random nzb's.
> 
> But ... specific NZBs? So if you repeat such a NZB, it happens again?

No, then it doesn't happen again.

**Comment by r3mko** [comment] 2024-07-31 11:43
> Which providers do you use? Any special things in your connection? Like proxy or something?

XS News, no proxy/nat or anything. Almost directly connected to the internet (just 1 hop from the router to the internet).
The only "special" thing is that the server is connected with 20Gbps (a bond of two 10Gbps).

**Comment by thezoggy** [comment] 2024-07-31 19:14
@r3mko have you tried upgrading in case it's a python bug

**Comment by r3mko** [comment] 2024-08-01 06:24
> @r3mko have you tried upgrading python in case it's a python bug..

I have the latest python available in the Debian bookworm repo:

> :~# apt policy python3-minimal
python3-minimal:
  Installed: 3.11.2-1+b1
  Candidate: 3.11.2-1+b1
  Version table:
 *** 3.11.2-1+b1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by r3mko** [comment] 2024-08-02 05:14
Collected some extra logging: https://pastebin.com/Rby0sTXb

**Comment by sanderjo** [comment] 2024-08-02 05:30
```
2024-08-02 05:45:21,034::INFO::[newswrapper:236] Increased buffer from 1638400 to 2048000 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>
2024-08-02 05:45:21,035::INFO::[newswrapper:236] Increased buffer from 2048000 to 2457600 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>
2024-08-02 05:45:21,037::INFO::[newswrapper:236] Increased buffer from 2457600 to 2867200 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>

...
2024-08-02 05:46:18,482::INFO::[newswrapper:236] Increased buffer from 412057600 to 412467200 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>
2024-08-02 05:46:18,595::INFO::[newswrapper:236] Increased buffer from 412467200 to 412876800 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>
2024-08-02 05:46:18,710::INFO::[newswrapper:236] Increased buffer from 412876800 to 413286400 for <NewsWrapper: server=reader.xsnews.nl:563, thread=68, connected=True>
2024-08-02 05:46:19,101::INFO::[notifier:157] Sending notification: Error - Fatal error in Downloader (type=error, job_cat=None)
2024-08-02 05:46:19,050::ERROR::[downloader:697] Fatal error in Downloader
Traceback (most recent call last):
```

Buffer size 413286400 ... that's 413.286.400, so 413 MB! Wow, I checked my logging, and never bigger than 1.2 MB.

So, again: does this happen with a specific NZB? Can you share that NZB?

**Comment by sanderjo** [comment] 2024-08-02 06:15
@Safihre @mnightingale why do we keep increasing the buffer size without any limit? Normal (article size) is 800 kB, 4MB does happen, but why go up to 413MB? What would happen when we set the limit at 10MB or 20MB, and if the buffer / article reaches that, mark the articles as bad / not available?

```
    def increase_data_buffer(self):
        """Resize the buffer in the extremely unlikely case that it overflows"""
        # Input needs to be integer, floats don't work
        new_buffer = sabctools.bytearray_malloc(len(self.data) + NNTP_BUFFER_SIZE // 2)
        new_buffer[: len(self.data)] = self.data
        logging.info("Increased buffer from %d to %d for %s", len(self.data), len(new_buffer), str(self))
        self.data = new_buffer
        self.data_view = memoryview(self.data)

```

**Comment by sanderjo** [comment] 2024-08-02 06:17
> > > Happens with random nzb's.
> > 
> > 
> > But ... specific NZBs? So if you repeat such a NZB, it happens again?
> 
> No, then it doesn't happen again.

So does it happen randomly, across different NZBs? Or certain NZBs from certain sources? 

Do you have more than one newsserver, so something else than reader.xsnews.nl? Does it happen if you only use that other newsserver (and not reader.xsnews.nl)?

**Comment by sanderjo** [comment] 2024-08-02 06:21
> The only "special" thing is that the server is connected with 20Gbps (a bond of two 10Gbps).

"server" ... at home on your LAN / home connection, or in a datacenter, cloud, VPS, etc?

Does it still happen if you only use one 10Gbps link?

**Comment by r3mko** [comment] 2024-08-02 07:13
> > > > Happens with random nzb's.
> > > 
> > > 
> > > But ... specific NZBs? So if you repeat such a NZB, it happens again?
> > 
> > 
> > No, then it doesn't happen again.
> 
> So does it happen randomly, across different NZBs? Or certain NZBs from certain sources?
> 
> Do you have more than one newsserver, so something else than reader.xsnews.nl? Does it happen if you only use that other newsserver (and not reader.xsnews.nl)?

It seems to happen randomly with different NZB's from different sources. But the NZB [1] that triggered the logging that I include above, now doesn't want to download at all and gets paused bij Sab and the web interface reloads when I try and start it again ("Lost connection to ...").

[1] https://uploadnow.io/f/2yShKFf

At the moment I only have access to XS News.

**Comment by r3mko** [comment] 2024-08-02 07:18
> > The only "special" thing is that the server is connected with 20Gbps (a bond of two 10Gbps).
> 
> "server" ... at home on your LAN / home connection, or in a datacenter, cloud, VPS, etc?
> 
> Does it still happen if you only use one 10Gbps link?

It is locate in a datacenter and is a bare metal server.

I haven't tried just one link, will have to try it when I get the chance.

**Comment by sanderjo** [comment] 2024-08-02 07:54
Thanks for the NZB. On my system, SAB does say `Failed to import 2 files from 77537273.nzb`, and indeed the NZB has empty stuff in there. But SAB detects that, and I would say that can't be the problem. And the NZB download succesfully on my system

```
$ cat .sabnzbd/logs/sabnzbd.log | grep  -i -e "error importing" -e "failed to import" 
2024-08-02 09:20:26,942::INFO::[nzbparser:475] Error importing (Spotjes) [82/98] - "Best.of.bbb-Disk1.part81.rar" yEnc: Bests.of.bbb-Disk1 (001/127), skipping
2024-08-02 09:20:26,976::INFO::[nzbparser:475] Error importing (Spotjes) [92/98] - "Best.of.bbb-Disk1.vol067+26.PAR2" yEnc: Bests.of.bbb-Disk1 (001/131), skipping
2024-08-02 09:20:27,006::INFO::[notifier:157] Sending notification: Warning - Failed to import 2 files from 77537273.nzb (type=warning, job_cat=None)
2024-08-02 09:20:27,005::WARNING::[nzbparser:488] Failed to import 2 files from 77537273.nzb
```


> now doesn't want to download at all and gets paused bij Sab and the web interface reloads when I try and start it again ("Lost connection to ...").

Oh. That means network problems.

**Comment by r3mko** [comment] 2024-08-02 08:37
> 
> Oh. That means network problems.

But if I keep that NZB paused, the rest of the NZB's in the queue keep downloaden without a problem. It's just when I resume that particular NZB the connection is lost for a second and the interface comes back. So maybe not network related?

**Comment by Safihre** [comment] 2024-08-02 11:16
It must be in a crash loop.
Seems bad article caused by bad nzb or by bad usenet host.
We should indeed just have a safety net to stop the increase.

**Comment by sanderjo** [comment] 2024-08-02 20:05
> Curious to see if xsnews has really stored a 400MB article, 

My guess: no.


> and if not how it has seemingly read so much from a socket.

My guess: TCP packets not acknowlegded by the client side (maybe because of the dual 10GigE-setup of the OP), so the server sends it again, and SABnzbd slurps it up and adds it to the buffer? Note: I do not know if TCP packet numbering protects against this ... so just a guess.
Maybe I can simulate that with nserv and the Linux random-packet-loss emulator https://www.pico.net/kb/how-can-i-simulate-delayed-and-dropped-packets-in-linux/#:~:text=Randomly%20drop%20approximately%20one%20percent%20of%20packets%20transmitted%20on%20eth1%3A

Anyway: Back to my remark "why do we keep increasing the buffer size without any limit? ...  What would happen when we set the limit at 10MB or 20MB": we already know the article size beforehand (as it's in the NZB), so why allow much more at all? Why not allow a maximum of 150% or 200% of the stated article size? 

Or too lazy method: find biggest article size in the NZB, and use 150% or 200% of that as max to read for any article in that NZB? For the NZB given by OP: 397214 is the max article, so use 800.000 as max?

```
$ cat 77537273.nzb  | grep "segment bytes" | awk -F\" '{ print $2 }'  | sort -rn | head -1
397214
```

**Comment by sanderjo** [comment] 2024-08-04 20:55
Ah, good news: with nzbget's nserv I'm able to reproduce the problem:

Create a 1GB file in the nserv data dir, create a .NZB for it (with article size 555000 bytes), and then hack that .NZB so it contains this:

![image](https://github.com/user-attachments/assets/e491bbe6-cabd-4b78-848f-8a0ce2e12a84)

... which will result in nserv to send the file part from 4995000 to 1000111000, so almost 1GB, well above our 400MB limit.

Now let SABnzbd get that .NZB ... and bingo: the recursion traceback at the 400MB limit. Good.

```
2024-08-04 22:27:09,233::INFO::[newswrapper:236] Increased buffer from 401817600 to 402227200 for <NewsWrapper: server=[127.0.0.1:6791](http://127.0.0.1:6791/), thread=3, connected=True>
2024-08-04 22:27:09,388::INFO::[newswrapper:236] Increased buffer from 402227200 to 402636800 for <NewsWrapper: server=[127.0.0.1:6791](http://127.0.0.1:6791/), thread=3, connected=True>
2024-08-04 22:27:09,546::INFO::[notifier:157] Sending notification: Error - Fatal error in Downloader (type=error, job_cat=None)
2024-08-04 22:27:09,539::ERROR::[downloader:697] Fatal error in Downloader
Traceback (most recent call last):
...
RecursionError: maximum recursion depth exceeded while calling a Python object
```


Then I changed newswrapper.py to have a limit of 20MB on the article buffer:

    def recv_chunk(self) -> Tuple[int, bool, bool]:
        """Receive data, return #bytes, end-of-line, end-of-article"""
        # Resize the buffer in the extremely unlikely case that it got full
        if self.data_position == len(self.data):
            if self.data_position < 20_000_000:
                self.nntp.nw.increase_data_buffer()
            else:
                # that is really too much, so stop this article
                logging.debug(f"SJ: ... too much data: {self.data_position} bytes in one article")
                raise ConnectionError("SJ: Article too big")

... and that works: the faulty article is halted

```
2024-08-04 22:40:48,588::INFO::[newswrapper:241] Increased buffer from 18432000 to 18841600 for <NewsWrapper: server=127.0.0.1:6791, thread=3, connected=True>
2024-08-04 22:40:48,592::INFO::[newswrapper:241] Increased buffer from 18841600 to 19251200 for <NewsWrapper: server=127.0.0.1:6791, thread=3, connected=True>
2024-08-04 22:40:48,596::INFO::[newswrapper:241] Increased buffer from 19251200 to 19660800 for <NewsWrapper: server=127.0.0.1:6791, thread=3, connected=True>
2024-08-04 22:40:48,601::INFO::[newswrapper:241] Increased buffer from 19660800 to 20070400 for <NewsWrapper: server=127.0.0.1:6791, thread=3, connected=True>
2024-08-04 22:40:48,601::DEBUG::[newswrapper:189] SJ: ... too much data: 20070400 bytes in one article
2024-08-04 22:40:48,601::DEBUG::[downloader:943] Thread 3@127.0.0.1: Server closed connection
2024-08-04 22:40:48,601::INFO::[nzbstuff:255] Article 1G.bin?10=4995000:1000111000 unavailable on all servers, discarding
2024-08-04 22:40:48,602::DEBUG::[nzbstuff:1508] Availability ratio=99.95, bad articles=0, total bytes=1073925000, missing bytes=555000, par2 bytes=0
2024-08-04 22:40:48,624::DEBUG::[assembler:80] Decoding part of /home/sander/git/sabnzbd/Downloads/incomplete/big_article_1G.bin/1G.bin
2024-08-04 22:40:48,827::DEBUG::[assembler:80] Decoding part of /home/sander/git/sabnzbd/Downloads/incomplete/big_article_1G.bin/1G.bin
2024-08-04 22:40:49,035::DEBUG::[assembler:80] Decoding part of /home/sander/git/sabnzbd/Downloads/incomplete/big_article_1G.bin/1G.bin

``` 
... and the download continues. No more recursion traceback. Nice.

However: after completing the download, there is a pickle traceback ... I don't know why

```
2024-08-04 22:40:54,296::ERROR::[filesystem:1148] Saving /home/sander/git/sabnzbd/Downloads/incomplete/big_article_1G.bin/__ADMIN__/SABnzbd_nzo_30xu8xx6 failed
2024-08-04 22:40:54,296::INFO::[filesystem:1149] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/filesystem.py", line 1139, in save_data
    pickle.dump(data, data_file, protocol=pickle.HIGHEST_PROTOCOL)
RuntimeError: set changed size during iteration
```
So my hack is not enough?

**Comment by mnightingale** [comment] 2024-08-05 12:40
Maybe the dual 10G bond could be the cause, @r3mko perhaps test without the bond or just active/backup?

I don't think retransmitted packets could cause the symptoms; decoding TLS would be broken so I’m at a loss to how that could happen, maybe it is reading for a different socket or a reused file descriptor but I think it's beyond the scope of SAB anyway.

The nzb segment bytes I believe are the decoded data size rather than the encoded size plus any headers/metadata. It could still work with a limit based on that but it’s still open to issues (purposely badly formatted nzbs resulting in high memory allocation = crashes), so I’d be in favour of a hard limit such as 20MB.

Enforcing that limit, means you’d have to discard until EOF (\r\n\.\r\n) or restart the connection.
Reading to EOF might not even work, this issue has read 400MB so who knows if it would ever stop.
Raising raising a ConnectionError or create own which results in a `__reset_nw` call is the way to go.
May also need to take care of the suspect article, trying it again may result in the same thing so maybe it needs marking as bad/failed.

The problem with your approach of `return self.data_position, True, True` is you’ve read 20MB, then ignoring the rest leaving the connection in an undefined state. So, it will request the next article and still be reading the response to the previous request.

I’m not sure about the pickle error, there was an article in the cache but maybe it has already been removed, it doesn’t lock and just tries a few times. I’m not sure this is related.

**Comment by sanderjo** [comment] 2024-08-05 21:16
@Safihre @mnightingale this is too difficult for me. So can you help / test / code? I've set up a nserv newsserver against which you can test with SABnzbd as client:

newsserver: www.appelboor.com, port 6791, with SSL, but disable  certificate checking (I'm too lazy to set up correct certificates)

NZB with 800MB article: https://raw.githubusercontent.com/sanderjo/NZBs/master/1G_toobigarticle.bin.nzb

That combination will create the recursion traceback.

![image](https://github.com/user-attachments/assets/b4981517-8e39-428f-b2a9-f11b45665e32)

testing the connection should work:

![image](https://github.com/user-attachments/assets/56b94ee3-3827-4bfd-8493-a3d941b4c5eb)

**Comment by r3mko** [comment] 2024-08-07 08:09
> Maybe the dual 10G bond could be the cause, @r3mko perhaps test without the bond or just active/backup?
> 

Sorry for the late reply. Finally had time to test it, but the behaviour is unfortunately the same as before.

**Comment by sanderjo** [comment] 2024-08-09 05:18
@r3mko 

Does it still happen with your downloads?
If you: Are you interested in appyling a workaround (the patch I created) until a real fix is released?

**Comment by r3mko** [comment] 2024-08-09 09:13
@sanderjo 

Thanks for offering! But it's not that urgent, I'll wait for the final fix.

**Closed** 2024-08-16 15:26 UTC
Labels: Bug

**Comment by Safihre** [comment] 2024-08-16 15:27
I implemented a limit at 10MB and tested with @sanderjo's NZB. 
@r3mko You can try the build here: https://github.com/sabnzbd/sabnzbd/actions/runs/10422350393

**Comment by sanderjo** [comment] 2024-08-16 16:13
Nice! I tested as I described in https://github.com/sabnzbd/sabnzbd/issues/2895#issuecomment-2269933959 ... and it works. Cool, cool, cool.



![image](https://github.com/user-attachments/assets/19933aea-bb2b-4833-b357-60d936bb9bed)

![image](https://github.com/user-attachments/assets/0179dea6-75a1-4709-bd1e-7e8f46fc723c)

```
2024-08-16 18:07:38,115::INFO::[newswrapper:240] Increased buffer from 9420800 to 9830400 for <NewsWrapper: server=www.appelboor.com:6791, thread=8, connected=True>
2024-08-16 18:07:38,171::INFO::[newswrapper:240] Increased buffer from 9830400 to 10240000 for <NewsWrapper: server=www.appelboor.com:6791, thread=8, connected=True>
2024-08-16 18:07:38,202::INFO::[newswrapper:240] Increased buffer from 10240000 to 10649600 for <NewsWrapper: server=www.appelboor.com:6791, thread=8, connected=True>
2024-08-16 18:07:38,285::DEBUG::[downloader:948] Thread 8@www.appelboor.com: Maximum data buffer size exceeded
2024-08-16 18:07:38,285::INFO::[nzbstuff:255] Article 1G.bin?6=2500000:800111000 unavailable on all servers, discarding
2024-08-16 18:07:38,285::DEBUG::[nzbstuff:1508] Availability ratio=99.95, bad articles=0, total bytes=1074000000, missing bytes=500000, par2 bytes=0
```

The download succeeds, which is a bit weird, as an article is missing and there are no par2's, but I guess IRL SAB's unrar and par2 will take care of that.

**Comment by r3mko** [comment] 2024-08-20 11:42
> I implemented a limit at 10MB and tested with @sanderjo's NZB. @r3mko You can try the build here: https://github.com/sabnzbd/sabnzbd/actions/runs/10422350393

Works here as well. Thank you!
