### ISSUE TITLE
SABnzbd is unusable with a very large queue

### ISSUE THREAD

**Issue by untotren** [sabnzbd/sabnzbd#550] opened 2016-04-17 22:33 UTC
I go through Sickbeard and backlog all my shows, a few thousand episodes.  And all these shows add to sab, then after they add SABNZBD starts to fall apart, lag itself into oblivion so I can not interface with the UI at all.

**Comment by jeffgeorge** [comment] 2016-04-17 22:57
1. **How many jobs are you trying to cram into SABnzbd simultaneously?** We can't try to diagnose this until we know the scale we're talking about.

1. **How are these jobs being added?** Is SABnzbd having to request the NZB over HTTP, or is the full NZB payload being provided as part of the original call? This will help us determine if more of the issue is before or after ingesting the NZB.

1. **What hardware / OS are you running SABnzbd on?** Disk and CPU info will be especially helpful here, as the bottleneck will likely be one or the other. If you can tell where the bottleneck is, that would be _even more helpful_.

1. **Is there any difference in performance if you try and do all this with SABnzbd paused?** It could be that part of what's freaking out is constantly shifting what jobs are loaded into memory for processing.

1. **Does *any* Usenet client perform to your standards under this kind of load?** It could be that what you're attempting to do is just completely out of bounds of reasonable operation, and is thereby not our fault.

**Comment by shypike** [comment] 2016-04-18 12:45
SABnzbd has issues with extremely large queues.
This is not an issue for most users, but in extreme cases SABnzbd should at least degrade gracefully. Currently it does not. We must try to fix this somehow.

**Comment by thezoggy** [comment] 2016-04-18 17:49
why the hell do you have thousands of episodes in your sickbeard backlog...

**Comment by labrys** [comment] 2016-04-27 11:07
@jeffgeorge As I have this issue (although it has improved significantly) I'd like to answer your questions for my case.

* **1. Jobs:** regularly > 1000-2000 jobs
* **2. Add Method:** HTTP, not full payload, from [Medusa](https://github.com/pymedusa/sickrage) (a sickrage/sickbeard fork)
* **3. Hardware:**
 * 6-Core AMD Phenom II X6 1100T Black Edition at 3.7GHz
 * Samsung 840 pro SSD
 * 32 GB RAM
* **4. Paused performance**:
 * Some increase in performance but still unusable with really large queues
 * Worst offender for performance has been mostly resolved (UI used to crash with lots of jobs and no display limit)
 * Lots of NZBs in queue that have not been resolved into a payload can cause the queue to stop resolving
* **5. Other clients:**  While I have used others, SAB has been my go-to for a really long time and I haven't pushed the others to this extreme so I can't provide better data.

I have significantly throttled the number of NZBs pushed to SAB to avoid these issues but it requires manually setting items in Medusa to skipped and periodically changing small batches to wanted which greatly reduces the automation provided.

**Comment by Safihre** [comment] 2016-04-27 11:12
@labrys, are you running from source? We updated the develop branch last week with some major speed improvements to the API. Haven't tested 1000-2000, but 900 worked well. We also fixed the freezing on pausing.

**Comment by labrys** [comment] 2016-04-27 11:19
@Safihre Yes I'm running from source, and yes I'm running the latest (i usually update every day or two).  However I have been intentionally keeping the number of requests really low lately and haven't pushed it with the latest updates.  If you would like I can slam it with everything I've got and let you know how it performs.

**Comment by Safihre** [comment] 2016-04-27 12:59
Well maybe give it a try? At least the interface shouldn't crash or slow to a standstill. Can't promise it will continue to resolve all URLs (since you mentioned sometimes problems there), we didn't change anything there. 

As a side question: when do you have time to watch all that? :P

**Comment by labrys** [comment] 2016-04-27 13:34
Hehe, a lot of it is I like to archive really old tv shows that may be difficult or impossible to find otherwise.  A lot of which I have already seen in the past.  Also I always have something playing in the background as whitenoise so its nice to have variety.

**Comment by labrys** [comment] 2016-04-29 04:59
It's been chugging along pretty good with about 1500 currently.  Not all have resolved yet (due to API limits, not SAB) but it looks like its proceeding as expected.  If it continues to perform well I'll add some more and see how it does.  I still have to have the display limit set, but that's pretty much expected.

**Comment by labrys** [comment] 2016-04-30 21:37
Performance has been holding steady with about 2k shows.

**Comment by labrys** [comment] 2016-05-13 16:11
Been running with about 2k shows for 2 weeks now and have had no issues as long as I limit the items per page.  I will throttle up and see how it performs with even more downloads.

**Comment by Safihre** [comment] 2016-05-14 16:52
Great! Yes, at some point also Glitter is slowing things down when actually showing all those items.

**Comment by thezoggy** [comment] 2016-05-20 22:57
@Safihre fyi, http://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/

**Comment by labrys** [comment] 2016-05-20 23:50
@Safihre I use plush almost exclusively.  I also modify the items per page to 1000 and still get great performance with plush.

**Comment by Safihre** [comment] 2016-05-31 10:43
@shypike I think this one can have a label Fixed now and get closed? We did all we could in terms of API performance :)

**Closed** 2016-05-31 10:44 UTC
Labels: 1 - Confirmed, 3 - Fixed

**Comment by efhunter31** [comment] 2017-04-07 19:12
@labrys How do I modify the number of items per page? I googled and ended up here.

**Comment by Safihre** [comment] 2017-04-07 19:23
Click on the little wrench icon in the menu bar, then click on Interface settings. 

This info is also in the Glitter tips and tricks that's linked when you first start.
