### ISSUE TITLE
Web interface settings often change spontaneously

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#2012] opened 2022-01-01 03:11 UTC
I have SABnzbd running on a separate Windows 10 PC with the glitter - night interface.
Often when I try to access it from another PC, the display mode settings are changed from what I had set before. 
I normally have "Always use full screen width" and "Tabbed layout" set. But often these settings are changed spontaneously when I view the interface. This change happens only when I initially start up the webbrowser and connect to SABnzbd. Never later.

Just now it happened again. The below lines are from the log and it shows initially the settings 
"displayFullWidth":true,"displayTabbed":true (which is as I had configured it) but a few miliseconds later, the log shows that 
SABnzbd has changed it on it's own to "displayFullWidth":false" and it dropped the "displayTabbed":true" setting. 
To recover, I have to go to the spanner menu option - web interface setting and tick the options again. 

The following is the extract from the log file:
```
2022-01-01 03:26:17,043::DEBUG::[interface:130] Request GET /api from 192.168.1.3 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] {'mode': 'set_config', 'section': 'misc', 'keyword': 'interface_settings', 'value': '{"dateFormat":"fromNow","extraQueueColumns":["category"],"extraHistoryColumns":["category"],"displayCompact":false,"displayFullWidth":true,"displayTabbed":true,"confirmDeleteQueue":true,"confirmDeleteHistory":true}', 'output': 'json', 'apikey':<APIKEY>', '_': '1641003976499'}
2022-01-01 03:26:17,050::INFO::[config:908] Writing settings to INI file \\?\C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini
2022-01-01 03:26:17,057::DEBUG::[interface:130] Request GET /api from 192.168.1.3 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] {'mode': 'set_config', 'section': 'misc', 'keyword': 'interface_settings', 'value': '{"dateFormat":"fromNow","extraQueueColumns":["category"],"extraHistoryColumns":["category"],"displayCompact":false,"displayFullWidth":true,"displayTabbed":true,"confirmDeleteQueue":true,"confirmDeleteHistory":true}', 'output': 'json', 'apikey':<APIKEY>', '_': '1641003976500'}
2022-01-01 03:26:17,063::DEBUG::[interface:130] Request GET /api from 192.168.1.3 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] {'mode': 'set_config', 'section': 'misc', 'keyword': 'interface_settings', 'value': '{"dateFormat":"fromNow","extraQueueColumns":["category"],"extraHistoryColumns":["category"],"displayCompact":false,"displayFullWidth":false,"displayTabbed":true,"confirmDeleteQueue":true,"confirmDeleteHistory":true}', 'output': 'json', 'apikey':<APIKEY>', '_': '1641003976501'}
2022-01-01 03:26:17,064::DEBUG::[interface:130] Request GET /api from 192.168.1.3 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] {'mode': 'set_config', 'section': 'misc', 'keyword': 'interface_settings', 'value': '{"dateFormat":"fromNow","extraQueueColumns":["category"],"extraHistoryColumns":["category"],"displayCompact":false,"displayFullWidth":false,"confirmDeleteQueue":true,"confirmDeleteHistory":true}', 'output': 'json', 'apikey':<APIKEY>', '_': '1641003976502'}
2022-01-01 03:26:17,067::DEBUG::[interface:130] Request GET /api from 192.168.1.3 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] {'mode': 'status', 'calculate_performance': '0', 'skip_dashboard': '1', 'output': 'json', 'apikey':<APIKEY>', '_': '1641003976503'}
2022-01-01 03:26:17,070::INFO::[config:908] Writing settings to INI file \\?\C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini

```

**Comment by thezoggy** [comment] 2022-01-01 04:28
The gui Settings are stored in a cookie within the browser you are using.

**Comment by Safihre** [comment] 2022-01-01 07:37
I can confirm also seeing this, but not really being able to reproduce it very well..

**Comment by ErikBrown2** [comment] 2022-01-01 11:44
> The gui Settings are stored in a cookie within the browser you are using. Uncheck the "use global interface settings" when setting the web settings if you want each browser to have its own cookie/settings.
> 
> #1475

I have Firefox configured to remove all cookies at program exit. I have now put an exception in Firefox for SABnzbd so that it will keep the SABnzbd cookies to see if that solves the issue. I do have the "use global interface settings" set.

**Comment by jcfp** [comment] 2022-01-03 10:35
> I can confirm also seeing this, but not really being able to reproduce it very well..

Same here. Been seeing this for a while, but always assumed it was a side effect of my strict privacy and cookie settings. Sometimes it works even after a browser restart or system reboot, only to revert to default settings at some seemingly random moment.

**Comment by thezoggy** [comment] 2022-01-03 16:09
Odd, I've never seen this myself. I mainly use Firefox. What browsers and any ad blocker installed with it?

**Comment by ErikBrown2** [comment] 2022-01-03 16:19
I use mostly Firefox. I use now Adblock but it also happened before I started using an add blocker.

**Comment by Safihre** [comment] 2022-01-04 07:32
@puzzledsab maybe you can look into this?

**Comment by puzzledsab** [comment] 2022-01-04 11:11
I've been using vanilla MS Edge with Sab for a while (except that it clears all browser data for everything except localhost when I close it). I can't remember having seen this problem with my current setup. I think I may have seen it while I was using Firefox with various privacy addons but it's difficult to be sure because I'm frequently messing with the config.

**Comment by ErikBrown2** [comment] 2022-01-07 11:15
When SABnzbd does not show the interface in tabbed mode while it should, then Firefox reports the cookie setting for it as 'undefined'. The setting for it in sabnzbd.ini file stays correct with "displayTabbed":true".



<img width="958" alt="Screenshot 2022-01-07 120402" src="https://user-images.githubusercontent.com/32511867/148535947-2b67a8a8-9ba8-45a3-9c0d-229b3e000010.png">

**Comment by puzzledsab** [comment] 2022-01-07 15:15
Possibly some kind of obscure bug that only triggers once in a while and only with Firefox? Could be Knockout related.

First thing that would be useful to know is if it's losing all modified cookies or only specific ones. Could you make some more cookie changes and see if they are lost too if it happens again? Changing the date format, one of the extra columns and another checkbox would be nice as they are all different variable formats.

**Comment by ErikBrown2** [comment] 2022-01-08 09:42
It just happened again and the following shows the default values, my initial settings and the settings after the error of the parameters as seen on the spanner menu item - Status and interface options. Only the 'Tabbed layout' setting was changed. 

<img width="556" alt="Screenshot 2022-01-08 104025" src="https://user-images.githubusercontent.com/32511867/148639608-669a5fc5-c332-447f-a0f8-4524f9e3fe6a.png">

**Comment by thezoggy** [comment] 2022-01-08 18:44
you have other webapps running?, maybe there is just a local cookie collision thats happening? since they would all be on the same 'domain'

**Comment by puzzledsab** [comment] 2022-01-08 20:55
I think it's related to the Knockout code. I would be surprised if there is other software that uses both displayFullWidth and displayTabbed as cookie names. If displayCompact can be lost too then that would support the suspicion because it's handled in exactly the same way as the other two. It could still be Knockout if all the variables can be lost but that would make it harder to narrow down.

**Comment by ErikBrown2** [comment] 2022-01-08 22:07
> you have other webapps running?, maybe there is just a local cookie collision thats happening? since they would all be on the same 'domain' (or multiple sab instances)

I do have the Ubiquiti Unify controller software running on the same PC. I will stop it and remove it's cookies to see if that has any positive effect.

**Comment by Safihre** [comment] 2022-01-10 13:58
Hmm strange, when I open SABnzbd in Incognito window (so "fresh") it randomly switches to tabbed-mode even though that's not even set in my `sabnzbd.ini`.
Additionally, I always see 2 requests to `set_config` when opening the page. Even though nothing changed.
Clearly some knockoutJS nonsense. Have to investigate a bit more.

**Comment by Safihre** [comment] 2022-01-10 18:56
Wonder why nobody reported this untill now, clearly it isn't working for a while 😅

**Comment by Safihre** [comment] 2022-01-11 10:20
I moved some code around, let's see if this helps.
Feel free to comment/reopen if this change doesn't help!

**Closed** 2022-01-11 10:20 UTC
Labels: Bug

**Comment by jcfp** [comment] 2022-01-14 09:47
> I moved some code around, let's see if this helps.

Installed the patched code 3 days ago, and the interface setting has remained as configured since then. Looks like you nailed it.

**Comment by ErikBrown2** [comment] 2022-01-16 01:55
> > I moved some code around, let's see if this helps.
> 
> Installed the patched code 3 days ago, and the interface setting has remained as configured since then. Looks like you nailed it.

I agree. It appears to have been fixed.
