### ISSUE TITLE
sab 0.8.x -- config > test server

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#430] opened 2016-01-17 17:09 UTC
badly worded response on test for server that doesnt support the passed tls type..
example with astraweb with TLSv1.2: `[Errno 10061] Failed to connect: This server does not allow SSL on this port -1@ssl-eu.astraweb.com:563`
If you use TLSv1 it works fine...

thus the comment from sab `Use the top value, unless your Usenet provider requires otherwise!` could cause people to waste some time

**Comment by thezoggy** [comment] 2016-01-17 17:11
also on the 0.7.x to 0.8.x upgrade.. it changed the TLS values for my servers..which broke astraweb.

**Comment by thezoggy** [comment] 2016-01-17 17:14
tls 1.2 works fine for my other 5 providers at least

**Comment by shypike** [comment] 2016-01-18 07:37
The default is to use the h\ighest avaibale protocol.
Include an extra test for Astraweb (given its popularity) and downscale?
Changing the error message may be better, but that would again invalidate translations :(
"This server either doesn't allow SSL or you should chose a different SSL protocol in Config->Servers"
A bit long winded...

**Comment by Safihre** [comment] 2016-01-18 08:10
Instead of exception for Astraweb, maybe just try v1 on this error? I know it would be an extra request, but that doesn't sound too bad? 
Is there no way to request the supported protocols from the server? (@sanderjo)

**Comment by sanderjo** [comment] 2016-01-18 08:23
I use tesssl.sh to test which SSL/TLS version are supported by a server:


```
sander@haring:~/git/testssl.sh$ ./testssl.sh ssl-eu.astraweb.com:563

 Testing protocols (via sockets except TLS 1.2 and SPDY/HTTP2)
<snip>

 SSLv2      offered (NOT ok) -- 7 ciphers
 SSLv3      offered (NOT ok)
 TLS 1      offered
 TLS 1.1    not offered
 TLS 1.2    not offered (NOT ok)
 SPDY/NPN   not offered
 HTTP2/ALPN not offered
```

I think it's not too hard to let python / SAB check the protocol. I'll check tonight.

**Comment by shypike** [comment] 2016-01-18 08:49
@sanderjo What is the conclusion of the little report? Only use TLS1? What does "NOT ok" mean here?

**Comment by sanderjo** [comment] 2016-01-18 09:03
Yes, only use TLS1; the best available.

It is "NOT ok" to offer the old, unsafe protocols SSLv2 and SSLv3

**Comment by shypike** [comment] 2016-01-18 09:34
@sanderjo But why does it say "Not OK" for TLS1.2?
Is TLS 1.2 unsafe too?

**Comment by sanderjo** [comment] 2016-01-18 09:35
FWIW: Astraweb doesn't look very SSL/TLS minded: even https://www.news.astraweb.com/ itself is untrusted by Chrome, FF and IE: ssl_error_bad_cert_domain

**Comment by sanderjo** [comment] 2016-01-18 09:37
> @sanderjo But why does it say "Not OK" for TLS1.2?
> Is TLS 1.2 unsafe too?

No; it's not OK because it's not offered at all:
```
TLS 1.2    not offered (NOT ok)
```

**Comment by thezoggy** [comment] 2016-01-18 13:51
is there any usp that dont work with TLS? could possibly just drop SSL or show warning if selected that it most likely is insecure and your wasting cpu cycles.

personally i view TLS 1 is the 'standard', so yes try 1.2 but then fall back to 1.0 if you worried about breaking stuff without the user knowing.

now to do this properly I say we put a button next to the ssl dropdown where once clicked it just tries from the top down of choices and will use the first one that is okay. thus most likely it only has to do a few request (tls 1.2 -> tls 1.1 -> tls 1) before it is happy. 

now what about false positives.. will the ssl/tls response change if the users account is out of credits/disabled/badly entered?

**Comment by sanderjo** [comment] 2016-01-18 14:30
I would say: no button. Like there is no button in Chrome/FF/IE "which SSL/TLS protocol would you like to use for this site?". Let SABnzbd take care of that just like Chrome/FF/IE: start with the most safe protocol (currently TLS 1.2), and if not possible (server or client side), fall back to a less safe protocol.

**Comment by Safihre** [comment] 2016-01-18 15:01
But when? On server-connect for each thread? Seems to time-consuming.
Or on save of the server? Do we show a message to the user and when?
Also need to consider the upgrade-case that the correct level is chosen.

**Comment by sanderjo** [comment] 2016-01-18 15:04
> But when? On server-connect for each thread? Seems to time-consuming.

Chrome/FF/IE do it for each HTTPS connection, so I guess it's not too time consuming.

**Comment by thezoggy** [comment] 2016-01-18 15:40
realistically no one even bothers with this field until its not working. and most wont know how/what to set. i see no reason to add even more complexity to sab's downloader for this.. its usually a set and forget -- which i'm suggesting we make it smarter to 'set' by just testing from top down and stopping on the newest/best option. the only reason its coming up now is because sab broke for me after the upgrade.

the reason a browser is going to test for each site is well.. each site is different.. it's not like your sab servers are changing daily.. hell even yearly.

**Comment by Safihre** [comment] 2016-01-18 15:44
Agreed, so when clicking on Test,  Save and on upgrade. In the response we could let them know if we switched it on their behalf.

**Comment by sanderjo** [comment] 2016-01-18 16:05
So, let's see if we agree based on this use case:
1) User has astraweb, supporting up to TLS1
2) SAB locks in on TLS1
3) Astraweb introduces TLS1.1 and TLS1.2. SAB keeps using TLS1 ... correct?
4) Astraweb phases out SSL and TLS1. What happens to SAB?

**Comment by thezoggy** [comment] 2016-01-18 16:30
better use case:
1) user has astraweb already in sab in 0.7.x and upgrades
2) user goes to add astraweb in sab 0.8.x

either case, we try our list top down (1.2->1.1->1.0->ssl..etc).. and set the first one that returns okay.. so in case of astraweb today.. we end up with tls 1.0. a year from now.. it could be tls 1.2 or whatever our top value is then. make sense?

**Comment by sanderjo** [comment] 2016-01-18 16:38
@thezoggy Do you mean SAB does that automatically, or the user sometimes has to trigger that process manually?

**Comment by thezoggy** [comment] 2016-01-18 16:52
the routine should be written, so that the user can manually trigger (test+set) on the server page when adding. but sab should auto do it during the upgrade. 

we dont want to go down the path of sab knows better than the user without giving the user the ability to override.. but we also want to help the user out from making mistakes/guide them. thus this should cover both scenarios pretty easily.

**Comment by sanderjo** [comment] 2016-01-18 17:08
So: automatically, or manually? Or both? Or more options?

We cleaned up the Wizard very much ... to avoid confusion for normal users.
I really don't think normal users know or want to know about TLS version xyz, etc.
So I think that SAB should take care of it, just like webbrowsers do.

**Comment by Safihre** [comment] 2016-01-18 17:16
The feature of selecting the level was only recently introduced, what happened in the old versions? How did it pick the level there?

**Comment by shypike** [comment] 2016-01-18 17:46
In previous releases it stuck to what you set, defaulting to V23, system-wide.
For 0.8.0, I propose to default to TLS1, the user can pick another value if he/she wants to.
Later we can make it more sophisticated.

**Comment by thezoggy** [comment] 2016-01-18 18:51
im cool with defaulting to tls1 for now.. @sanderjo what is the real world benefits of tls 1 vs 1.2 for sab... speed/security/etc.  also tls 1.2 -- issues with python 2.x?

**Comment by Safihre** [comment] 2016-01-18 19:14
Okay question from a SSL-noob here, but in NZBGet you can specify a cipher and they suggest 'RC-MD5' (https://github.com/nzbget/nzbget/wiki/Choosing-cipher). Not exactly sure if thats SSL or TLS, but there's also some tables about all the relative speeds of each cipher combination (and how to run the tests on your own PC).
He concludes:
> Now test the download speed in NZBGet. On my SAT Receiver Vu+ choosing cipher "RC4-MD5" has increased the speed from 2500KB/s to 3800KB/s. Not bad, isn't it?

Shouldn't we also consider the performance? 
Can we in Python even select the specific cipher combination?

**Comment by sanderjo** [comment] 2016-01-18 20:56
Why not let Python / SSL take care of it? So no choice for the user. I did not specify any TLS version, and that works: highest TSL version available on both client and server is used automatically:

sslreader.eweka.nl results in TLSv1.2
```
$ python ssl_info.py 
OPENSSL_VERSION: OpenSSL 1.0.1f 6 Jan 2014
OPENSSL_VERSION_INFO: (1, 0, 1, 6, 15)

Protocols found:
PROTOCOL_SSLv23
PROTOCOL_SSLv3
PROTOCOL_TLSv1
PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2

Details:
PROTOCOL_SSLv23: 2
PROTOCOL_SSLv3: 1
PROTOCOL_TLSv1: 3
PROTOCOL_TLSv1_1: 4
PROTOCOL_TLSv1_2: 5
host is  sslreader.eweka.nl
SJ cipher DHE-RSA-AES128-SHA
SJ version: TLSv1.2
Done

```


ssl-eu.astraweb.com results TLSv1
```
$ python ssl_info.py 
OPENSSL_VERSION: OpenSSL 1.0.1f 6 Jan 2014
OPENSSL_VERSION_INFO: (1, 0, 1, 6, 15)

Protocols found:
PROTOCOL_SSLv23
PROTOCOL_SSLv3
PROTOCOL_TLSv1
PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2

Details:
PROTOCOL_SSLv23: 2
PROTOCOL_SSLv3: 1
PROTOCOL_TLSv1: 3
PROTOCOL_TLSv1_1: 4
PROTOCOL_TLSv1_2: 5
host is  ssl-eu.astraweb.com
SJ cipher ECDHE-RSA-AES256-SHA
SJ version: TLSv1
Done

```
Tested on Ubuntu 15.04

**Comment by Safihre** [comment] 2016-01-18 21:22
So an Auto setting, that would be perfect. But still offer to let the user override it if they want. Judging from nzbget and the benchmarks online, higher security comes at the price of lower speed.

**Comment by sanderjo** [comment] 2016-01-18 22:16
> im cool with defaulting to tls1 for now.. @sanderjo what is the real world benefits of tls 1 vs 1.2 for sab... speed*/security/etc. also tls 1.2 -- issues with python 2.x?

See table on https://en.wikipedia.org/wiki/Transport_Layer_Security#History_and_development:

Defined
Protocol	Year
SSL 1.0	n/a
SSL 2.0	1995
SSL 3.0	1996
TLS 1.0	1999
TLS 1.1	2006
TLS 1.2	2008
TLS 1.3	TBD

So TLS 1.0 is 17 years old. The table on https://en.wikipedia.org/wiki/Transport_Layer_Security#Cipher tells TLS 1.0 is only always secure with one specific cipher.

TLS 1.1 and certainly 1.2 are more secure. *If* you have them (which depends on the version of Python and Openssl; I believe TLS 1.1 and 1.2 support were introduced with Python 2.7.9.), let SABnzbd use them.

Are these "real world benefits"? I would say not as real-world as banking details, but you certainly want your username/password to stay secret, and in certain cases you don't want anybody to be able to eavesdrop on what you're downloading.

Is TLS slower? See statements on https://istlsfastyet.com/
I can quite well imagine SSL and TLS are slower than plain-text connections on *low-spec* CPUs. A test matrix (low versus high spec CPU, plain versus SSL versus TLS) would be useful.

**Comment by sanderjo** [comment] 2016-01-18 22:24
@shypike said:

> For 0.8.0, I propose to default to TLS1, the user can pick another value if he/she wants to.
> Later we can make it more sophisticated.

And I agree; too risky and time-consuming to change the behaviour *now*. Let's release 0.8.0 first.

**Comment by sanderjo** [comment] 2016-01-18 23:23
"Meten is weten", so I did some checking:

78 newsservers with TLSv1.2:
```
$ cat result-of-ssl-check.txt  | grep "socket version" | grep  TLSv1.2
host is  sslreader.eweka.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.i-telligent.com , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.cheapnews.eu , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  reader.123usenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.123usenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.4ux.nl , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.aeton.nl , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.alibis.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.altbinaries.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.altbinaries.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.atlantisnews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.bintube.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.bitusenet.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.budgetnews.net , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.cheapnews.eu , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.eweka.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.extremeusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.extremeusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.fastusenet.org , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.forteinc.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.frugalusenet.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.giganews.com , cipher AES256-GCM-SHA384 , socket version: TLSv1.2 Done
host is  news.hitnews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.hitnews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.i-telligent.com , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.i-telligent.com , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  reader.mijnusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.mijnusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.newsconnection.eu , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.newsdemon.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.newsfusion.net , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.newsgrabber.nl , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.newsgroupdirect.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.newshosting.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.newsrazor.net , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  reader.newsxs.nl , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.newsxs.nl , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.ngroups.net , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.panic.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.powernews.nl , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.powerusenet.com , cipher AES256-GCM-SHA384 , socket version: TLSv1.2 Done
host is  news.pureusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.smsusenet.nl , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  reader.snelnl.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.snelnl.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.speedplaza.net , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.sunnyusenet.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.supernews.com , cipher AES256-GCM-SHA384 , socket version: TLSv1.2 Done
host is  news.surfino.com , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  ssl.thenewsgroups.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.thundernews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.tigerusenet.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.tweaknews.eu , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenet4u.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.usenet-access.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenetcentral.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenetmonster.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenet.net , cipher AES256-GCM-SHA384 , socket version: TLSv1.2 Done
host is  ssl.usenet-news.net , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenetnewsserver.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.usenet.pro , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenet.pro , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenetrocket.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenet.se , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.usenet.se , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenetserver.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.usenet-to-go.de , cipher AES256-SHA , socket version: TLSv1.2 Done
host is  news.usenext.com , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  reader.voordeligusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.voordeligusenet.nl , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.wondernews.eu , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.xennews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  ssl.xennews.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.xlned.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  reader.xsnews.nl , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  reader.xsusenet.com , cipher DHE-RSA-AES128-SHA , socket version: TLSv1.2 Done
host is  news.yabnews.nl , cipher AES128-SHA , socket version: TLSv1.2 Done
host is  news.z51.biz , cipher AES256-SHA , socket version: TLSv1.2 Done

```

and 6 hosts with TLSv1:
```
$ cat result-of-ssl-check.txt  | grep "socket version" | grep  -v TLSv1.2     
host is  ssl-eu.astraweb.com , cipher ECDHE-RSA-AES256-SHA , socket version: TLSv1 Done
host is  news.anarqy.com , cipher AES256-SHA , socket version: TLSv1 Done
host is  ssl.astraweb.com , cipher DHE-RSA-AES256-SHA , socket version: TLSv1 Done
host is  news.newsguy.com , cipher DHE-RSA-AES256-SHA , socket version: TLSv1 Done
host is  news.nntpjunkie.com , cipher DHE-RSA-AES256-SHA , socket version: TLSv1 Done
host is  news.sonic-news.com , cipher AES256-SHA , socket version: TLSv1 Done

```
No TLSv1.1


To be complete: tested on Debian Testing, with python 2.7.11:
```
$ python ssl_info-with-version-info.py 
Python version: 2.7.11 (default, Dec  9 2015, 00:29:25) 
TLS on this system:
OPENSSL_VERSION: OpenSSL 1.0.2e 3 Dec 2015
OPENSSL_VERSION_INFO: (1, 0, 2, 5, 15)

Protocols found:
PROTOCOL_SSLv23
PROTOCOL_TLSv1
PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2

Details:
PROTOCOL_SSLv23: 2
PROTOCOL_SSLv3: No PROTOCOL_SSLv3
PROTOCOL_TLSv1: 3
PROTOCOL_TLSv1_1: 4
PROTOCOL_TLSv1_2: 5
```

**Comment by shypike** [comment] 2016-01-19 07:31
Conclusion: add a little list of TLS1-only hosts to SABnzbd?

**Comment by sanderjo** [comment] 2016-01-19 08:16
> Conclusion: add a little list of TLS1-only hosts to SABnzbd?

I'm not a fan of a static list distributed across millions of SAB instances. That's like a static /etc/hosts (with an IP address for www.google.com in it) instead of using DNS. ;-(

The point of my post is:
- Python/openssl is clever enough to find out which protocol is supported; I did NOT specify which protocol to use in my few lines of code; python/openssl negotiates that. 
- The majority of NTTPS server is using TLS 1.2. As it's more secure, do not force TLS1

**Comment by shypike** [comment] 2016-01-19 12:21
The list would only be used to set a default for the server, if no value was set.
The current code isn't clever enough to find out the right protocol, see zoggy's error message.

**Comment by Safihre** [comment] 2016-01-19 12:43
> The list would only be used to set a default for the server, if no value was set.
But that's the thing that @sanderjo is trying to say: not setting *any* value when making the connection will let openssl negotiate the best available. 
So we should leave it empty, except when the user explicitly picks one.

**Comment by shypike** [comment] 2016-01-19 13:28
@Safihre OK, if that works, that would be a better situation indeed.
I'll need to do some testing with that.
In that case we should also have a "Auto" setting, which would be the default.

**Comment by sanderjo** [comment] 2016-01-19 18:13
I was able to reproduce @thezoggy problem with ssl-eu.astraweb.com. Annoying and confusing indeed.

https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_SSLv23 says:

> ssl.PROTOCOL_SSLv23
> Selects the highest protocol version that both the client and server support. Despite the name, this
> option can select “TLS” protocols as well as “SSL”.

If that is true (and thus TLS1.2 will be selected if available), we could do this in SABnzbd

Use ssl.PROTOCOL_SSLv23 as default in the code, BUT in the GUI call it "automatic selection"

I would prefer to let SAB log the SSL/TLS version that is used. With python 2.7.9+ you can see that with SSLSocket.version(). But @shypike , where in newswrapper.py is the wrapped socket available? Ik can't find wrap_socket() anywhere ...

```
        if sslenabled and _ssl:
            ctx = _ssl.Context(ssl_method(ssl_type))
            self.sock = SSLConnection(ctx, socket.socket(af, socktype, proto))
```

**Comment by shypike** [comment] 2016-01-19 20:05
@sanderjo 
If V23 works, that would be great. There is no other way to let OpenSSL negotiate its own choice.
So far, I don't know where to find out the actual protocol used :(
We only ever introduced ssl_type, way back, because that could defeat ISP throttling.
It may be so that we should not have bothered and always go for V23.
It could have been a mistake all along.

**Comment by shypike** [comment] 2016-01-19 20:43
I cannot find way to get the negotiated protocol.
Despite the Python documentation suggesting that there is a version() method, the actual sockets don't have it.

**Comment by sanderjo** [comment] 2016-01-19 22:26
Are you using Python 2.7.9 or higher?

This works for me

```
import ssl
import socket

host = "sslreader.eweka.nl"
#host = "ssl-eu.astraweb.com"
PORT = 563
print "host is ", host
ip = socket.getaddrinfo(host, PORT, socket.AF_INET)[0][4][0]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(3)

try:
    # WRAP SOCKET
    wrappedSocket = ssl.wrap_socket(s)
    # CONNECT
    wrappedSocket.connect((ip, PORT))
    print "SJ cipher", wrappedSocket.cipher()[0]
    print "SJ version:", wrappedSocket.version()

    # CLOSE SOCKET CONNECTION
    wrappedSocket.close()
except:
    print "Something bad happened"

```

Is it a difference between ssl and OpenSSL?

**Comment by thezoggy** [comment] 2016-01-20 05:25
yes.. OpenSSL vs pyOpenSSL as well.  you can have an ssl version compiled with python (2.6+).. have one in system libs.. and then one included with your app... it can get messy very quickly.
pyopenssl provides a wrapper to the openssl lib.. and over time this went from a simple wrapper into a ssl replacement.. also they dropped python 2.5 support (not an issue with sab 0.8.x)

http://stackoverflow.com/questions/23709664/openssl-let-the-server-and-client-negotiate-the-method

looking back in my sickbeard dev chat notes.. ssl has always been a pain :(

```
2014-07-16 10:07:33 <_zoggy_>  SSLError -- 2014-07-13 16:21:54 CP Server Thread-3 :: PUSHALOT: Notification failed: _ssl.c:495: The handshake operation timed out
2014-07-16 10:07:47 <_zoggy_> looks like we may need to catch for that and just retry again.. also httplib has a known bug with with certain openssl versions that you can workaround by just forcing TLSv1
2014-07-16 10:07:52 <_zoggy_> ssl_version=ssl.PROTOCOL_TLSv1
2014-07-16 10:07:33 <_zoggy_> and there is http://bugs.python.org/issue10272
2014-07-16 10:07:02 <_zoggy_> which explains why on: http://sickbeard.com/forums/viewtopic.php?f=4&t=8220
2014-07-16 10:07:20 <_zoggy_> we saw those _ssl messages for timeouts (unreachable)
2014-07-16 10:07:05 <_zoggy_> anyways, i wanna just catch it and try one more time.. since earlier this week i got several notifications and noticed one didnt come through.. checked and saw that
2014-07-16 10:07:22 <_zoggy_> even though i got a notification just before and just after ~5 mins
2014-07-16 10:07:31 <_zoggy_> yet another reason we really need to move to Requests
2014-07-16 11:07:23 <_zoggy_> openssl s_client -connect pushalot.com:443
2014-07-16 11:07:29 <_zoggy_> can see it uses TLSv1
2014-07-16 11:07:51 <_zoggy_> so whats interesting if you specify to use tlsv1
2014-07-16 11:07:29 <_zoggy_> default (not specifying):
2014-07-16 11:07:30 <_zoggy_> SSL handshake has read 2758 bytes and written 444 bytes
2014-07-16 11:07:42 <_zoggy_>     Timeout   : 300 (sec)
2014-07-16 11:07:57 <_zoggy_> now if i use -tls1
2014-07-16 11:07:58 <_zoggy_> SSL handshake has read 2758 bytes and written 412 bytes
2014-07-16 11:07:05 <_zoggy_>     Timeout   : 7200 (sec)
```

```
2014-06-29 07:06:32 <_zoggy_> D:\>python -c "import _ssl; print _ssl.__file__, _ssl.OPENSSL_VERSION"
2014-06-29 07:06:32 <_zoggy_> C:\Python27\DLLs\_ssl.pyd OpenSSL 0.9.8y 5 Feb 2013
2014-06-29 07:06:18 <_zoggy_> above is my main machine with python 2.7.5.. made a new vm for doing builds, fresh install of python 2.7.7 with openssl 0.13.1 etc
2014-06-29 07:06:19 <_zoggy_> C:\sickbeard>python -c "import OpenSSL; print OpenSSL.__file__, OpenSSL.__version__"
2014-06-29 07:06:19 <_zoggy_> C:\Python27\lib\site-packages\OpenSSL\__init__.pyc 0.13.1
2014-06-29 07:06:19 <_zoggy_> C:\sickbeard>python -c "import _ssl; print _ssl.__file__, _ssl.OPENSSL_VERSION"
2014-06-29 07:06:19 <_zoggy_> C:\Python27\DLLs\_ssl.pyd OpenSSL 1.0.1g 7 Apr 2014
2014-06-29 07:06:30 <_zoggy_> glad to see python finally updated their ssl 
```

**Comment by sanderjo** [comment] 2016-01-20 13:37
As a sidenote for those interested: manual NNTP over SSL/TSL connections, which show protocol and cipher used:

With ```openssl```:

```
$ openssl s_client -connect  sslreader.eweka.nl:563
<snip>
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES128-SHA
<snip>
---
200 Welcome to Eweka (fx28.am4)
HELP
100 Legal Commands
  article [<messageid>|number]
  authinfo type value
  body [<messageid>|number]
<snip>
.
QUIT
DONE

```

With ```gnutls``` (from debian package gnutls-bin):

```
$ gnutls-cli ssl.astraweb.com -p 563

Processed 173 CA certificate(s).
Resolving 'ssl.astraweb.com'...
Connecting to '91.208.207.47:563'...
<snip>
- Version: TLS1.0
- Key Exchange: RSA
- Cipher: ARCFOUR-128
- MAC: SHA1
- Compression: NULL
- Options: safe renegotiation,
- Handshake was completed

- Simple Client Mode:

200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
HELP
100 Legal commands
  article [MessageID|Number]
  body [MessageID|Number]
  date
<snip>
.
QUIT
205 Transferred 702 bytes in 0 articles, 0 groups.  Disconnecting.
- Peer has closed the GnuTLS connection

```

**Comment by shypike** [comment] 2016-01-20 19:49
I've implemented a fix in "develop", please take a look at it: db64ce75adc32cf72d59c0365b4d9e5b553711a3
It's far from ideal, but should do the trick for 0.8.0.

**Comment by sanderjo** [comment] 2016-01-20 20:20
One more "meten is weten, gissen is missen": proof that ssl.PROTOCOL_SSLv23 indeed negotiates the best protocol. So it's safe to use it.

Also that in the UI below, I have called "SSLv23" ... "automatic", to avoid confusion with old SSL stuff.

On debian-testing with python 2.7.11 and OpenSSL 1.0.2e 3 Dec 2015:
```
sander@cubox:~$ python ssl-nntp-tester-5.py 


Host under test is sslreader.eweka.nl

Wanted sslprotocol is 2 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: TLSv1.2

Wanted sslprotocol is 3 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: TLSv1

Wanted sslprotocol is 5 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: TLSv1.2


Host under test is ssl.astraweb.com

Wanted sslprotocol is 2 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: TLSv1

Wanted sslprotocol is 3 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: TLSv1

Wanted sslprotocol is 5 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
could not create wanted SSL-socket
```

On Ubuntu 14.04 with python 2.7.6:
```


Host under test is sslreader.eweka.nl

Wanted sslprotocol is 2 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: no ssl.version() in your python ... :-(

Wanted sslprotocol is 3 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: no ssl.version() in your python ... :-(

no PROTOCOL_TLSv1_2 on your own system ... 


Host under test is ssl.astraweb.com

Wanted sslprotocol is 2 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: no ssl.version() in your python ... :-(

Wanted sslprotocol is 3 (2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)
Negotiated TLS version with remote host: no ssl.version() in your python ... :-(

no PROTOCOL_TLSv1_2 on your own system ... 
```

The hacked together code:
```
import socket, ssl, sys

def tryTLSconnection(host, port, sslprotocol):

	print "\nWanted sslprotocol is", sslprotocol, "(2=automatic, 3=TLS1, 4=TLS1.1, 5=TLS1.2)"
	try:
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                s.settimeout(3)

		try:
                    wrappedSocket = ssl.wrap_socket(s, ssl_version=sslprotocol)
                    wrappedSocket.connect((host, port))
		except:
		    print "could not create wanted SSL-socket"
		    return
		try:
			print "Negotiated TLS version with remote host:", wrappedSocket.version()
		except:
			print "no ssl.version() in your python ... :-(" 
		s.close()
	except:
		print "Unexpected error:", sys.exc_info()[0]


def checkhost(host,port):

	print "\n\nHost under test is", host
	tryTLSconnection(host,port, ssl.PROTOCOL_SSLv23)
	tryTLSconnection(host,port, ssl.PROTOCOL_TLSv1)
	try:
		tryTLSconnection(host,port, ssl.PROTOCOL_TLSv1_2)
	except:
		print "\nno PROTOCOL_TLSv1_2 on your own system ... "


checkhost('sslreader.eweka.nl', 563)
checkhost('ssl.astraweb.com', 563)

```

**Comment by sanderjo** [comment] 2016-01-20 20:33
> I've implemented a fix in "develop", please take a look at it: db64ce7
> It's far from ideal, but should do the trick for 0.8.0.

I did a "git pull" and tried three different servers with SSL and port 563, and each time I get "Invalid server address" in a popup. Nothing in stdout/stderr.
I try to find out what is going on.

> BTW, I think that not all pyOpenSSL versions make the version() method available.

I don't know about that, but you certainly need python 2.7.9 or higher

**Comment by thezoggy** [comment] 2016-03-04 03:43
sure you've heard about the SSLv2 (DROWN) attack thats been going around, openssl's latest release takes care of it by disabling sslv2...

https://www.openssl.org/news/secadv/20160301.txt
`NOTE: With this update, OpenSSL is disabling the SSLv2 protocol by default, as
well as removing SSLv2 EXPORT ciphers.`

not sure if this will cause us any issues (connecting to servers / sending emails / etc).. but may change the landscape as sites start disabling sslv2 to deal with it.. 

https://test.drownattack.com/?site=ssl.astraweb.com

**Comment by Safihre** [comment] 2016-04-04 10:25
Close this? Since we now default to auto-negation?

**Closed** 2016-04-04 11:01 UTC
Labels: 1 - Confirmed
