### ISSUE TITLE
Purging failed NZBs & Delete Files also deletes half-downloaded/extracting files

### ISSUE THREAD

**Issue by olipayne** [sabnzbd/sabnzbd#247] opened 2015-07-22 10:21 UTC

**Comment by shypike** [comment] 2015-07-22 10:37
Please add some details and/or a scenario description. Also the version of SABnzbd.

**Comment by Safihre** [comment] 2015-11-09 12:20
I checked this now a couple of times over the past month and cannot reproduce it. Either with purging Failed or purging Completed, it does not delete extracting or repairing jobs.
Think we can close this one..

**Comment by Safihre** [comment] 2015-11-09 12:24
@shypike I do notice that when I select "Show Failed jobs" (both in Plush and Glitter), that it shows Waiting/Checking/Repairing/Unpacking jobs. That shouldn't be of course..

**Comment by shypike** [comment] 2015-11-09 12:36
That's  by design.
The "Waiting/Checking/Repairing/Unpacking" always show.

**Comment by olipayne** [comment] 2015-11-09 12:37
Also couldn't replicate after the first two times, something did seem
strange though. I'll open a new ticket with more details if I can reproduce

**Closed** 2016-01-07 18:56 UTC
