### ISSUE TITLE
Glitter: Incomplete NZBs waiting to be processed are labeled as Completed

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#563] opened 2016-05-01 08:53 UTC
Right now if there's multiple files in the queue waiting to be verified/repaired/extracted then the ones waiting in line are labeled as Completed, whereas they probably should be labeled as something like Waiting or Pending.

![al-sab-completed](https://cloud.githubusercontent.com/assets/12164957/14940924/c5076b42-0f3e-11e6-90dd-65c3f8319033.jpg)

That screenshot above is a good example because the file next in the queue was missing about 2000 blocks, and it's absolutely going to fail, so just glancing at it and seeing Completed threw me for a loop thinking that somehow magically it was able to recover all 2000 blocks and extract successfully.

SABnzbd: 1.0.1RC1 [4eb486d]

**Comment by albino1** [comment] 2016-05-01 09:05
Well now I have another one and it says Fetching, which is I believe what Plush says.

![al-sab-completed2](https://cloud.githubusercontent.com/assets/12164957/14940981/08c77f28-0f41-11e6-84da-a7bbabb1c425.jpg)

Any idea why one would say Fetching and another would say Complete when they're both missing blocks?

**Comment by Safihre** [comment] 2016-05-01 09:20
You are right, it's a bug due to some new internal statusses.
@shypike your patch to ```1.0.x``` does not catch this. I just test it and the API-status is still ```deleted``` for an item waiting to be processed. Because Glitter doesn't know the ```deleted``` status, it shows it as complete. 
Before it also would show ones with ```Fetching x blocks``` as Queued, so maybe that also went wrong? Those ones coming back from extra fetch should also labeled ```Queued```.

**Comment by shypike** [comment] 2016-05-01 09:45
@Safihre Which API call is being used here?
Did you test with 6e108c9ef2deeabee90eb5fd6ac9c0b87090ceca ?

**Comment by Safihre** [comment] 2016-05-01 09:49
@shypike yes I tested with https://github.com/sabnzbd/sabnzbd/commit/6e108c9ef2deeabee90eb5fd6ac9c0b87090ceca, and the history call is just ```mode=history```.
![image](https://cloud.githubusercontent.com/assets/5703454/14941174/cb5b4b04-0f92-11e6-9415-e5e365f46f6a.png)

**Comment by shypike** [comment] 2016-05-01 11:29
@Safihre I cannot reproduce the problem.
There's only one place the status is set to "Deleted", here: https://github.com/sabnzbd/sabnzbd/blob/1.0.x/sabnzbd/nzbqueue.py#L441

**Comment by Safihre** [comment] 2016-05-01 11:36
I just did a breakpoint there and ```nzo.status = ToPP``` for every job, so that if-statement will set it to Deleted.
Seems wrong to me!

**Comment by shypike** [comment] 2016-05-01 11:52
Ah right, it's the ToPP status!
I will check again whether that state is really needed.

**Comment by Safihre** [comment] 2016-05-01 11:55
It could also be the ```Fetching``` status!
See @albino1's screenshot https://cloud.githubusercontent.com/assets/12164957/14940981/08c77f28-0f41-11e6-84da-a7bbabb1c425.jpg

**Comment by Safihre** [comment] 2016-05-01 11:57
It could also be the ```Fetching``` status I think, but in the end they should all have status ```Queued``` when they are not processing. Otherwise they show up wronglt in Glitter and Plush.
See @albino1's screenshot https://cloud.githubusercontent.com/assets/12164957/14940981/08c77f28-0f41-11e6-84da-a7bbabb1c425.jpg

**Comment by shypike** [comment] 2016-05-01 12:47
This should fix it: f0a243e3d3ef47eacd4a73b2f2df164e1dce93d8

**Comment by Safihre** [comment] 2016-05-01 13:41
:+1: Yes, fixed now!

**Comment by Safihre** [comment] 2016-05-01 13:47
Took some time but was also able to replicate what happens when there's a job waiting for PP that was Fetching extra blocks (like @albino1's screenshot from before), that case is also handled correctly.
It has Status=Queued!

**Closed** 2016-05-12 14:01 UTC
