### ISSUE TITLE
Cleanup leftover files after crash on importing/grabbing NZB 

### ISSUE THREAD

**Issue by zeon** [sabnzbd/sabnzbd#494] opened 2016-02-28 16:18 UTC
Does anyone encounter this before? Jobs I added to the queue just stay there forever and no error logs or anything. See the screen capture below:

![image](https://cloud.githubusercontent.com/assets/450073/13380285/f6979470-de79-11e5-8552-2e0f36fa0b7f.png)

and if I copy that download url sabnzbd tries to fetch the nzb file in the browser it downloads just fine. Any clues?

**Comment by Safihre** [comment] 2016-02-28 16:20
What version of Sabnzbd are you on?

**Comment by zeon** [comment] 2016-02-28 16:25
0.7.20

**Comment by Safihre** [comment] 2016-02-28 16:27
Are you running it locally or on your NAS/server?

**Comment by zeon** [comment] 2016-02-28 16:27
NAS

**Comment by Safihre** [comment] 2016-02-29 08:31
There are problems with SSL certificates (for the https connection) on Synology NAS. Could you try adding the same URL but then with http instead of https. Browsing through the forum I found updates to Python on the NAS might solve this problem. There is also a way to disable certificate validation, but can't find the guide on the forum for that now @sanderjo is the expert there :)

**Comment by thezoggy** [comment] 2016-03-01 03:38
config > special > enable_https_verification -- set that to off

**Comment by Safihre** [comment] 2016-03-01 05:57
@thezoggy he's on 0.7.2, that special and function were only introduced in 1.0.0.

**Comment by thezoggy** [comment] 2016-03-01 13:46
oh yeah, just downgrade python to pre 2.7.9 or upgrade sab version

**Comment by labrys** [comment] 2016-03-18 09:16
This is appears to be a duplicate of what I was experiencing in #404.  After reading this I tried @thezoggy's fix and continued to have the same issues.  I looked into it some more and found that it appears the URL grabber appears to be dying.  I watched the console logs to see what might be triggering it and found that sometimes when the URL grabber runs, it prints out the content of the NZB file to the log and after that the URL grabber never runs again.   If you remove the offending job and restart SAB then the URL grabber will continue to function as normal and resolving jobs, until it chokes on another job.  Rinse lather and repeat until all jobs are resolved and all offending jobs have been removed.  If you copy the offending jobs URL, download it via your browser, and add the NZB that way, it will proceed with the job as normal, however it appears the majority of those NZBs fail to download.

Tested on Win 10 running Python 2.7x64 and SAB, various 1.0.0 versions from dev and master.

**Comment by Safihre** [comment] 2016-03-18 09:22
Could you maybe post the part of the log where it goes wrong? Or attach it to the message, think Github allows that.

**Comment by labrys** [comment] 2016-03-18 09:28
@Safihre Redacting it right now so I can post it.

**Comment by labrys** [comment] 2016-03-18 09:43
@Safihre here's the gist https://gist.github.com/labrys/c6525594384549c3cb67

**Comment by Safihre** [comment] 2016-03-18 09:55
Very odd, I really have no clue.. @shypike any ideas why this would suddenly appear in the log randomly like that?

**Comment by thezoggy** [comment] 2016-03-18 10:56
can you provide the url? curious to know if they are using x-dzb-*

**Comment by shypike** [comment] 2016-03-18 11:29
Very strange indeed.
However the urlgrabber code has become a bit of a mess over the years.
Partially due to us using outdated parts of the Python library.
I would appreciate if unredacted material was sent to bugs@sabnzbd.org (including URLs)
Assuming that it's not a generic issue, independent of specific URLs,

**Comment by labrys** [comment] 2016-03-18 13:15
@shypike sent an unredacted log file.  This is a different url but exhibits the same exact symptom.  This has occurred from several providers and not all URLs from this provider exhibit this symptom.

**Comment by shypike** [comment] 2016-03-18 13:45
@labrys If I understand it correctly: the NZB determines the behaviour, not the indexing site?

**Comment by Safihre** [comment] 2016-03-18 14:26
Found it!
We use the filename provided by the meta information in the NZB, and for this NZB the filename starts with... ```con```.. On an Windows PC..

**Comment by thezoggy** [comment] 2016-03-18 14:32
`con` is fine. `con ` is not.

**Comment by Safihre** [comment] 2016-03-18 14:38
Adding ``replace_win_devices``` to ```sanitize_foldername``` will make the URLGrabber get the file, but now par2.exe breaks. It's stuck at 0% Repairing with par2.exe using 100% CPU..

```
2016-03-18 15:33:03,943::DEBUG::[newsunpack:1204] Starting par2: ['C:\\Users\\__v\\Documents\\GitHub\\sabnzbd\\win\\par2\\x64\\par2.exe', 'r', 'D:\\SABnzbd\\_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H\\_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.par2', 'D:\\SABnzbd\\_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H\\*']
2016-03-18 15:33:04,572::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part03.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part03.rar"
2016-03-18 15:33:04,598::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part02.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part02.rar"
2016-03-18 15:33:04,622::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part04.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part04.rar"
2016-03-18 15:33:04,651::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part01.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part01.rar"
2016-03-18 15:33:05,016::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part05.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part05.rar"
2016-03-18 15:33:05,039::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part06.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part06.rar"
2016-03-18 15:33:05,075::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part07.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part07.rar"
2016-03-18 15:33:05,108::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part08.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part08.rar"
2016-03-18 15:33:05,424::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part09.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part09.rar"
2016-03-18 15:33:05,453::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part10.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part10.rar"
2016-03-18 15:33:05,483::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part11.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part11.rar"
2016-03-18 15:33:05,526::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part12.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part12.rar"
2016-03-18 15:33:05,832::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part13.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part13.rar"
2016-03-18 15:33:05,887::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part15.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part15.rar"
2016-03-18 15:33:05,917::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part14.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part14.rar"
2016-03-18 15:33:05,971::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part16.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part16.rar"
2016-03-18 15:33:06,242::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part17.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part17.rar"
2016-03-18 15:33:06,269::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part18.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part18.rar"
2016-03-18 15:33:06,326::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part19.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part19.rar"
2016-03-18 15:33:06,381::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part20.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part20.rar"
2016-03-18 15:33:06,457::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part24.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part24.rar"
2016-03-18 15:33:06,641::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part22.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part22.rar"
2016-03-18 15:33:06,671::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part21.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part21.rar"
2016-03-18 15:33:06,719::DEBUG::[newsunpack:1455] PAR2 will rename "_Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part23.rar" to "Con.Man.S01E04.Retarding.It.All.Up.720p.WEB-DL.DD5.1.H.264-EsQ.part23.rar"
2016-03-18 15:33:06,749::INFO::[newsunpack:1278] Verified in 2 seconds, repair is required
```

**Comment by Safihre** [comment] 2016-03-18 14:56
When I add ```replace_win_devices``` only to the URLGrabber and not to ```sanitize_filename```, it will download the files and name them ```Con.etc```. But now it hangs on *Repair: Quick Checking*.
Going to the folder I can not open the files using Winrar or par2.
I can't even delete them... What the...

**Comment by labrys** [comment] 2016-03-18 18:12
@Safihre the windows command to remove that would be `rd \\.\c:\path\to\folder /S /Q`
`rd` is remove directory, `\\.` is current computer `\c:\path\to\folder` is ofc the `c:` drive followed by the path.  `/S` removes subdirectories and `/Q` is for quiet, e.g. no confirmation.

**Comment by shypike** [comment] 2016-03-18 19:00
There's no real solution for this.
We cannot stop par2.exe from renaming the files to what they should be according to the par2 files.
Same goes for unrar.exe
Unfortunately there's at least one idiot in the Windows team. This is an inheritance from the MSDOS era, but MSDOS only ever forbade "con", "con.txt" was OK.

**Comment by labrys** [comment] 2016-03-18 19:54
@shypike a couple of proposals
First and foremost I think a watchdog process should be created (assuming there isn't one) to restart the URL grabber in case of any failures, possibly adding the last failed URL to an exclusion list to avoid repeated lockups.  This would allow URL grabber to continue even if the failure is for some other unforeseen reason.  If the URL grabber watchdog fails to restart the process or encounters repeated failures, it can raise an error for the user to either intervene or report the issue.

Secondly, perhaps, if par2.exe can't process certain files correctly, attempt to preemptively detect such cases and prevent par2.exe from running in those cases.  Another option would be to possibly detect excessive par2.exe process runs (either by time or by cpu usage or some other metric) and kill the task if it can't complete.

Lastly, possibly run the sanitizer yet again after the PAR2 process has completed to make sure file/folder names are valid for the platform afterwards.

**Comment by Safihre** [comment] 2016-03-19 10:03
On a side note: NZBGet also fails miserably on this NZB, it shoots to 100% CPU before fetching finishes and then just gets locked.

@labrys Unfortunately none of those command line functions helped, it was crazy. I tried ```rd```, ```DEL``` and ```rm``` and all they suggested.

No program on Windows can correctly handle these files starting with ```con```, so all we could do is indeed blacklist.
It is probably too much work to make a special filter for this since it happens so rarely, you are only the second one to report this..

**Comment by shypike** [comment] 2016-03-19 10:24
The only feasible measure is to look at the expected files in the par2 files and abort if there are forbidden names. Intercepting unrar is a lot more difficult though, especially when it's using RAR5 format.

**Comment by labrys** [comment] 2016-03-19 19:35
@Safihre I agree that its too much to filter for a specific instance, however, in the interest of robust programming, some kind of watchdog to make sure the URL grabber doesn't die or restarts it if it does and some sort of exclusion of problematic URLs/files (regardless of the reason they fail) should be included.

**Comment by shypike** [comment] 2016-04-02 12:05
There already is a watchdog for the URL-grabber.
What is missing is a clean up of the NZB responsible for the crash.
The "forbidden words" issue of Windows cannot be completely solved.

**Comment by Safihre** [comment] 2017-02-15 09:06
Seems resolved, with the fixing of any forbidden Windows names problems.

**Closed by Safihre** 2017-02-15 09:06 UTC
Labels: Confirmed
