### ISSUE TITLE
Decompression over slow network connection

### ISSUE THREAD

**Issue by Fmstrat** [sabnzbd/sabnzbd#189] opened 2014-12-18 14:45 UTC
Currently SABnzbd extracts files from the Temporary Download Folder to the Completed Downloads folder directly. This can cause slow downs over slow networks, or long IO wait times for those running on virtual machines who mount the host OS's drives.

Recommend providing a check box on the Folders configuration screen labeled "Decompress in temporary folder" that allows this behavior to be swapped, where when the check box is:

Off (default): Decompresses directly from Temporary Download Folder to Completed Downloads
On: Decompresses in the Temporary Download Folder, then moves uncompressed files to Completed Downloads

**Comment by Cpuroast** [comment] 2016-12-09 21:46
I just tested this with Temporary(SSD) on macOS 10.12 and Complete on Windows 8.1(HDD) network share.
The source SSD on the macOS 10.12 box can read ~600MB/sec
The HDD on the win 8.1 box drive can write ~200MB/sec
Both are fast machines.
I tested with unrar 5.30 and unrar 5.40.

Results:
SMB1.0 - ~111Mbit/sec
SMB3.0 - ~96Mbit/sec

Oddly enough if I used winrar 5.40 to extract from Win 8.1 to a target FreeBSD SMB3 file share, performance was excellent and peaked at around ~650Mbit/sec

**Comment by Safihre** [comment] 2016-12-09 21:56
So, the problem is in the OS that winrar is run on? 

That would explain why I was also not able to reproduce this on Windows, extracting using winrar to network is also at full speed for me.

**Comment by Cpuroast** [comment] 2016-12-09 22:04
yes, it seems that way, I tried unrar from the mac to the same FreeBSD SMB3 file share and got a dismal ~25Mbit/sec

**Comment by Cpuroast** [comment] 2016-12-09 22:05
so there are definitely situations where unraring to temp and then copy to complete has massive performance benefits.

**Comment by thezoggy** [comment] 2016-12-10 05:23
yes, depends on your workflow..  doing things locally or not.
ive seen people d/l with sab on one comp but then their 'download' folder is across the network on a nother comp.. or even outside their network (fusefs).. its even worse when their 'incomplete' is also not locally..  and the really jacked up scenario is when the incomplete is remote but then download is local...

**Comment by Safihre** [comment] 2017-06-24 19:09
WIll not implement this at any time, so closing it.

**Closed by Safihre** 2017-06-24 19:09 UTC
Labels: Help Wanted
