### ISSUE TITLE
Sab locks out server for 10min unnecessarily!!

### ISSUE THREAD

**Issue by sabfreezes** [sabnzbd/sabnzbd#733] opened 2016-11-13 01:54 UTC
#Short version of problem: 

When connecting to a server like astra which has max 20connections... and some of them are frozen/drop off, sab warns: "too many conections in use", over and over... and then blocks you out for 10min if it keeps up with the warning, which in essence, kills the speed. 

Other clients (newsleecher) dont do that. They keep powering through the messages and the frozen connections since its not Astraweb doing the lock.

Only fix right now is to MANUALLY shutdown SAB and restart it for it to kick back at full speed (which again confirms its not astraweb blocking it, but SAB choosing for whatever reason that its not going to try to reconnect.

I pointed this out to  @thezoggy  over a month ago and apparently there's some "switch" called no_penalties that I turned on... but it doesn't do anything... same problem persists.

This 10min lock "feature" wasn't there in .720 (which I used for over 3-4 months after 1.0.0 was released) so can we please get someone to look into this properly?

I'm disappointed that 1.1.1 was released a few days ago and this bug is still there, and not acknoledged here.

I also pointed out this bug in Reddit to Safhyre today...

*fingers crossed*

**Comment by thezoggy** [comment] 2016-11-13 02:11
```
2016-10-30 09:10:20 <IAmApoll0> Is there a setting in the new sabnzb to try to attempt to resume downloading after X seconds when it deems there are "too many connections" connected?
2016-10-30 09:10:10 <IAmApoll0> It seems that if I have newsleecher going and using 20/20 slots, sab just freezes (pauses) downloading, and then even if i shut down newsleecher, it doesnt automatically attempt to redownload after 15sec, 30sec, 1min, 5min, whatever the # is...... it just indefinitly sits at pause
2016-10-30 09:10:25 <IAmApoll0> annoying as hell to have to go RESUME it manually when i remember
2016-10-30 09:10:32 <IAmApoll0> the old sab 7.20 never used to do it
2016-10-30 09:10:39 <Daq> but I don't think there is a function for that (AFAIK just a user here)
2016-10-30 09:10:55 * David-- (none@synIRC-CA0679E5.daveaskew.com) Quit (Quit: - nbs-irc 2.39 - www.nbs-irc.net -)
2016-10-30 09:10:03 <Daq> after getting too many 502's that is
2016-10-30 10:10:34 <IAmApoll0> ok so can i change that?
2016-10-30 10:10:40 <IAmApoll0> this "feature" wasnt there in the old .720
2016-10-30 10:10:48 <IAmApoll0> and it'd usually reconnect itself within 2-3 min
2016-10-30 10:10:05 <IAmApoll0> and I know the 10min you quoted is incorrect, cause ill wake up sometimes to the queue not having progressed at all
2016-10-30 10:10:07 <IAmApoll0> cause of that
2016-10-30 10:10:32 <IAmApoll0> so that 10min may actually be like 10 hours or something, but a "force disconnect" on sab fixes it immediately
2016-10-30 10:10:55 <Daq> well it isn't incorrect (check you logs if you need to. it will contain messages like ::INFO::[downloader:635] Server news.server.com:119 ignored for 10 minutes)
2016-10-30 10:10:27 <Daq> that's wat sab is saying 
2016-10-30 10:10:54 <Daq> but I've been having some issues with too many connections also lately .. even with max1 connection
2016-10-30 10:10:02 <Daq> other news readers work perfectly
2016-10-30 10:10:28 <Daq> so it could be in the same area
2016-10-30 10:10:47 <Daq> an option that maybe could help you is in the special section
2016-10-30 10:10:10 <Daq> the no_penalties one
2016-10-30 10:10:41 <Daq> normally used for servers with lots of 502 errors. sab then only "blocks" for 1 min
2016-10-30 10:10:08 <Daq> https://sabnzbd.org/wiki/introduction/known-issues 
2016-10-30 10:10:25 <Daq> the unreliable usenet servers paragraph
2016-10-30 10:10:45 <IAmApoll0> ??
2016-10-30 10:10:48 <IAmApoll0> What are you reading?
2016-10-30 10:10:49 <IAmApoll0> https://sabnzbd.org/wiki/configuration/1.1/special
2016-10-30 10:10:53 <IAmApoll0> there is no switch for "502"
2016-10-30 10:10:56 <IAmApoll0> or "unreliable"
2016-10-30 10:10:01 <IAmApoll0> those keywords dont show up in the search
2016-10-30 10:10:10 <IAmApoll0> oh... enable: "no_penalties"
```

**Comment by thezoggy** [comment] 2016-11-13 02:20
looking, at downloader:
we see:
```
_PENALTY_SHORT = 1 # Minimal penalty when no_penalties is set
```

https://github.com/sabnzbd/sabnzbd/blob/1.1.x/sabnzbd/downloader.py#L629
```
                            if block or (penalty and server.optional):
                                if server.active:
                                    server.active = False
                                    if (not server.optional) and cfg.no_penalties():
                                        penalty = _PENALTY_SHORT
                                    if penalty and (block or server.optional):
logging.info('Server %s ignored for %s minutes', server.id, penalty)
```

so if the server is your main one and not a block, then `no_penalties` isnt going to do much for you.

**Comment by thezoggy** [comment] 2016-11-13 02:23
```
[08:22pm] <IAmApoll0> Astra is my main server
[08:23pm] <IAmApoll0> I dont have astra set as optional
```

there we go...

**Comment by thezoggy** [comment] 2016-11-13 02:37
user is using windows 10, running sab 1.1.1 windows binary

**Comment by sabfreezes** [comment] 2016-11-13 03:04
Astra doesnt allow multiple IPs at same time. If i was account sharing, astra locks out both people for 5min. That is not what is happening here.

Yes I am on Windows 10, x64.

I have also *JUST NOW* set both my MAIN and backup servers as OPTIONAL as requested by @thezoggy - so maybe the "no penalties" being on in conjunction with this will fix the issue...

Will monitor over next few days and report back..... in meantime if anyone has alternatives and fixes... by all means... please share (seems silly to set all servers as Optional... cause then...... why even have this option?)

**Comment by albino1** [comment] 2016-11-13 07:23
In my experience it's because Astra isn't closing the connection fast enough.  Try lowering your connections to more like 18 and see if that helps alleviate the issue.

**Comment by Safihre** [comment] 2016-11-13 22:17
Trying to reproduce it, but can't. Tried splitting connections between EU/US servers, but SAB nicely reduces the number of connections when I add too many.
The difference vs older SAB is that we now include code 482 in the check of too many connections. 
Have to hope it occurs at some point in the next days.

**Comment by sabfreezes** [comment] 2016-11-13 23:22
@Safihre I sent you a .zip file with a few nzbs that are missing partials... load that up? That should reproduce it.

**Comment by sabfreezes** [comment] 2016-11-13 23:23
@albino1 I have a gigabit connection. I need the speed. Even 20 connections doesn't max out astra. But yes, I've tried lowering it to 18, or even 15. Same problem.

**Comment by thezoggy** [comment] 2016-11-14 00:06
@Safihre only time ive gotten the too many connections messages is when i run multiple usenet clients or share my usp between multiple connections...   but I will say I'm on win7 and with no firewall/antivirus/any apps that would possibly inspect/hold onto the connections

**Comment by albino1** [comment] 2016-11-14 00:21
I've often gotten too many connection errors, but much less often with 1.x than I got with 0.7.x.

FWIW, I get them both on Windows 7 and in Debian Wheezy.  Windows is 150mbit and the Wheezy box is 1 gigabit.  I would say that the biggest culprits of the providers I've tried are definitely Astraweb and Frugal, and since I lowered the connections a little bit below max for all of my servers it happens significantly less often.

**Comment by Safihre** [comment] 2016-11-14 08:06
I used your zip, and experienced no problems so far after 30GB. The problem doesn't depend on the stuff being downloaded, but on the connection. For some reason it causes timeouts on your servers. 
What did you set for Server Timeout?

**Comment by Safihre** [comment] 2016-11-14 08:53
Can you set logging in the Status window to +Debug, wait until a few of these errors occur and then send me the log at safihre@sabnzbd.org? 
It will be automatically  anonomyzed. 
After this set it back to Errors/warnings only, because increased logging reduces performance.

**Comment by sabfreezes** [comment] 2016-11-14 14:25
@Safihre I've noticed it happens when parts are incomplete... so if you can, please try download the whole pack, not just 30gb (if you have bandwidth and time to spare).

SSL-us, port 443, timeout 30, priority 0, connections 20, ssl type default, currently set to OPTIONAL server for BOTH my servers

It happened a bunch through today morning as well, note the timers bang on at 10min intervals... despite optional servers on and no penalties on.

WARNING 14/11/2016 09:08 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:58 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:58 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:58 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:58 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:58 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:57 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:49 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:49 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:44 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:34 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:24 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:24 Too many connections to server ssl-us.astraweb.com
WARNING 14/11/2016 08:24 Too many connections to server ssl-us.astraweb.com

**Comment by sabfreezes** [comment] 2016-11-14 14:29
I'll set the logging to debug and send by tomorrow

**Comment by thezoggy** [comment] 2016-11-14 19:31
once you set the logging level to debug, you need to restart sab for it to take effect.

**Comment by Safihre** [comment] 2016-11-14 20:29
@thezoggy, no you don't have to restart. Takes about a second to take effect after changing in Glitter..

**Comment by Safihre** [comment] 2016-11-15 07:46
@sabfreezes I have downloaded the whole 60GB and no problems.. Hoping your logs can tell me more!

**Comment by sabfreezes** [comment] 2016-11-16 13:43
@Safihre shut down sab. deleted all logs. restarted sab. set to debug. restarted sab. logged since my last post. shut down right now. zipped logs. emailed.

**Comment by Safihre** [comment] 2016-11-16 15:50
I think I have found the problem. So I see in the logs that _something_ (unrelated to missing articles) causes all your connections to timeout at the same time, upon which SAB will re-connect. 
However, SAB has a special optimization that it will look up which IP-addresses belong to a hostname (this can be multiple for load-balancing, in the case of ```ssl-us.astraweb.com``` there are a whooping [21 addresses](https://www.robtex.com/?dns=ssl-us.astraweb.com) linked to that name) and try to find the one that responds fastest.
In your case, it re-connects to a different IP than was used in the previous connection attempt. Since I can imagine that the information of our lost connections on the first server is not immediately shared to all 20 other servers, causing the new server to throw the ```502 Your per-user connection limit reached```.

```
2016-11-15 00:30:24,770::INFO::[happyeyeballs:138] Quickest IP address for ssl-us.astraweb.com (port 443, ssl True, preferipv6 True) is 207.246.207.131
>>> Now timeouts happen and SAB goes and searches for the fastest IP with this host:
2016-11-15 00:33:00,028::INFO::[happyeyeballs:138] Quickest IP address for ssl-us.astraweb.com (port 443, ssl True, preferipv6 True) is 8.17.249.102
```
Can you try and go into Config > Switches and then set Load-balancing to Prevent load-balancing? 
Does this improve things?

(paging @sanderjo, this seems like something we should think off, because problems with Astra seem more common and this could be a cause of it..)

**Comment by sanderjo** [comment] 2016-11-16 20:18
Some remarks:

- HappyEyeballs does socket connects, but no login. So if Astraweb alreadys counts that as a user session (so: based on the source IP address, not on a user name), I would be surprised and - more important - that would be bad news for different users behind the same NAT-device (or CGNAT-device).
- I wonder if "prevent load-balancing" really solves the problem. If so, the cause is indeed in the socket connects, and not in using a different destinations IP address of Astraweb.

How to solve this:
- @Safihre you suggested in a PM to let SAB take into account that there are still sessions open, and reuse that IP address to avoid the above. Implementation: You have to 1) cache the last found IP address for a server  and 2) be able to determine if connections to that server are active.

Other options: 
- make HappyEyeball's memory longer. I believe it's now 100 seconds
- in HappyEyeballs lower the number of IP addresses to check to N per type: for example 2 IPv4's, 2 IPv6's. Still a problem with 19 connections in use, 4 HE-connects set up ...
- make HappyEyeballs more sequential: only start up a next socket connect each 300 ms if the previous socket connect(s) have not (yet) resulted in a connect. You can still get different IP addresses as a result, though, but SAB's HE is less agressive.

... to be updated

**Comment by sabfreezes** [comment] 2016-11-17 16:52
@Safihre @sanderjo I dont know what any of that stuff means between you two... so this is what I have done at the time of this posting.

- set the: Config > Switches and then set Load-balancing to Prevent load-balancing
- set logging back to debug
- saved and shut down sab
- deleted all logs (so fresh batch upon next)
- will report back with logs in another 2 days

Also: Regarding your latest first line: "I think I have found the problem. So I see in the logs that something (unrelated to missing articles) causes all your connections to timeout at the same time, upon which SAB will re-connect."

Do we know what that "something" is, because it appears awfully coindidental, that when I have missing articles, it eventually times out ... (like in that .rar file I sent you...) but apparently, you didnt get any time outs with the entire 100gb pack... so I dunno... (maybe astra moved the files to their main servers after I attempted to redownload... I dont know).

Either way, will report back in a day or 2 when I see it happen again.

If there's anything else you need me to do aside from preventing load balance and debug mode on - let me know.

**Comment by sanderjo** [comment] 2016-11-17 17:54
@sabfreezes 

1) @Safihre has made progress on a real good solution in SABnzbd
2) For now: instead of "ssl-us.astraweb.com" as the host name, can you fill out "8.17.249.103" (still SSL, 20 connections, same login etc) and download. You should NOT get a problem. Please report back the result.

**Comment by Safihre** [comment] 2016-11-17 18:07
@sabfreezes What @sanderjo says above will fix it for now, because even 'Prevent load-balancing' will **not** solve the issue.
I worked today on a solution after reproducing the problem and indeed it's something we introduced in the latest versions that causes timeouts to snowball and result in that 10min block. 
I looked at your logs again, but there seems to be no source of the timeouts, just that the load-balancing feature causes the sporadic timeouts to result in a full block.

Hope to release a version with this fix (and others) soon!

**Comment by sabfreezes** [comment] 2016-11-17 18:41
@Safihre @sanderjo 
Ok, so I Just went to revert the settting I had set to prevent load balancing, back to what it was... and the setting didn't stick... so even though above I said I set it to prevent, and then saved, and then shutdown (restarted) sab... The setting didnt even save... so I guess that's broken too lol.

Anyways... so its back to ALlow Load balancing with optimization (default....)

So all I have done now is: Change Astra to:  8.17.249.103 // 563 from ssl-us 443... logging is still set to debug. Will monitor for a day or 2 and report back with problems, if any...


NOTE: Both Astra and UNB are still set to "OPTIONAL" (as requested by @thezoggy ) let me know when I can revert that back...

**Comment by thezoggy** [comment] 2016-11-19 05:03
@sabfreezes the setting works fine here and saves just fine. I see that you have mention having problems before on unable to change settings on sab's config.. makes me think you are running into permission issues on saving config or have something else going on locally.. check logs/browser console.. and make sure your not disabling javascript.

**Comment by sabfreezes** [comment] 2016-11-19 14:38
@thezoggy - I don't know how to interpret the logs, so ....... :| But you are right, this isn't the first setting that didn't "save" properly... First, we had the Timeout settings (couldn't go lower than 30) - but we know why, it says right on the page, that the range is 30+ lol... so changing it to 5,10,15 wouldn't logically work.

Now this load balancing one... but everything else seems to work...

@Safihre - haven't had to DL much in the past 2 days, no issues though, Sunday is when the big DL happens, so I will report back then if the fix from you and @sanderjo works.... but so far, 0 issues with 8.17.249.103

**Comment by sabfreezes** [comment] 2016-11-19 22:00
@Safihre @sanderjo 

WARNING 19/11/2016 15:23 Too many connections to server ssl-us.astraweb.com
WARNING 19/11/2016 15:13 Too many connections to server ssl-us.astraweb.com
WARNING 19/11/2016 15:03 Too many connections to server ssl-us.astraweb.com

Looks like it didn't fix it... sending logs again...

**Comment by Safihre** [comment] 2016-11-19 22:42
I checked his log and this time there are no timeouts or network drops in the logs (he is using the IP as host), SAB just connects from idle and immediately gets rejected from the first connections and not during ongoing downloads.
So that must be a problem on Astra's side or maybe  another download-program was running  at the same time.

**Comment by sanderjo** [comment] 2016-11-20 06:02
So OP should reset his astraweb password,  set it in sabnzbd and try again. @sabfreezes can you do that?

**Comment by sanderjo** [comment] 2016-11-21 15:42
Unsubscribing from this thread. Just notify me know when/if I can add value to this thread.

**Closed** 2016-11-25 14:06 UTC
