### ISSUE TITLE
pneumatic error

### ISSUE THREAD

**Issue by berot3** [sabnzbd/sabnzbd#537] opened 2016-04-07 12:39 UTC
Hi, not sure if I should put this here or at https://github.com/TsUPeR/xbmc-pneumatic/issues/new

with version 0.7 it works fine, but with 1.0 I get this error:

````
2016-04-07 14:15:22,275::INFO::[_cplogging:216] [07/Apr/2016:14:15:22] HTTP 
Request Headers:
  HOST: x.x.x.x:8080
  CONNECTION: close
  Remote-Adde: x.x.x.x
  Content-Length: 941
  USER-AGENT: Xbmc/14.0 (Addon; plugin.program.sabnzbd)
  Content-Type: multipart/form-data; boundary=192.168.99.1.502.44759.1460031322.272.1
  ACCEPT-ENCODING: identity

2016-04-07 14:15:22,276::ERROR::[_cplogging:216] [07/Apr/2016:14:15:22] HTTP 
Traceback (most recent call last):
  File "/opt/sabnzbd/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/sabnzbd/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/sabnzbd/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/sabnzbd/sabnzbd/interface.py", line 460, in api
    msg = check_apikey(kwargs)
  File "/opt/sabnzbd/sabnzbd/interface.py", line 217, in check_apikey
    req_access = sabnzbd.api.api_level(mode, name)
  File "/opt/sabnzbd/sabnzbd/api.py", line 954, in api_level
    if cmd in _api_table:
TypeError: unhashable type: 'list'
````

What is going wrong?

**Comment by Safihre** [comment] 2016-04-07 12:47
One of the parameters, the one that specifies the action that's request, occurs twice in the url that pneumatic sends to sabnzbd. So yes, indeed should report there :)

**Comment by shypike** [comment] 2016-04-07 14:15
And fix it on our side too.
The problem is that we get double parameters as lists instead of simple strings. In most places it's already taken care of, not for the main parameter.

**Comment by shypike** [comment] 2016-04-07 19:35
Will be fixed in 1.0.1

**Closed by shypike** 2016-04-07 19:35 UTC

**Comment by mgaulton** [comment] 2017-01-05 20:21
I appear to have gotten this today when trying to edit RSS feeds. Can't open the config tab at all.


Version:	1.1.1 [33a7874]
Python Version:	2.7.12 (default, Jun 28 2016, 06:57:42) [GCC] [UTF-8]
OpenSSL:	OpenSSL 1.0.2j-fips 26 Sep 2016   [TLS v1.2, TLS v1.1, TLS v1, SSL v3]
pyOpenSSL:	16.0.0

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/sabnzbd/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/sabnzbd/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/sabnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/sabnzbd/sabnzbd/interface.py", line 1971, in index
    rss[feed]['baselink'] = get_base_url(rss[feed]['uri'])
  File "/opt/sabnzbd/sabnzbd/misc.py", line 1307, in get_base_url
    url_host = urlparse(url).hostname
  File "/usr/lib64/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'list'
Powered by CherryPy 6.0.2

**Comment by Safihre** [comment] 2017-01-06 08:42
@mgaulton your error resolved itself? 😃
