### ISSUE TITLE
3.1.0RC1 [56343b9] Error

### ISSUE THREAD

**Issue by DrakeJones** [sabnzbd/sabnzbd#1622] opened 2020-09-26 09:19 UTC
Got about 20 of these on the round of download attempts on the Queue/History page - ultimately got what I wanted though

ERROR 16 minutes ago ERROR DURING SCHEDULER EXECUTION The read operation timed out
Traceback (most recent call last):
  File "sabnzbd\utils\kronos.py", line 300, in __call__
  File "sabnzbd\utils\kronos.py", line 311, in execute
  File "sabnzbd\rss.py", line 88, in run_method
  File "sabnzbd\rss.py", line 560, in run
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\rss.py", line 287, in run_feed
  File "feedparser\api.py", line 214, in parse
  File "feedparser\api.py", line 114, in _open_resource
  File "feedparser\http.py", line 158, in get
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "feedparser\http.py", line 55, in http_error_301
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1393, in https_open
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1347, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out

**Comment by Safihre** [comment] 2020-09-26 09:33
Duplicate of #1621. Although this code didn't change... 
Indexers just seem to have become less stable? It just indicates the server didn't respond, not SABnzbd's fault..

**Closed by Safihre** 2020-09-26 09:33 UTC

**Comment by Safihre** [comment] 2020-09-26 09:39
Aaah, probably feedparser changed..

**Comment by DrakeJones** [comment] 2020-09-26 09:44
Okay.  Thanks.  I've just never seen that error before...

**Comment by Safihre** [comment] 2020-09-26 09:48
It is indeed a change in one of the dependencies of SABnzbd, will fix in #1621.
