### ISSUE TITLE
Saving Server Settings sometimes causes JSON response

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1129] opened 2018-04-17 08:23 UTC
When saving a server's settings like so:
![step 1](https://user-images.githubusercontent.com/17044982/38857275-39aa30da-426c-11e8-878d-c92c2759cfff.png)
it sometimes results in:
![step 2](https://user-images.githubusercontent.com/17044982/38857278-39e77616-426c-11e8-8468-cc9c55b695fe.PNG)
instead of a page (seems be more often when the "advanced settings" checkbox is checked.

I'm using 2.3.3RC2 [e0dc988].

**Comment by Safihre** [comment] 2018-04-17 10:02
Do you have any Javascript errors shown?
Does this also happen on a different browser? 
Asking because I can't reproduce it.

**Comment by Safihre** [comment] 2018-04-17 11:09
I can confirm that this happens when priority gets changed, did it happen other times as well?

**Comment by hl2guide** [comment] 2018-04-17 11:12
For it happens about every 8 save attempts. (i'll keep testing though)

**Comment by thezoggy** [comment] 2018-04-17 21:39
changing the priority (changing it from a value to something different than back to original value even) on saving causes it to navigate to the saveServer then submit the update.

**Comment by Safihre** [comment] 2018-04-18 17:52
When saving priorities we disable the Ajax submit and use 'normal' submit specially. But since we still provide the `json` parameter it would show the Ajax return.
@hl2guide did you find any more ways to show the JSON instead of normal page besides changing priority?

**Comment by hl2guide** [comment] 2018-04-19 12:01
Not yet I'll keep trying over the next few days.

**Comment by Safihre** [comment] 2018-04-20 13:05
Considering it closed by c872ee16ab29bd13f0078a7b96ba2abac6ef4566.
Re-open in case it persists after that!

**Closed by Safihre** 2018-04-20 13:05 UTC
