### ISSUE TITLE
1.0.0RC5 Config Tool Doesn't Correctly Disable "Ignore Samples"

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#510] opened 2016-03-14 19:17 UTC
If you uncheck "Ignore Samples" in the config and hit save, then refresh the page, it's checked again.

If I shutdown sab and set ignore_samples = 0 instead of 1. It now remains unchecked.

**Comment by Safihre** [comment] 2016-03-14 19:51
@shypike the problem is that this is an ```OptionNumber```, because it used to be possible to either select Delete before or after download. So on the save of the Switches page, it is ignored when not checked.
Easiest is to make it into an ```OptionBool```. But what happens if people have ```ignore_samples=2``` in their sabnzbd.ini? Let me test

**Comment by Safihre** [comment] 2016-03-14 19:59
Oke only here it seems to matter:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L705
The rest it just tests if it's ```> 0```

**Comment by Cpuroast** [comment] 2016-03-14 20:05
Pretty sure, it's related to the change made in https://github.com/sabnzbd/sabnzbd/issues/157.

**Comment by shypike** [comment] 2016-03-14 21:19
So, that needs to be fixed in 1.0.0.
Tomorrow.

**Closed** 2016-03-15 19:11 UTC
